### ISSUE TITLE
Avoid assembly scanning when resolving unregistered service

### ISSUE THREAD

**Issue by tpluscode** [seesharper/LightInject#103]
Hi

In on of my unit test classes I have a `ICompositionRoot` implementation, which I register with `RegisterFrom<T>()`. 

Unfortunately it breaks another test class, becuase LightInject scans the assembly and discovers that composition root when resolving unregiseterd service, for which I explicitly use the register fallback.

Is there a way to disable assembly scanning unless explicit?

Thanks,
Tom

**Comment by bounav** [comment]
Hello,

Just to clarify: Is registering a fallback that throws an exception the best way to prevent the assembly scanning from kicking in?

```csharp
container.RegisterFallback((type, s) => { throw new ApplicationException("Unknown type: " + type.Name);}, null);
```

Thanks!

**Comment by seesharper** [comment]
The best solution would probably be to implement a custom IAssemblyScanner that fits your needs. 
You could use the default implementation (AssemblyScanner) as a starting point for your implementation)

Or we could introduce an option to disable this

**Comment by bounav** [comment]
Thanks, that makes sense.

My `RegisterFallback` attempt was throwing exceptions for types like `bool` which wasn't great.

I as per your suggestion, I ended up implementing a dummy `IAssemblyScanner` class...

```csharp
public class DisabledAssemblyScanner : IAssemblyScanner
{
    public void Scan(Assembly assembly, IServiceRegistry serviceRegistry, Func<ILifetime> lifetime, Func<Type, Type, bool> shouldRegister)
    {
        // Do nothing!
    }

    public void Scan(Assembly assembly, IServiceRegistry serviceRegistry)
    {
        // Do nothing!
    }
}
```

...then setting it to the `ServiceContainer`:

```csharp
var container = new ServiceContainer { AssemblyScanner = new DisabledAssemblyScanner() };
```

If you ask me, I'd say _yes_, an option to disable assembly scanning would be nice to have. That or a mention of this trick in the documentation...?

**Comment by bounav** [comment]
I cloned the LightInject to see how adding the option to disable assembly scanning for unknown types would look like...

This is what I came up with:

1. Add a new option in the `ContainerOptions` class. The option would default to true so that the current behaviour isn't changed.

```csharp
public class ContainerOptions
{
    public ContainerOptions()
    {
        ...
        ScanAssembliesWhenRegistrationNotFound = true;
        ...
    }

    ...

    /// <summary>
    /// Gets or sets a value indicating whether to scan assemblies when a type is not registered.
    /// </summary>
    /// <remarks>
    /// The default value is true.
    /// </remarks>
    public bool ScanAssembliesWhenRegistrationNotFound { get; set; }

    ....
}
```

2. In the `ServiceContainer` class, tweak the `GetEmitMethod()`:

```csharp
private Action<IEmitter> GetEmitMethod(Type serviceType, string serviceName)
{
    Action<IEmitter> emitMethod = GetRegisteredEmitMethod(serviceType, serviceName);

    if (emitMethod == null)
    {
        emitMethod = TryGetFallbackEmitMethod(serviceType, serviceName);
    }

    if (emitMethod == null && options.ScanAssembliesWhenRegistrationNotFound)
    {
        AssemblyScanner.Scan(serviceType.GetTypeInfo().Assembly, this);
        emitMethod = GetRegisteredEmitMethod(serviceType, serviceName);

        if (emitMethod == null)
        {
            emitMethod = TryGetFallbackEmitMethod(serviceType, serviceName);
        }
    }
            
    return CreateEmitMethodWrapper(emitMethod, serviceType, serviceName);
}
```

I had a quick skim over the unit test project but didn't really know in which class I would add a test to cover that new scenario...

Anyway, do you think that would of this proposed change?
