### ISSUE TITLE
Support for .NET 3.5?

### ISSUE THREAD

**Issue by swquinn** [seesharper/LightInject#110]
First, I apologize if this is not the right forum for this question. I have been unable to find anything definitive in the documentation.

I'm bound to the Mono 2.x release which prevents me from using anything greater than .NET 3.5; it doesn't appear (at least through the official NuGet repositories) that LightInject supports .NET 3.5. Is this true? If true, is there an earlier version of LightInject that does support .NET 3.5?

Thanks!

**Comment by seesharper** [comment]
LightInject only support >= 4.0

**Comment by zldrq** [comment]
fyi: it's strange, the only place, where one can find this information is an issue at github
