### ISSUE TITLE
LightInject no longer overwrites registered services with new dependencies

### ISSUE THREAD

**Issue by mattnischan** [seesharper/LightInject#133]
In our project, our bootstrapping system supplies a set of default services via LightInject which users of the bootstrapper are free to overwrite with their own implementations. The following used to work a few months back:

```
[Test]
public void Test_Default_Service_Is_Overwritten()
{
    var container = new ServiceContainer();
    container.Register<IFoo, FooImpl>();
    var fooImpl = container.GetInstance<IFoo>();

    Assert.IsAssignableFrom(fooImpl, typeof(FooImpl));

    container.Register<IFoo, OtherFooImpl>();
    var otherFooImpl = container.GetInstance<IFoo>();

    Assert.IsAssignableFrom(otherFooImpl, typeof(OtherFooImpl));
}
```

However, this test now fails. It seems that there is no way of overwriting an existing service with a different implementation. Is this intended?

**Comment by tom3m** [comment]
That's right. This behaviour is actually intended. The fact is that
allowing a service to be overridden after it has been requested for the
first time, opened up for some potential "bugs" that would be very tough to
debug. You can still override an existing registration as long as you do it
before it is requested from the container for the first time.


Godness ((((
We're moving away from old Unity and was going to use LightInject
But the fact that it does not allows to override any dependency in any given moment make that not possible.  In the production scenarion that behaviour is absolutely fine but im tests... ((
Could that behaviour be optional so we could set that option in tests?

**Comment by dotnetjunkie** [comment]
> We're moving away from old Unity and was going to use LightInject
But the fact that it does not allows to override any dependency in any given moment make that not possible

Can you describe what you think exactly works in Unity, because overriding already resolved registrations are already resolved (both directly or indirectly) is riddled with bugs in **every** container. That's why noth Ninject and Autofac are moving to a model where it becomes impossible to change the container after it has been built, and that's why Simple Injector dissalowed this from day 1.

**Comment by tom3m** [comment]
>>Can you describe what you think exactly works in Unity
Imagine scenario, you have code that sets up the container, then you have test that needs to override some deps with mocks/stubs, or you have a tests framework that in some calls overrides some deps with mocks/stubs. That is very common pattern in the integration testing. When you need to mock external dependency like e.g. another web service or database or etc.. Or you just need to mock your internal code to simulate something

**Comment by dotnetjunkie** [comment]
Hi Tom,

You just describes _why_ you need this, but not why you think this will actually work as expected in Unity. As I said, it won't work in Unity, as it doesn't work in _any_ container. This problem is described in more detail [here](https://simpleinjector.readthedocs.io/en/latest/decisions.html#container-is-locked).

For your specific scenario, don't reuse the same container instance for all integration tests. Even if it could work, it will cause concurrency conflicts when you run your tests in parallel. You should create a new container instance for each integration tests. Each test can add or override the registrations it requires for it test, but you will never have to be able to replace registrations when you already resolved from the container.

In case you might want to influence the used instance after the object graphs have been built (which is a quite common scenario), you can use proxies or composites that allow you to switch from one implementation to the other at runtime.

**Comment by tom3m** [comment]
>>You just describes why you need this, but not why you think this will actually work as expected in Unity. As I said, it won't work in Unity, as it doesn't work in any container. This problem is described in more detail here.

We had it working in Microsoft Unity for many years with no problem, not sure how it works in the latest version as we were using version 2.<something>

>>For your specific scenario, don't reuse the same container instance for all integration tests. Even if it could work, it will cause concurrency conflicts when you run your tests in parallel.
We run test in parallel in the separate processes, again for years,  there are many potential problems when running tests in parallel in the same process.

In general I do not agree with statement that such a feature could cause bugs/problems, you need to note it is mainly needed just in testing scenarios, in the prod scenario there are rare cases when it might be usefull. Imagine pluging subsystem where plugin could override base app implementation.

Anyway, what I need seems to be working in other top containers, like DryIoc.

**Comment by seesharper** [comment]
Bottom line here is that shared state between tests should be avoided. The cost of setting up the container for each test is negligible in most cases. Tests should be able to run in parallell in a non-deterministic order.

**Comment by tom3m** [comment]
100% agree, but that is not related to the problem described by the topic starter.
Just FYI: I'm now trying to use DryIoc and there you even can specify behavior, what do you want to do when there is already a registration exist, do you want to append or you want to replace or etc. Replacing works perfectly at any stage. So I don't see the reason why it can't work in the LightInject. Would love to see the issue reopened

**Comment by kgoyal1** [comment]
Could you describe how to register at any time in lightinject? I couldn't find anything yet?

**Comment by seesharper** [comment]
You can't. 

> So the basic rule here is that you can add new services after the first
request, but you cannot modify an existing service registration.

> In your case you need to make sure that you allow for custom bootstrapping
before the first request to the container is made.

**Comment by dadhi** [comment]
@tom3m,

>  I'm now trying to use DryIoc and there you even can specify behavior, what do you want to do when there is already a registration exist, do you want to append or you want to replace or etc. Replacing works perfectly at any stage. So I don't see the reason why it can't work in the LightInject.

I am author of DryIoc. And yes, the replacement works in DryIoc, __but it is not free for your container setup__. It may work for your specific case without any specific modifications to container and registrations, but you still should be aware of possible [cache issues](https://bitbucket.org/dadhi/dryioc/wiki/UnregisterAndResolutionCache) (the article is about `Unregister` but issues are the same).
So for a good practice I would recommend __avoid this feature if you can__, or in other words __do it if you know what you doing__.
Btw, even DryIoc has `IContainer.WithNoMoreRegistrationAllowed` method to make container a resolve-only.

**Comment by kgoyal1** [comment]
Thanks for explanation. I need this functionality for testing.
I have a class below
private class ServiceControllerSpecsMessageProvider : IRequestMessageProvider
{
public ServiceControllerSpecsMessageProvider(ServiceControllerMultipleSpecsAsync specs)
{
this.Specs = specs;
}
public HttpRequestMessage CurrentMessage
{
get
{
return this.Specs.inputs.Last();
}
}
private ServiceControllerMultipleSpecsAsync Specs { get; set; }
}

And I am trying to override like this:
container.Override(r => r.ServiceType == typeof(IRequestMessageProvider),
(f, r) => new ServiceRegistration()
{
ServiceType = typeof(IRequestMessageProvider),
ImplementingType = typeof(ServiceControllerSpecsMessageProvider),
Lifetime = new PerScopeLifetime(),
ServiceName = ""
});

But its not working. Any suggestions?

**Comment by kgoyal1** [comment]
Hi @seesharper 
Could you please elaborate with example? As I mentioned above I need this behaviour for testing so httprequest can be overridden.
Thanks in advance
Karuna

**Comment by seesharper** [comment]
Hei @kgoyal1 
Could you create a minimal and simple repro for what you are trying to do? Put it up on GitHub and we will PR a solution for you
