### ISSUE TITLE
Allow IServiceFactory to be injected into classes

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject#135]
````
public class Foo
{
	public Foo(IServiceFactory factory)
	{

	}
}

container.Register<Foo>(factory => new Foo(factory));
container.Register<Foo>();
````

**Comment by LightInjectedVenom** [comment]
Hi Bernhard.

I have been using LightInject in my projects for half year and I already addicted to it.

For a while I have been researching to understand whether injecting IServiceFactory like classes should be considered good or not.

What do you think about injecting IServiceFactory to other classes ? Should it be considered service locator anti-pattern. If that is not the case would you please explain me why it is not ?

Thank you.

**Comment by seesharper** [comment]
The reason that injecting IServiceFactory (or any other type that belongs to the container) is considered an anti-pattern, is that you make a very strong connection between your class and the underlying container. Instead of injecting IServiceFactory you could just inject a Func<IWhateverInterface> . That makes the class dependant upon Func<T> instead.

**Comment by LightInjectedVenom** [comment]
Hi Bernhard. 

Your help is much appreciated.

Thank you and thank you again for providing us with a such a nice DI library.

Take care.

**Comment by seesharper** [comment]
No problem :)
