### ISSUE TITLE
Set default lifetime for container

### ISSUE THREAD

**Issue by geirsagberg** [seesharper/LightInject#136]
Hi, is it possible to set default lifetime for a container somehow? I can't for the life of me figure out how...

If not, this would be an awesome addition to this awesome library :)

Specifically, I would like to do something like this:

```
container.SetDefaultLifetime<PerScopeLifetime>();
container.Register<IFirstService, FirstService>();
container.Register<ISecondService, SecondService>();
container.Register<IThirdService, ThirdService>();
```
instead of specifying the lifetime every time:

```
container.Register<IFirstService, FirstService>(new PerScopeLifeTime());
container.Register<ISecondService, SecondService>(new PerScopeLifeTime());
container.Register<IThirdService, ThirdService>(new PerScopeLifeTime());
```

**Comment by geirsagberg** [comment]
Added a pull request, only took me a year ;)

**Comment by seesharper** [comment]
Thanks a lot:)

**Comment by naeemkhedarun** [comment]
Nice one @geirsagberg we also need the same thing!
