### ISSUE TITLE
xUnit package doesn't work with xUnit version 2

### ISSUE THREAD

**Issue by Hinidu** [seesharper/LightInject#149]
Hello!
LightInject.xUnit can't be installed via NuGet with xUnit 2 and LightInject.xUnit.Source can't be compiled against it.
Since xUnit 2 is still in beta I think the good approach would be to make prerelease version of LightInject.xUnit package for it. Because most of the time developers are using prerelease versions of either none or all dependencies. So this would provide pleasant experience: if one use xUnit 1.* NuGet will automatically download LightInject.xUnit stable release for that but if one use xUnit 2.* it will be happy with automatically downloaded prerelease version of LightInject.xUnit.
What do you think?
I suppose I can implement this feature if I will have some free time in the near future.
Thanks.

**Comment by Hinidu** [comment]
Yesterday xUnit 2.0 was [released](http://xunit.github.io/release-notes/2015-03-16.html).

**Comment by seesharper** [comment]
Hi. I have just started to take a look at xUnit 2.0 and it seems that they have introduced a number of breaking changes. I would have to look into the details and confirm that they still provide similar extension points that makes the integration with an IoC container possible.

**Comment by Hinidu** [comment]
Great! FWIW: one of the goals of xUnit v2 were further improvements in extensibility. So I'm pretty sure that it is still possible.

**Comment by seesharper** [comment]
LightInject.xUnit 2.0.0.0 has just been published to the official Nuget feed.
