### ISSUE TITLE
WebApi: Attempt to end a scope before all child scopes are completed.

### ISSUE THREAD

**Issue by paiden** [seesharper/LightInject#153]
I'm using LightInject in a ASP.NET WebApi project. When the API call exits, I sometimes get the error:
  System.InvalidOperationException occurred
  HResult=-2146233079
  Message=Attempt to end a scope before all child scopes are completed.
  Source=LightInject
  StackTrace:
       at LightInject.ScopeManager.EndScope(Scope scope) in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:line 4727
  InnerException: 
Additional information: Attempt to end a scope before all child scopes are completed.

I currently have no clue why I get this error.

More information about my project:
+ LighInject v3.0.2.1
+ LightInject.WebApi v1.0.0.3
+ WebApi 2.1
+ WebApi is self hosted in console
+ Container setup:
```C#
    var container = new ServiceContainer();
    container.RegisterApiControllers(CustomAssemblyResolver.GetControllerAssemblies().ToArray());
    Bootstrapper.Bootstrap(container); //performs service registration 
    container.EnableWebApi(config);
```

**Comment by seesharper** [comment]
Try this

```
container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
```

**Comment by paiden** [comment]
That did the trick. Now that you mentioned the scope manager I also found the 'Async/Await  'and 'OWIN selfhosting' sections in the documentation that would have pointed me into the right direction. 

Thank you very much for your help.

**Comment by seesharper** [comment]
You're welcome:)

**Comment by 0xced** [comment]
@seesharper I just got bitten by this too. Would you accept a pull request that makes `PerLogicalCallContextScopeManagerProvider` the default `ScopeManagerProvider` on target frameworks where it's available ? Do you think it makes sense ?
