### ISSUE TITLE
Proxy object does not implements all original object interfaces.

### ISSUE THREAD

**Issue by VladimirSmall** [seesharper/LightInject#154]
See test.

```csharp
namespace LightInjectInterceptBug
{
    using LightInject;
    using LightInject.Interception;

    using NUnit.Framework;

    [TestFixture]
    public class CastProxyBugTests
    {
        public interface IMarkerInterface
        {
        }

        public interface IAnyInterface
        {
            void AnyMethod();
        }

        public class AnyClass : IAnyInterface, IMarkerInterface
        {
            public void AnyMethod()
            {
            }
        }

        public class AnyInterceptor : IInterceptor
        {
            public object Invoke(IInvocationInfo invocationInfo)
            {
                return invocationInfo.Proceed();
            }
        }

        [Test]
        public void Bug()
        {
            var container = new ServiceContainer();
            container.Register<IAnyInterface, AnyClass>();

            container.Intercept((ServiceRegistration sr) => sr.ServiceType == typeof(IAnyInterface), 
                sf => new AnyInterceptor());

            var anyInterface = container.GetInstance<IAnyInterface>();

            Assert.IsNotNull(anyInterface as IMarkerInterface); // bug
        }
    }
}
```
Known workaround: inherit IAnyInterface from IMarkerInterface

**Comment by seesharper** [comment]
This is not really a bug. Here we have an interface based proxy that implements IAnyInterface. Only the concrete type (AnyClass) knows about this interface. If you want to have the proxy implement the interface you would have to explicitly define this.

    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.Register<IAnyInterface, AnyClass>();

            container.Intercept(
                sr => sr.ServiceType == typeof(IAnyInterface),
                new[] { typeof(IMarkerInterface) },
                (factory, definition) => definition.Implement(() => new AnyInterceptor()));
            
            var anyInterface = container.GetInstance<IAnyInterface>();
            
            Debug.Assert((anyInterface as IMarkerInterface) != null);
        }
    }


    public interface IMarkerInterface
    {
    }

    public interface IAnyInterface
    {
        void AnyMethod();
    }

    public class AnyClass : IAnyInterface, IMarkerInterface
    {
        public void AnyMethod()
        {
        }
    }

    public class AnyInterceptor : IInterceptor
    {
        public object Invoke(IInvocationInfo invocationInfo)
        {
            return invocationInfo.Proceed();
        }
    }
