### ISSUE TITLE
Generic variance

### ISSUE THREAD

**Issue by vegar** [seesharper/LightInject#156]
@jbogard wrote a piece on [generic variance support in DI containers](http://lostechies.com/jimmybogard/2015/01/13/generic-variance-in-di-containers/) a couple of days ago. 

I decided to take a shot at implementing the example that he had made with LightInject. I'm not sure, though if I have done it right. 

Please take a look at the following thread: https://github.com/jbogard/MediatR/pull/18

What are the limitations for registering and resolving generic types in LightInject?

**Comment by seesharper** [comment]
Working on this now.

**Comment by seesharper** [comment]
LightInject 3.0.2.2 has been published to the official NuGet feed.

Take a look at the following setup for working with MediatR.

    class Program
    {
        static void Main(string[] args)
        {
            var mediator = BuildMediator();

            Runner.Run(mediator, Console.Out);

            Console.ReadKey();
        }

        private static IMediator BuildMediator()
        {
             var serviceContainer = new ServiceContainer();
            serviceContainer.Register<IMediator, Mediator>();
            serviceContainer.RegisterInstance(Console.Out);
            serviceContainer.RegisterAssembly(typeof(Ping).Assembly, (serviceType, implementingType) => !serviceType.IsClass);
            serviceContainer.RegisterAssembly(typeof(IMediator).Assembly, (serviceType, implementingType) => !serviceType.IsClass);
            var serviceLocator = new LightInjectServiceLocator(serviceContainer);
            serviceContainer.RegisterInstance(new ServiceLocatorProvider(() => serviceLocator));
            return serviceContainer.GetInstance<IMediator>(); 
        }
    }

**Comment by vegar** [comment]
nice.
