### ISSUE TITLE
Using log4net and named logger / calling type

### ISSUE THREAD

**Issue by fractalfractal** [seesharper/LightInject#157]
I am trying to inject log4net, which has the dependency on the caller's Type. (FYI: I wrap my log4net implementation in a ILogService). Code snippet below.

In Unity, this blog posts shows how they handled it:
http://blog.baltrinic.com/software-development/dotnet/log4net-integration-with-unity-ioc-container

I believe someone asked a similar question here (issue #91), but there was not resolution
https://github.com/seesharper/LightInject/issues/91

If you can provide further guidance, it would be greatly appreciated. We've heard great reviews on the performance LightInject (good work btw!) so we would love to switch over to this if we can resolve this. Thanks! 

When using Unity, I only need to do something like this:
            container.AddNewExtension<BuildTracking>(); // see article link for more info
            container.AddNewExtension<LogCreation>();  // see article link for more info
            container.RegisterType<ILogService, log4netLogService>();
            container.RegisterType<ISampleService, SampleService>();

    public class log4netLogService : ILogService
    {
        private ILog _log = null;
        public log4netLogService(System.Type callersType)
        {
            _log = LogManager.GetLogger(callersType); 
        }
        public void WriteDebug(string message)
        {
            _log.Debug(message);
        }

    public class SampleService : ISampleService
    {
        private ILogService _logService = null;
        public SampleService(ILogService logService) 
        {
            _logService = logService;
        }

**Comment by seesharper** [comment]
The problem with relying on the implementing type (caller's type) is that this information is not necessarily available to us at the time of construction.

One example of this is when we use a factory to create the instance.

	container.Register<IFoo>(factory => CreateFoo());

	private IFoo CreateFoo()
	{
		return new Foo();
	}

In this scenario, the container knows absolutely nothing about the *Foo* class since the actual instance is produced by the factory delegate.

The only place where we can safely rely on the implementing type, is within the implementing type itself.

By making the *ILogService* generic we can safely provide this information. 

We go from this 

	public class Foo
	{
		private ILogService logService;

		public Foo(ILogService logservice)
		{
			this.logService = logService;
		}
	}


to this 

	public class Foo
	{
		private ILogService<Foo> logService;

		public Foo(ILogService<Foo> logservice)
		{
			this.logService = logService;
		}
	}

The ONLY difference is that you have to specify the generic argument type (implementing type).

The ONLY registration you need to get this working is this

	container.Register(typeof(ILogServicer<>), typeof(LogService<>));	

The rest of the services that relies on this logger can be registered in any way that you want.

Another advantage of this is that if you should need a "special" *ILogService* for a given type, you can simply implement the interface and the container will inject that logservice instead.


	public class BarLogService : ILogService<Bar>
	{
		...
	}

	container.Register<ILogService<Bar>, BarLogService>

**Comment by seesharper** [comment]
After thinking about this for a while I have found a solution that seem to work as expected.

    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.ConstructorDependencySelector = new CustomConstructorDependencySelector();
            container.Register<IFoo, Foo>();
            container.GetInstance<IFoo>();
        }

        public class CustomConstructorDependencySelector : ConstructorDependencySelector
        {
            public override IEnumerable<ConstructorDependency> Execute(ConstructorInfo constructor)
            {
                ConstructorDependency[] dependencies = base.Execute(constructor).ToArray();

                ConstructorDependency logDependency = dependencies.FirstOrDefault(d => d.ServiceType == typeof(ILog));
                if (logDependency != null)
                {
                    Expression<Func<ILog>> factoryExpression = () => LogManager.GetLogger(constructor.DeclaringType);
                    logDependency.FactoryExpression = factoryExpression.Body;
                }

                return dependencies;
            }
        }

        public interface IFoo { }

        public class Foo : IFoo
        {
            public Foo(ILog log)
            {
                Debug.Assert(log.Logger.Name == typeof(Foo).FullName);
            }
        }
    }

**Comment by LukeDefeo** [comment]
thanks @seesharper this is almost what we want however we prefer to use property injection for loggers, can you provide a solution that works in this way.

Cheers

**Comment by fractalfractal** [comment]
Thanks, that is the type of solution I was looking for. It is very similar to how Unity does it. As I get the chance, I will give this a try.

**Comment by seesharper** [comment]
The same thing, now using property injection.

    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.PropertyDependencySelector = new CustomPropertyDependencySelector();
            container.Register<IFoo, Foo>();
            var instance = container.GetInstance<IFoo>();

            Debug.Assert(((Foo)instance).Log.Logger.Name == typeof(Foo).FullName);
        }
        
        public interface IFoo { }

        public class Foo : IFoo
        {
            public ILog Log { get; set; }
        }


        public class CustomPropertyDependencySelector : PropertyDependencySelector
        {
            public CustomPropertyDependencySelector()
                : base(new PropertySelector())
            {
            }

            public override IEnumerable<PropertyDependency> Execute(Type type)
            {
                PropertyDependency[] dependencies = base.Execute(type).ToArray();

                PropertyDependency logDependency = dependencies.FirstOrDefault(d => d.ServiceType == typeof(ILog));
                if (logDependency != null)
                {
                    Expression<Func<ILog>> factoryExpression = () => LogManager.GetLogger(type);
                    logDependency.FactoryExpression = factoryExpression.Body;
                }

                return dependencies;
            }
        }
    }

**Comment by sovetkin** [comment]
First, I'd like to express my sincere thanks for the excellent work. However, it appears that the current solution is no longer functioning as expected.

LightInject provides a more elegant alternative, which I've included below:

```C#
var container = new ServiceContainer();
container..RegisterConstructorDependency((_, parameter) => LogManager.GetLogger(parameter.ParameterType));
container.Register<IFoo, Foo>();
var instance = container.GetInstance<IFoo>();
```
```C#
public interface IFoo { }

public class Foo : IFoo
{
    public Foo(ILog log)
        {
            Debug.Assert(log.Logger.Name == typeof(Foo).FullName);
        }
}
```

For property injection, you can use RegisterPropertyDependency<>().
