### ISSUE TITLE
Windows Store Apps 8.1 common usage bug

### ISSUE THREAD

**Issue by Centurys** [seesharper/LightInject#158]
Hi,

i have tried to use this lib on "Windows Store Apps 8.1" app project and I
keep getting this exception:
System.ArgumentException was unhandled by user code
  HResult=-2147024809
  Message=Argument for array index must be of type Int32
  Source=System.Core
  StackTrace:
       at System.Linq.Expressions.Expression.ArrayAccess(Expression array, IEnumerable`1 indexes)
       at System.Linq.Expressions.Expression.ArrayAccess(Expression array, Expression[] indexes)
       at LightInject.ILGenerator.Emit(OpCode code)
       at LightInject.Emitter.<>c__DisplayClass1.<Emit>b__0(ILGenerator il)
       at LightInject.Emitter.Emit(OpCode code)
       at LightInject.EmitterExtensions.Return(IEmitter emitter)
       at LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter)
       at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
       at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
       at LightInject.ServiceContainer.GetInstance(Type serviceType)
       at aa.App..ctor()
       at aa.Program.<Main>b__0(ApplicationInitializationCallbackParams p)
  InnerException: 

Code sample:
private readonly ServiceContainer _container = new ServiceContainer();
_container.Register<ILauncher, LauncherWindows>(new PerContainerLifetime());
...
var a = _container.GetInstance(typeof(...));
var a2 = _container.GetInstance(typeof(...));
var a3 = _container.GetInstance(typeof(...));
var a4 = _container.GetInstance(typeof(ILauncher));

4'th GetInstance call throws exception, any ideas?

**Comment by seesharper** [comment]
Could you please provide the full example?

**Comment by seesharper** [comment]
I have tried to reproduce this in a unit test (windows store 8.1), but this test works as expected.

    [TestClass]
    public class UnitTest1
    {        
        [TestMethod]
        public void TestMethod1()
        {
            var container = new ServiceContainer();
            container.Register(typeof(IFoo), typeof(Foo), new PerContainerLifetime());
            var f1 = container.GetInstance(typeof(IFoo));
            var f2 = container.GetInstance(typeof(IFoo));
            var f3 = container.GetInstance(typeof(IFoo));
            var f4 = container.GetInstance(typeof(IFoo));
        }
    }


    public interface IFoo { }

    public class Foo : IFoo
    {
    }

**Comment by Centurys** [comment]
I only can give you rewritten code example with changed type names and implementation, exception is still thrown on  4'th GetInstance:
using System;
using LightInject;
using Windows.ApplicationModel;
using Windows.ApplicationModel.Activation;
using Windows.UI.Xaml;
using Windows.UI.Xaml.Controls;
using Windows.UI.Xaml.Navigation;

namespace App4
{
	sealed partial class App : Application
	{
		private readonly ServiceContainer _container = new ServiceContainer();

		public App()
		{
			this.InitializeComponent();
			this.Suspending += OnSuspending;

			_container.Register<IFoo8, Foo8>(new PerContainerLifetime());
			_container.Register<IFoo9, Foo9>(new PerContainerLifetime());
			_container.Register<IFoo2, Foo2>(new PerContainerLifetime());
			_container.Register<IFoo6, Foo6>(new PerContainerLifetime());
			_container.Register<IFoo5, Foo5>(new PerContainerLifetime());
			_container.Register<IFoo1, Foo1>(new PerContainerLifetime());
			_container.Register<IFoo4, Foo4>(new PerContainerLifetime());
			_container.Register<IFoo3, Foo3>(new PerContainerLifetime());
			_container.Register<IFoo7, Foo7>(new PerContainerLifetime());
			_container.Register<IFoo, Foo>(new PerContainerLifetime());

			var a = _container.GetInstance(typeof(IFoo));
			var a2 = _container.GetInstance(typeof(IFoo2));
			var a3 = _container.GetInstance(typeof(IFoo3));
			var a4 = _container.GetInstance(typeof(IFoo4));
		}

		protected override void OnLaunched(LaunchActivatedEventArgs e) { ... }

		private void OnSuspending(object sender, SuspendingEventArgs e) { ... }
	}

	public interface IFoo { }
	public interface IFoo1 { }
	public interface IFoo2 { }
	public interface IFoo3 { }
	public interface IFoo4 { }
	public interface IFoo5 { }
	public interface IFoo6 { }
	public interface IFoo7 { }
	public interface IFoo8 { }
	public interface IFoo9 { }

	public class Foo : IFoo
	{
		public Foo(IFoo5 foo5, IFoo6 foo6, IFoo7 foo7, IFoo8 foo8, IFoo9 foo9)
		{
		}
	}

	public class Foo1 : IFoo1
	{
	}

	public class Foo2 : IFoo2
	{
	}

	public class Foo3 : IFoo3
	{
	}

	public class Foo4 : IFoo4
	{
	}

	public class Foo5 : IFoo5
	{
	}

	public class Foo6 : IFoo6
	{
	}

	public class Foo7 : IFoo7
	{
		public Foo7(IFoo5 foo5, IFoo6 foo6, IFoo9 foo9)
		{
		}
	}

	public class Foo8 : IFoo8
	{
		public Foo8(IFoo5 foo5, IFoo1 foo1)
		{
		}
	}

	public class Foo9 : IFoo9
	{
	}
}

**Comment by seesharper** [comment]
I got it. I'll let you know when a new nuget package has been published
(tomorrow).

**Comment by seesharper** [comment]
LightInject 3.0.2.3 is now available from the official Nuget feed.

**Comment by Centurys** [comment]
Thanks
