### ISSUE TITLE
Using a private readonly string instead of a const breaks named service registrations

### ISSUE THREAD

**Issue by mnmr** [seesharper/LightInject#161]
I was using the following snippet in my CompositionRoot:

        private const EIdentity identity = EIdentity.Foo;
        private readonly string registrationName = identity.ToString();

        public void Compose(IServiceRegistry registry)
        {
            registry.Register<ICoordinator>(sr => new Coordinator(identity, 
                 sr.GetInstance<IRootTokenProvider>()), registrationName);

            registry.Register<IMatcher>(sr => new Matcher(
                sr.GetInstance<IConfiguration>(registrationName),
                sr.GetInstance<ICoordinator>(registrationName),
                sr.GetInstance<ISessionFactory>(),
                sr.GetInstance<IDataChannelPublisher>()),
                registrationName, new PerContainerLifetime());
        }

With this code, only implicitly registered services can be resolved. If I change the registrationName field to be const "Foo" then everything works as it should.

**Comment by seesharper** [comment]
Could you come up with a simple (Foo, Bar) example that demonstrates this
behavior?

**Comment by seesharper** [comment]
Should be fixed in LightInject > 4.0.2
