### ISSUE TITLE
All public properties of type Func interpreted as factories

### ISSUE THREAD

**Issue by mattnischan** [seesharper/LightInject#162]
We're having an issue with the following kind of situation:

    interface IFoo<T>
    {
        Func<T, bool> Function { get; set; }
    }

    class Bar : IFoo<int>
    {
        public Func<int, bool> Function { get; set; }

        public Bar()
        {
            this.Function = x => x == 5;
        }
    }

    class Baz : IFoo<int>
    {
        public Func<int, bool> Function { get; set; }

        public Baz()
        {
            this.Function = x => x == 5;
        }
    }

    [Test]
    public void Test_Unintended_LightInject_Factories()
    {
        var container = new ServiceContainer();
        container.Register<IFoo<int>, Bar>("Bar");
        container.Register<IFoo<int>, Baz>("Baz");

        var x = 5;
        foreach(var service in container.GetAllInstances<IFoo<int>>())
        {
            Assert.IsInstanceOf<Func<int, bool>>(service.Function);
            Assert.IsTrue(service.Function(x)); //InvalidOperationException: Unable to resolve type: System.Boolean, service name:
        }
    }

Is it the desired behavior for LightInject to interpret any public Func as some kind of service factory? I don't see that in the documentation anyplace.

Thanks!
-Matt

**Comment by seesharper** [comment]
No but it treats all public properties with a public getter and public
setter as properties whos dependencies are injected. Make the setter
private and you are good to go. The private setter is still available in
the constructor.

**Comment by mattnischan** [comment]
Thanks Bernhard. I'll close this issue and make a note of it for our team in the future.
