### ISSUE TITLE
Using function factory to create named instance when two named instances for interface exist

### ISSUE THREAD

**Issue by bjporada** [seesharper/LightInject#168]
I can work around it by creating a factory wrapper then use GetInstance directly off container.

public interface IBar { }
        public class Bar1 : IBar { }
        public class Bar2 : IBar { }

        [TestMethod]
        public void IBar_Two_NamedInstances_FuncFactory()
        {
            var serviceContainer = new ServiceContainer();
            serviceContainer.Register<IBar, Bar1>("bar1");
            serviceContainer.Register<IBar, Bar2>("bar2");

            var factory = serviceContainer.GetInstance<Func<string, IBar>>();

            //fail
            var bar = factory("bar1");
        }

        [TestMethod]
        public void IBar_One_NamedInstance()
        {
            var serviceContainer = new ServiceContainer();
            serviceContainer.Register<IBar, Bar1>("bar1");

            var factory = serviceContainer.GetInstance<Func<string, IBar>>();

            //success
            var bar = factory("bar1");
        }        

        [TestMethod]
        public void IBar_Two_NamedInstances_GetInstance()
        {
            var serviceContainer = new ServiceContainer();
            serviceContainer.Register<IBar, Bar1>("bar1");
            serviceContainer.Register<IBar, Bar2>("bar2");

            //success
            var bar = serviceContainer.GetInstance<IBar>("bar1");
        }

**Comment by seesharper** [comment]
The reason that this is happening is that Func&lt;string, T&gt; represents an ambiguity between a named service and a service that takes a string as a runtime argument. This behavior is not ny any means ideal, but as you said it can be worked around using a factory wrapper.
