### ISSUE TITLE
Where's `container.EnablePerWebRequestScope()`

### ISSUE THREAD

**Issue by ronnieoverby** [seesharper/LightInject#170]
The documentation says to use this when integrating with Web API when hosting in ASP.NET. I can't find it. Has it been removed?

**Comment by seesharper** [comment]
You need to install LightInject.Web to get access to that method. If you are on .Net 4.5 you can do the following instead:

    container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();

That way the container does not rely on System.Web which in turn ties it to IIS.

**Comment by omnibs** [comment]
Also had the same issue. 

If the LightInject website had a repo I'd be making a pull request to document that.

**Comment by Shazwazza** [comment]
If we use this instead of `container.EnablePerWebRequestScope();` does this mean we don't need to reference LightInject.Web at all? Since LightInject.Web includes the modules to dispose on the end of the request, etc... how would this work without it?

**Comment by seesharper** [comment]
The story with HttpContext, async/await and different versions of the framework is quite difficult to understand and quite frankly I don't even remember the details around this. LightInject.Web uses the HttpContext.Current to manage the scope. This could apparently break apart when using async/await unless you configure it correctly.   
Take a look here for a brief explanation
http://blog.alextercete.com/keep-your-context-around/

The PerLogicalCallContextScopeManagerProvider uses what is known as the Logical Thread Context to manage scopes. This is implemented using the CallContext class on .net 4.5 and the new AsyncLocal on .Net 4.6. These classes ensures that scopes are tied to the logical thread of execution flowing across await points. There is also a thing call ASP.NET thread agility that means that ASP.NET can suddenly move work from one thread to another and I really don't know how well that plays with the logical thread context.

**Comment by seesharper** [comment]
Also take a look here
http://stackoverflow.com/questions/22924048/is-it-possible-to-detect-if-you-are-on-the-synchronous-side-of-an-async-method

Stephen Cleary, which is the man when it comes to threading and async/await seems to think the logical call context should flow even in thread agility scenarios.

**Comment by Shazwazza** [comment]
Thanks for the links, that all makes sense. I guess what I'm wondering though is what is the best practices for LightInject with web apps in .Net 4.5+, should I use either or both:
`PerLogicalCallContextScopeManagerProvider` and `EnablePerWebRequestScope` ?

Since I still need LightInject.Mvc and WebApi for the DependencyResolvers and they require LightInject.Web I can't really remove the dependency on LightInject.Web anyways.
