### ISSUE TITLE
LightInject 3.0.2.5 RegisterFallback + .Create() = StackOverflow exception

### ISSUE THREAD

**Issue by Scratch-net** [seesharper/LightInject#173]
Hello there.
I'm using latest 3.0.2.5
I tried to follow #139 to automatically create concrete types using fallback and .Create() but it somehow loops itself and I don't understand why. 

Here is my test code:

	public class Foo
	{
		public Foo(IBar bar, IBar2 bar2)
		{
			
		}
	}

	public interface IBar2
	{
	}

	class Bar2 : IBar2
	{
	}

	public interface IBar
	{
	}

	class Bar : IBar
	{
	}

	private ServiceContainer container = new ServiceContainer();

	container.RegisterFallback((t, s) => true, Factory);
	container.Register<IBar, Bar>();
	container.Register<IBar2, Bar2>();
	var foo = container.GetInstance<Foo>(); // Error here

	private object Factory(ServiceRequest req)
	{
		return container.Create(req.ServiceType);
	}

Could you please advise?

**Comment by scratch-net** [comment]
It loops even if the Factory method looks like this:

		private object Factory(ServiceRequest req)
		{
			container.Register(typeof(Foo));
			return container.GetInstance<Foo>();
		}

but works perfectly if I register Foo beforehand (which I obviously want to avoid)

		container.Register<Foo>();

**Comment by seesharper** [comment]
The bug has been confirmed and is being looked into

**Comment by seesharper** [comment]
The following workaround should work.


        [TestMethod]
        public void Create_UsingFallback_ReturnsInstance()
        {
            var container = CreateContainer();
            container.RegisterFallback(
                (type, s) =>
                    {
                        container.Register(type);
                        return false;
                    },
                null);

            var instance = container.GetInstance<Foo>();
            Assert.IsInstanceOfType(instance, typeof(Foo));   
        }

The trick here is to use the predicate as a hook to register the missing service.
While this is not ideal, it ensures that the service is registered by the time it is resolved.

Best regards 
Bernhard Richter

**Comment by scratch-net** [comment]
It's not that critical, I can wait till the fix become available, but thanks for the workaround.

**Comment by scratch-net** [comment]
I'm sorry, but I still reproduce the bug in 3.0.2.6

**Comment by seesharper** [comment]
The 3.0.2.6 release does not include a fix for this. I suggest that you use the suggested workaround for now as focus now is to get things ready for Visual Studio 2015 and the CoreCLR.

**Comment by scratch-net** [comment]
Hi @seesharper , If you add this workaround code inside a WebApi project, You'll get

[InvalidOperationException: Missing public constructor for Type: System.Web.Http.Metadata.ModelMetadataProvider]

So, workaround won't help either

**Comment by seesharper** [comment]
You could filter the types based on the namespace and only register the concrete types if they belong to a namespace containing the types you would like to register.

**Comment by scratch-net** [comment]
Yep, looks like working, will test further
