### ISSUE TITLE
RegisterConstructorDependency requires Expression<Func>

### ISSUE THREAD

**Issue by twhitbeck** [seesharper/LightInject#176]
Is there a necessary reason `RegisterConstructorDependency` takes an `Expression<Func>` rather than just a `Func`? Requiring an `Expression` limits the logic that can be placed in the lambda.

If that's an intentional limitation, that's fine. I may be abusing the feature. Perhaps there's a better way to achieve what I'm doing:
A few of my services require `string` parameters for configuration. The implementing type for some is defined in my Web.config, so I don't want to use explicit registration. Using `RegisterConstructorDependency` for type `string` allows me to specify what strings to use depending on the implementing type and parameter name. Is there a cleaner way? Or could `RegisterConstructorDependency` be reconfigured to take a `Func`?

**Comment by seesharper** [comment]
The reason that it is an Expression is that the underlying service
registration is based on this. Without going into all the details,
LightInject sometimes inspects the Expression tree to infer the
implementing type. If found, we can do some minor performance improvements.

If you need to do more advanced stuff in the registration you could always
just extract the code into a private method and call that in the expression
factory. LightInject will do nothing else than compile the expression tree
and call your method.

**Comment by twhitbeck** [comment]
ok that's all I was wondering. I am doing just that, now. Thank you for the quick reply!

**Comment by seesharper** [comment]
No problem :)

**Comment by ronnieoverby** [comment]
I prefer the convenience over the minor performance improvement: https://gist.github.com/ronnieoverby/364e2af40eeb2cf5cca7
