### ISSUE TITLE
Specific Registrations for nested scopes

### ISSUE THREAD

**Issue by Tornhoof** [seesharper/LightInject#177]
Hi,
this question is similar to  Creating ChildContainers Issue #50 .

Is it possible to register specific types or instances in nested scopes?
Example:
Let's assume I have root scope, which has for logging purposes a certain context object with the IP Address, during startup etc. the IP 127.0.0.1 is used. Now for each Request I want to change that context object to a request specific one with the real request ip.
The specific code line is  `innerScope.RegisterInstance(typeof(IContext), new WebContext("192.168.0.1"));`

Example Code:
```csharp

    internal interface IContext
    {
        string IPAddress { get; }
    }

    internal class GeneralContext : IContext
    {
        public GeneralContext()
        {
            IPAddress = "127.0.0.1";
        }

        public string IPAddress { get; private set; }
    }

    internal class WebContext : IContext
    {
        public WebContext(string ip)
        {
            IPAddress = ip;
        }

        public string IPAddress { get; private set; }
    }

    internal class Program
    {
        private static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.RegisterInstance(typeof (IContext), new GeneralContext());
            using (var outerScope = container.BeginScope()) // app wide container (whole runtime)
            {
                var outerInstance = container.GetInstance<IContext>();
                Assert.AreEqual("127.0.0.1", outerInstance.IPAddress);
                using (var innerScope = container.BeginScope()) // e.g. per request scope started by owin
                {
                    // I'd like to do the line below
                    innerScope.RegisterInstance(typeof(IContext), new WebContext("192.168.0.1"));
                    var innerInstance = container.GetInstance<IContext>();
                    Assert.AreEqual("192.168.0.1", innerInstance.IPAddress);
                }
            }
        }
    }
```

**Comment by seesharper** [comment]
Are you building this on top of Web Api and Owin? In that case, before we dig any deeper, could you take a look at http://www.lightinject.net/#webapi? There is a section that explains how to get access to the current HttpRequestMessage outside the controller itself. Maybe that could be used as a starting point for what you are trying to achieve?

**Comment by Tornhoof** [comment]
Thank you very much. Your example would actually work in my example. A bit more complicated than expected though.
