### ISSUE TITLE
Manually begin/end scope (without touching ScopeManager[Provider])

### ISSUE THREAD

**Issue by justdmitry** [seesharper/LightInject#184]
I'm using LightInject.Mvc for NET 4.5 Razor application, but my website also need to run some background tasks, where no current HttpRequest is available.

My services are registered in Global.asa as follows:

    Container = new ServiceContainer();
    Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
    Container.RegisterControllers();
    Container.Register<SomeService>(new PerScopeLifetime());
    Container.EnableMvc();

And in background task I'm trying to start scope manually:

    using (MvcApplication.Container.BeginScope()) { ... }

And this code fails with `Object reference not set to an instance of an object` in `LightInject.Web.PerWebRequestScopeManagerProvider.GetScopeManager()`, because there is not HttpRequest which can store Scope for request.

Is there any option to manually "begin scope" without touching "current" ScopeManagerProvider?

I made a sample demo app to play with: https://github.com/justdmitry/LightInjectBackgroundTasks

**Comment by seesharper** [comment]
The default for LightInject.Mvc is to rely on LightInject.Web for handling the scopes. This basically means the in order to provide a scope we need a current HttpRequest. You could try setting the ScopeManager after the EnableMvc call.

**Comment by justdmitry** [comment]
If I assign `PerLogicalCallContextScopeManagerProvider` to `ScopeManagerProvider` after call `EnableMvc` - I'll receive exception `Attempt to create a scoped instance without a current scope` while rendering view (instantiating controller?)

If I completely remove `PerLogicalCallContextScopeManagerProvider` - nothing happens as I understand, because `EnableMvc` replaces it with `PerWebRequestScopeManagerProvider`... Ok, I can remove it. 

And my problem still alive - I need create scoped instances with and without HttpRequest. Are there any solutions better than having two ServiceContainers with equal instance registrations and different ScopeManagerProviders ?

**Comment by seesharper** [comment]
Assign the PerLogicalCallContextScopeManagerProvider  after the EnableMvc call.
Then you can do

```
using (container.BeginScope())
{
    container.GetInstance<IFoo>();
}
````

**Comment by justdmitry** [comment]
I receive exception `Attempt to create a scoped instance without a current scope` while rendering view (instantiating controller?) for Home/Index page.

Running on IIS Express, VS 2013 Upd 4, Win 8.1 Pro

**Comment by seesharper** [comment]
Okay, the preferred scoping for web application is to use LightInject.Web
that in turn relies on HttpRequest. If you need to deal with scopes during
startup, make sure you call the EnableMvc method as the last statement in
the Application_Start method

**Comment by justdmitry** [comment]
No, I need to deal with scopes during life of my application - some tasks are performed every X minutes.

**Comment by seesharper** [comment]
Can the service in question be registered with the PerContainerLifetime?

**Comment by justdmitry** [comment]
No, it's DbContext and services depending on it.

**Comment by seesharper** [comment]
So you want DbContext that is per web request and you also want a DbContext
that can be resolved as a transient without a scope? In that case you could
register the DbContext that you will be resolving outside the web request
as a transient (no lifetime) and handle disposal yourself

**Comment by seesharper** [comment]
The latter as a named DbContext service

**Comment by justdmitry** [comment]
I have several services, depending on DbContext (and each other). Almost all of them are used in controllers, and almost all are used in background tasks. They are not transient - they must live only while background task performing some job. And I have several tasks and they should not share DbContext and other services if running at the same time

As far as I see, I need some way to start/kill "custom" Scope in my background task. Something like Container.BeginScope, but without dealing with "default" ScopeManagerProvider...

**Comment by seesharper** [comment]
I see. 

What I meant was that you could do something like:

```
container.Register<DbContext>(f => CreateDbContext(), new PerScopeLifetimer()); 
container.Register<DbContext>(f => CreateDbContext(), "BackgroundTaskDbContext"); 
```

Then in the background task you can simply request the "unscoped" DbContext.

```
using (var context = container.GetInstance<DbContext>("BackgroundTaskDbContext"))
{

} -- context gets disposed here
```

If this does not work out for you I would suggest that you use two container instances.

**Comment by justdmitry** [comment]
But as soon as other services depends on DbContext - I need also create them manually with correct dbContext as parameter (or at least register second named instances for all of them)... No, I think second container is better solution :)

I hope future versions will have BeginScope() alternative to manually create Scope for working in 'mixed' scenarios.

**Comment by seesharper** [comment]
I think I got it working. The trick is to manually start and end the scope in the BeginRequest/EndRequest methods.  Let me know if this works out for you

```
    public class MvcApplication : System.Web.HttpApplication
    {
        internal static ServiceContainer Container;

        public Task bgTask;

        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            Container = new ServiceContainer();
           
            Container.RegisterControllers();
            Container.Register<SomeService>(new PerScopeLifetime());
            Container.EnableMvc();
            Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
            bgTask = Task.Run(() => BackgroundTask.DoSomething());
        }


        protected void Application_BeginRequest(Object sender, EventArgs e)
        {
            Container.BeginScope();
        }

        protected void Application_EndRequest(Object sender, EventArgs e)
        {
            Container.EndCurrentScope();
        }        
    }
```

**Comment by justdmitry** [comment]
It works until I make controller action async.

    public async Task<ActionResult> Index()
    {
        await Task.Run(() => Thread.Sleep(2000));
        ViewBag.Now = someService.GetNow();
        return View();
    }

After this, `Container.EndCurrentScope();` failures with `NullReferenceException` because `ScopeManagerProvider.GetScopeManager().CurrentScope` is null.

Pushed to sample repo.

**Comment by seesharper** [comment]
Try this

```
    public class MvcApplication : System.Web.HttpApplication
    {
        internal static ServiceContainer Container;

        public Task bgTask;

        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            Container = new ServiceContainer();
           
            Container.RegisterControllers();
            Container.Register<SomeService>(new PerScopeLifetime());
            Container.EnableMvc();
            Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
            bgTask = Task.Run(() => BackgroundTask.DoSomething());
        }


        protected void Application_BeginRequest(Object sender, EventArgs e)
        {
            var application = sender as HttpApplication;
            if (application == null)
            {
                return;
            }
            application.Context.Items["Scope"] = Container.BeginScope();
        }

        protected void Application_EndRequest(Object sender, EventArgs e)
        {
            var application = sender as HttpApplication;
            if (application == null)
            {
                return;
            }

            var scope = (Scope)application.Context.Items["Scope"];           
            scope.Dispose();
        }
        

    }
```

**Comment by justdmitry** [comment]
Yes, this works on demo project, but on real website sometimes (!?) fails when creating controllers with `Attempt to create a scoped instance without a current scope`. I can't peproduce this on demo project. I fallback to "two containers" scenario for real project and will continue to play with demo one.

**Comment by seesharper** [comment]
Let's try this

```
    public class MvcApplication : System.Web.HttpApplication
    {
        internal static ServiceContainer Container;

        public Task bgTask;

        protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);

            Container = new ServiceContainer();
           
            Container.RegisterControllers();
            Container.Register<SomeService>(new PerScopeLifetime());
            Container.EnableMvc();
            Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
            bgTask = Task.Run(() => BackgroundTask.DoSomething());
        }


        protected void Application_BeginRequest(Object sender, EventArgs e)
        {
            Container.BeginScope();
        }

        protected void Application_EndRequest(Object sender, EventArgs e)
        {
            if (Container.ScopeManagerProvider.GetScopeManager().CurrentScope != null)
            {
                Container.EndCurrentScope();
            }
        }
        
    }
```

**Comment by ilyazolotarov** [comment]
Unfortunately this solution will fail if ASP decides to swap threads during request, because logical call context would not flow in new thread in this case. You could combine 2 scope managers. If HttpContext.Current exists just use HttpContext to store current scope, if it doesn't - then use logical call context and start/dispose your scope manually. 

```csharp
public class AppScopeManager : ScopeManager
    {
        private const string HttpContextKey = "LightInject.Scope";
        private readonly LogicalThreadStorage<Scope> _logicalScope = new LogicalThreadStorage<Scope>();

        public AppScopeManager(IServiceFactory serviceFactory)
            : base(serviceFactory)
        {
        }
        public override Scope CurrentScope
        {
            get
            {
                return HttpContext.Current != null
                    ? GetThisScopeOrFirstValidAncestor(GetOrAddHttpContextScope())
                    : GetThisScopeOrFirstValidAncestor(_logicalScope.Value);
            }
            set
            {
                if (HttpContext.Current != null)
                    HttpContext.Current.Items[HttpContextKey] = value;
                else _logicalScope.Value = value;
            }
        }

        public static void EndHttpContextScope()
        {
            var scope = (Scope) HttpContext.Current.Items[HttpContextKey];
            if (scope == null) return;
            scope.Dispose();
            HttpContext.Current.Items[HttpContextKey] = null;
        }

        private Scope GetOrAddHttpContextScope()
        {
            var scope = (Scope) HttpContext.Current.Items[HttpContextKey];
            if (scope != null) return scope;
            scope = new Scope(this, null);
            CurrentScope = scope;
            return scope;
        }
    }
```
And HttpModule to dispose current scope when request ends: 
```csharp
public class ScopeManagerHttpModule : IHttpModule
    {
        public void Init(HttpApplication context)
        {
            context.EndRequest += (a, e) => AppScopeManager.EndHttpContextScope();
        }
        public void Dispose()
        {
        }
    }
```
