### ISSUE TITLE
Recursive dependency detected when initializing property in constructor

### ISSUE THREAD

**Issue by geirsagberg** [seesharper/LightInject#185]
I am getting an error when attempting to constructor inject a type that initializes a property manually, if the property type also depends on the first type.

Here is the code to reproduce the issue:

    public class ConstructorDependencyTests
    {
        [Fact]
        public void This_should_not_fail()
        {
            var container = new ServiceContainer();
            container.RegisterAssembly(Assembly.GetExecutingAssembly());

            Action action = () => container.GetInstance<Controller>();

            action.ShouldNotThrow();
        }
    }

    public class Controller
    {
        private readonly UserManager userManager;

        public Controller(UserManager userManager)
        {
            this.userManager = userManager;
        }
    }

    public class UserManager
    {
        public UserManager()
        {
            UserValidator = new UserValidator(this);
        }

        public UserValidator UserValidator { get; set; }
    }

    public class UserValidator
    {
        public UserValidator(UserManager userManager)
        {
            UserManager = userManager;
        }

        public UserManager UserManager { get; set; }
    }

I would expect LightInject to be able to create a `UserManager` without trying to resolve a `UserValidator`, but it fails with an InvalidOperationException: Recursive dependency detected.

**Comment by seesharper** [comment]
Make this setter private 

from 
public UserValidator UserValidator { get; set; }
to
public UserValidator UserValidator { get; private set; }

**Comment by geirsagberg** [comment]
That was quick!
So, it's the property injection that's the issue?

Unfortunately I am subclassing a class I do not own (UserManager in ASP.NET Identity), so I cannot set the setter visibility. 

Is there a way to disable property injection? Or, to de-register a single type, or somehow override it?

**Comment by seesharper** [comment]
Exactly.

You can disable property injection by implementing a custom IPropertyDependencySelector that returns zero property dependencies.

This implementation is then assigned to the PropertyDependencySelector property of the container.

**Comment by geirsagberg** [comment]
That did the trick, thanks!

**Comment by seesharper** [comment]
You're welcome :)

**Comment by geirsagberg** [comment]
Revisiting this issue, I have stumbled upon unexpected side effects of automatic property injection a few times the past year. Would you ever consider making property injection opt-in rather than opt-out?

Or, would you be open for a PR adding an easy way to disable property injection, something like this?

```csharp
    // in ServiceContainer:
    internal class PropertyInjectionDisabler : IPropertyDependencySelector
    {
        public IEnumerable<PropertyDependency> Execute(Type type)
        {
            return new PropertyDependency[0];
        }
    }
    public void DisablePropertyInjection() {
        this.PropertyDependencySelector = new PropertyInjectionDisabler();
    }
```

**Comment by seesharper** [comment]
I think we need to stay with opt-out with regards to backward compatibility. We could add a new property to the ContainerOptions class (EnableProperyInjection). It might make sense to keep the most obvious options in one place. What do you think?

**Comment by geirsagberg** [comment]
That sounds like a good compromise! I will send a PR tomorrow :)

**Comment by seesharper** [comment]
Nice. Thanks a lot
