### ISSUE TITLE
container.GetAllInstances methods resolve some strange instance starting from version 3.0.2.6

### ISSUE THREAD

**Issue by alex-konstantinov** [seesharper/LightInject#190]
We've tested it ok on version 3.0.2.0 and the test fails on 3.0.2.6.
The culprit is in the following change (see the diff screenshot): http://take.ms/Ld92C

Here is a test to reproduce fail with 3.0.2.6.

```
[TestFixture]
public class ProperlyResolvesInstancesFromContainer
{
	public interface ITestee<T> { }
	public class Testee {}
	public class TesteeImpl : ITestee<Testee> { }

	[Test]
	public void Registers_Interface_With_Concrete_Type_And_Resolves_Single_Instance_With_GetAllInstances()
	{
		ServiceContainer container = new ServiceContainer();
		
		//register by interface
		container.Register(typeof(ITestee<Testee>), typeof(TesteeImpl), typeof(TesteeImpl).FullName);
		//register by concrete
		container.Register(typeof(TesteeImpl));

		var resolved1 = container.GetAllInstances<ITestee<Testee>>();
		Assert.IsTrue(resolved1.Count() == 1);

		var resolved2 = container.GetAllInstances(typeof(ITestee<Testee>));
		Assert.IsTrue(resolved2.Count() == 1);

		var resolved3 = container.GetAllInstances<TesteeImpl>();
		Assert.IsTrue(resolved3.Count() == 1);

		var resolved4 = container.GetAllInstances(typeof(TesteeImpl));
		Assert.IsTrue(resolved4.Count() == 1);
	}
}
```

'resolved' collections contain two instances when using LightInject 3.0.2.6.
Whereas there should be one instance returned, as it is, when using LightInject 3.0.2.0.

**Comment by seesharper** [comment]
This is by design. The GetAllInstances method will return all services that is compatible with the requested service. The change was made to be able to support polymorphic dispatch of handlers in MediatR (https://github.com/jbogard/MediatR/wiki).

If this is a problem for you, I can show you how to set up an IEnumerable&lt;T&gt; that does not apply generic variance.

**Comment by stevenmiles** [comment]
What if the types weren't generic? Would it still return an instance from the concrete registration when asking for all services.

I have similar code, the purpose of which wasn't anything to do with generics, although some types happened to be generic. I was trying to ask for an instance by it's concrete type specifically but also be able to get all instances for their service type (interface). Explicit registration of concrete types separate from service registration was/is a requirement of LightInject. However there seems to be a special case for generics now where explicit concrete registrations result in multiple registrations being applied for getting all instances of a service type and so should be omitted. 

For this use case, this seems inconsistent.

**Comment by stevenmiles** [comment]
So as a result, a type that is registered as a concrete type is automatically available through any of it's interfaces without explicit registration of those interfaces?

**Comment by seesharper** [comment]
When using GetAllInstances, that is the default behavior.

**Comment by monnster** [comment]
@seesharper MediatR lets you setup the behavior of MultiInstanceFactory, so I think it would be better to make a specific method for this concrete situation.
GetAllInstances is used to resolve IEnumerable<IFoo> dependenices (internally by lightinject) and was very suitable to create factory constructors (FooFactory(IEnumerable<IFoo> handlers)) with no additional code. Now it's broken.

**Comment by seesharper** [comment]
Okay, I will be happy to help you out. I am not sure what you mean is broken. I would really appreciate if you could show me an example.

**Comment by monnster** [comment]
It seems that I misunderstood the issue a bit, but the problem is the same as in issue #172. Alex just does the same as RegisterAssembly() does - registers the same type by implementing interface and by concrete type.
The expected behavior of GetAllInstances() in this situation is to return all _distinct_ implementations of the requested type.

**Comment by alex-konstantinov** [comment]
>The expected behavior of GetAllInstances() in this situation is to return all distinct implementations of the requested type.

True. Whereas now we get two identical emitters (emit methods) on 3.0.2.6

**Comment by seesharper** [comment]
Would it be sufficient to provide a way to configure this behavior at the container level?

```
container.UseCovariance = false;
```

**Comment by alex-konstantinov** [comment]
I think yes. With the covariance disabled by default. From my point of view, as it was the behaviour before the new feature was introduced.

So if anybody wants the covariance explicitly - he will switch it on.

**Comment by seesharper** [comment]
Okay, I will look into it. As I know for a fact that many people actually relies on the new behavior (covariance), I might decide to make covariance the default. You guys that have run into this problem are already aware of this and hence in a better spot to make the necessary modifications. I am afraid that changing the default back will cause even more breaking changes out there. Anyway, I will add the configuration option and push a new version.

**Comment by monnster** [comment]
Anyway please don't forget to update the excellent docs at http://lightinject.net

**Comment by seesharper** [comment]
LightInject 3.0.2.7 has been published to the official NuGet feed

This behavior can be overridden using the **EnableVariance** container option.

	var container = new ServiceContainer(new ContainerOptions { EnableVariance = false });
	container.Register<Foo>();
	container.Register<DerivedFoo>();
	var instances = container.GetAllInstances<Foo>();
	Assert.AreEqual(1, instances.Count());
