### ISSUE TITLE
Lightinject resolves relative paths "wrong" when using private path probing

### ISSUE THREAD

**Issue by rubenwe** [seesharper/LightInject#192]
Hi, 
I observed an (from my point of view) undesired behaviour using the LightInject.dll from a subfolder.
LightInject.dll is correctly found by the CLR in the specified subfolder (in my case `./libs`), because I enabled private path probing in my app.config.

When I scan for all component DLLs that LightInject should load like this:
```csharp
container.RegisterAssembly(@"components\*.dll");
```
it will scan in `./libs/components/` instead of `./components/`.
I guess LightInject resolves those paths based on it's assembly location.

I have not checked the code, but this could be problematic if the DLL was GACed or shadowcopied.
Just wanted to let you know. In my case I can work around that limitation.

Thanks again for an awesome framework!

**Comment by seesharper** [comment]
The path is resolved relative to Assembly.Codebase, so shadow copying should not be a problem.
