### ISSUE TITLE
Log on debugging

### ISSUE THREAD

**Issue by Rajivhost** [seesharper/LightInject#193]
Hi,
Apparently, LightInject does not use an internal log mechanism to know what goes wrong for example on debugging.

**Comment by seesharper** [comment]
That, is correct. The idea is that the exception message should provide you with enough information to be able to figure out what is wrong. Is it something in particular that your are having problems with?

**Comment by Rajivhost** [comment]
I figured out my issue. It was an internal error which was not thrown because I disabled the exceptions on debugging.

**Comment by seesharper** [comment]
Good, closing the issue then :)
