### ISSUE TITLE
NRE in upload handler

### ISSUE THREAD

**Issue by impworks** [seesharper/LightInject#195]
I added LightInject to my ASP.NET project and started getting the following error in my upload handler, which doesn't even reference LightInject:

```
[NullReferenceException]: Object reference not set to an instance of an object.
   at LightInject.Web.LightInjectHttpModule.EndRequest() in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject.Web\LightInject.Web.cs:line 110
   at LightInject.Web.LightInjectHttpModule.<Init>b__1(Object s, EventArgs a) in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject.Web\LightInject.Web.cs:line 97
   at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute()
   at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)
```

What could be causing it?

**Comment by impworks** [comment]
Update: the error is somehow related to uploaded file size. It never occurs on small files (under 20 kb). However, 100kb and larger files always fail.

**Comment by impworks** [comment]
Update 2: apparently, the issue was originally caused by an incorrect value of the `maxAllowedContentLength` attribute in `web.config`. However, I'm still interested in how LightInject was affected by it.

**Comment by seesharper** [comment]
Should be covered by existing checks for null in the EndRequest method

**Comment by phosgen-tepes** [comment]
Hello,

I receive similar exception with the latest LightInject version

**Comment by phosgen-tepes** [comment]
Hello,

I receive similar exception with the latest LightInject version:

System.NullReferenceException: Object reference not set to an instance of an object. at LightInject.Web.LightInjectHttpModule.EndRequest() at LightInject.Web.LightInjectHttpModule.b__1(Object s, EventArgs a) at System.Web.HttpApplication.SyncEventExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() at System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously)

Interesting that PerWebRequestScope is enabled by container.EnablePerWebRequestScope(), but I don't use this lifetime, everything is set as PerContainerLifetime.

Could you help me?

**Comment by abhandare** [comment]
I'm also getting this exception but maxAllowedContentLength is not helpfull to resolve this issue.

**Comment by seesharper** [comment]
Any async/await going on here?

**Comment by abhandare** [comment]
No..

**Comment by seesharper** [comment]
Would you be able to create a simple repro of this?

**Comment by abhandare** [comment]
no....Coz I'm new to Git.
Sipmly I'm using Lightinject into a Aspnet MVC application.

**Comment by seesharper** [comment]
It is rather difficult to make any assumptions about why it fails without looking at the code. Is it a large project or could you just zip it up so we can have a look?

**Comment by hitesh29889** [comment]
I am getting the same error, maxallowedcontent length is not helpful.
I just created urlrewrite rule in iis to redirect my site to https, and this comes up. Stressfull
