### ISSUE TITLE
Xamarin support?

### ISSUE THREAD

**Issue by omares** [seesharper/LightInject#197]
Hey,

is there a version of lightinject that supports xamarin? Right now when i try to add the nuget package to our pcl solution i get following error: 

    Adding LightInject...
    Adding 'LightInject 3.0.2.7' to RebuyApp.
    Could not install package 'LightInject 3.0.2.7'. You are trying to install this package into a project that targets 'portable-net45+win+wp80+MonoTouch10+MonoAndroid10+xamarinmac20+xamarinios10', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

**Comment by seesharper** [comment]
Looking into this right now. The build system needs some TLC to get this working. Actually you can test this out right now by pulling out the windows phone dll from the NuGet package. That dll is 259

**Comment by omares** [comment]
Hey thats cool, do you have any ETA on the release?

Regarding the testing: unfortunately i am very short on time and compiling the sourcecode on mac using mono, pulling out the dll out of the nuget etc etc is currently just not within my timeframe.

**Comment by seesharper** [comment]
There is no particular timeframe on this. BTW, you do not have to recompile on Mono. You just have to  use the dll in the wp8 folder from the nuget package.

**Comment by seesharper** [comment]
LightInject > 4.0.0 now supports PCL profile 111

**Comment by smozhaykin** [comment]
@seesharper, I'm experiencing the same issue with LightInject 4.0.6:

Could not install package 'LightInject 4.0.6'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile111', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

Initially target framework profile was 78 and I've got the same message:

Could not install package 'LightInject 4.0.6'. You are trying to install this package into a project that targets '.NETPortable,Version=v4.5,Profile=Profile78', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author.

I've found this issue and tried to change profile to 111, but the error is still present...

**Comment by taori** [comment]
@seesharper Could you have another look at this please? I can't install it to xamarin pcl projects anymore (I tried profile 259+78). I compared your commit https://github.com/seesharper/LightInject/commit/8ddb35723d460c0007ac63d7fe249874fbccb960 with Newtonsoft.Json which uses targetFramework "portable45-net45+win8+wp8+wpa81". That package installs just fine.

I've also had a look at http://embed.plnkr.co/03ck2dCtnJogBKHJ9EjY 

To me it looks like that page indicates false nuget framework targets. I also found this as targetFramework reference: https://docs.nuget.org/create/enforced-package-conventions "Common Framework and Profile Targeting Examples"

**Comment by seesharper** [comment]
The LightInject PCL profile is 111. Have you tried that?

**Comment by seesharper** [comment]
On a sidenote I have not tested this in Xamarin for a while since I got tired of begging them for an open source license that got expired all the time. Hopefully this will now change as Microsoft has acquired Xamarin.

**Comment by taori** [comment]
@seesharper this profile system could really use an overhaul... i've got the same accepted platforms like before but a different profile version and now it's working just fine. ugh. Problem resolved however. Thanks!

OT: Yeah, i am sure there will be major changes to how xamarin licensing works. It only makes sense to promote xamarin development to make people ship windows mobile applications too as a side product. I wish you the best of luck with it - they would certainly benefit from it. 

Personally i really enjoy your DI framework. Not bloated and easy to extend and plenty enough features to work with.
