### ISSUE TITLE
System.ArgumentNullException with a Proxy Type as a Constructor Dependency

### ISSUE THREAD

**Issue by daniel-githubuser** [seesharper/LightInject#201]
Good morning,

We are having an error when trying to resolve a class that has as dependency a Proxy Type.
When the same type is registered as a normal Type (without proxy), it is resolved successfully.
Below a sample code and the stack trace.

Sample:

using System;
using LightInject;
using Microsoft.VisualStudio.TestTools.UnitTesting;

namespace LightInjectError
{

    public class A
    {
        private B b;

        public A(B b)
        {
            this.b = b;
        }
    }

    public class B
    {
    }

    public class interB : LightInject.Interception.IInterceptor
    {
        public object Invoke(LightInject.Interception.IInvocationInfo invocationInfo)
        {
            return invocationInfo.Proceed();
        }
    }

    [TestClass]
    public class InjectProxy
    {
        [TestMethod]
        public void InjectProxyTest()
        {
            try
            {
                ServiceContainer sc = new ServiceContainer();
                sc.Register<A>(new PerContainerLifetime());
                sc.Register<B>(new PerContainerLifetime());
                sc.Intercept(sr => sr.ServiceType == typeof(B), sf => new interB());

                B b = sc.GetInstance<B>();
                A a = sc.GetInstance<A>();
            }
            catch(Exception e)
            {
                throw e;
            }
        }
    }
}

StackTrace

System.ArgumentNullException was caught
  HResult=-2147467261
  Message=Valor não pode ser nulo.
Nome do parâmetro: con
  Source=mscorlib
  ParamName=con
  StackTrace:
       em System.Reflection.Emit.ModuleBuilder.GetFieldTokenNoLock(FieldInfo field)
       em System.Reflection.Emit.ModuleBuilder.GetFieldToken(FieldInfo field)
       em System.Reflection.Emit.ILGenerator.Emit(OpCode opcode, FieldInfo field)
       em LightInject.Interception.ProxyBuilder.PushProxyInstanceIfReturnValueEqualsTargetInstance(ILGenerator il, Type returnType) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 1514
       em LightInject.Interception.ProxyBuilder.PushReturnValue(ILGenerator il, Type returnType) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 1498
       em LightInject.Interception.ProxyBuilder.ImplementInterceptedMethod(MethodInfo targetMethod, Int32[] interceptorIndicies) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 1713
       em LightInject.Interception.ProxyBuilder.ImplementMethod(MethodInfo targetMethod) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 1682
       em LightInject.Interception.ProxyBuilder.ImplementMethods() na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 1672
       em LightInject.Interception.ProxyBuilder.GetProxyType(ProxyDefinition definition) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 1233
       em LightInject.InterceptionContainerExtensions.CreateProxyType(Type serviceType, Type[] additionalInterfaces, IServiceFactory serviceFactory, Action`2 defineProxyType, ServiceRegistration registration) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 136
       em LightInject.InterceptionContainerExtensions.CreateProxyServiceRegistration(ServiceRegistration registration, Type[] additionalInterfaces, IServiceFactory serviceFactory, Action`2 defineProxyType) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 171
       em LightInject.InterceptionContainerExtensions.<>c__DisplayClass3.<Intercept>b__2(IServiceFactory serviceFactory, ServiceRegistration registration) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject.Interception\LightInject.Interception.cs:linha 66
       em LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3114
       em LightInject.ServiceContainer.<>c__DisplayClass9e.<ResolveEmitMethod>b__9a(IEmitter methodSkeleton) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3739
       em LightInject.ServiceContainer.<>c__DisplayClass39.<CreateEmitMethodWrapper>b__38(IEmitter ms) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3059
       em LightInject.ServiceContainer.EmitConstructorDependency(IEmitter emitter, Dependency dependency) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3339
       em LightInject.ServiceContainer.EmitConstructorDependencies(ConstructionInfo constructionInfo, IEmitter emitter, Action`1 decoratorTargetEmitter) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3302
       em LightInject.ServiceContainer.EmitNewInstanceUsingImplementingType(IEmitter emitter, ConstructionInfo constructionInfo, Action`1 decoratorTargetEmitMethod) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3274
       em LightInject.ServiceContainer.EmitNewInstance(ServiceRegistration serviceRegistration, IEmitter emitter) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3228
       em LightInject.ServiceContainer.EmitNewInstanceWithDecorators(ServiceRegistration serviceRegistration, IEmitter emitter) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3124
       em LightInject.ServiceContainer.<>c__DisplayClass9e.<ResolveEmitMethod>b__9a(IEmitter methodSkeleton) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3739
       em LightInject.ServiceContainer.<>c__DisplayClass39.<CreateEmitMethodWrapper>b__38(IEmitter ms) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3059
       em LightInject.ServiceContainer.CreateDynamicMethodDelegate(Action`1 serviceEmitter) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 2980
       em LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3824
       em LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 3787
       em LightInject.ServiceContainer.GetInstance(Type serviceType) na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 2486
       em LightInject.ServiceContainer.GetInstance[TService]() na c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:linha 2539

**Comment by cephius473** [comment]
Got any news on this? Also happening to me intermittently
