### ISSUE TITLE
IDisposable implementation is broken

### ISSUE THREAD

**Issue by dotnetchris** [seesharper/LightInject#203]
Container.Dispose needs to dispose the entire container. Instead it calls dispose on some (all?) of the registered services.

Either IDispoable needs implemented properly or the interface needs to be removed and this method should be renamed to make it clear that it is ```ICallDisposeOnYourRegistrationsOnlyInTheseCircumstances______()```

**Comment by hheg** [comment]
As far as I've understood with LightInject that's taken care of by the scope management. So look for Scope.Dispose()

**Comment by seesharper** [comment]
Services registered with the PerScopeLifetime or PerRequestLifetime gets disposed when the scope ends and services registered with the PerContainerLifetime gets disposed along with the container.

```
container.Register<DisposableFoo>(new PerScopeLifetime());
container.Register<DisposableBar>(new PerContainerLifetime());

using (container.BeginScope())
{
    container.GetInstance<DisposableFoo>();
}  //DisposableFoo disposed here.

container.Dispose()  // DisposableBar disposed here
````
