### ISSUE TITLE
Massive performance issue and memory leak with GetInstance(Type serviceType, string serviceName)

### ISSUE THREAD

**Issue by stevenmiles** [seesharper/LightInject#206]
Tested with 3.0.2.7

The new hashtable implementation introduced in #191 seems to force a default object style GetHasCode() in Search by using RuntimeHelpers.GetHashCode(key). This will bypass any implementation of GetHashCode on the key. This essentially searches for instances of keys, not properties of the keys. This is an issue when the hashtable is used with Tuples.

This works OK with Type objects as .NET returns the same instance of a Type object, one for each Type.

GetInstance(Type serviceType, string serviceName) creates a new Tuple instance each time to search with, obviously this instance isn't in the cache, and so never finds the delegate in the cache.

So every time GetInstance(Type serviceType, string serviceName) is called, it compiles a new delegate, and then caches it. This is slow,  and constantly adds to the cache, leaking memory.

**Comment by nothingmn** [comment]
I can confirm that there is an issue with this tool leaking memory like a sieve.


![capture](https://cloud.githubusercontent.com/assets/423958/8988785/28d54430-369d-11e5-8651-91da3f3391c1.PNG)

**Comment by seesharper** [comment]
Fixed in LightInject 4.0.o
