### ISSUE TITLE
LightInject assemblies are not signed

### ISSUE THREAD

**Issue by YuriyIvon** [seesharper/LightInject#207]
I am developing a project where I must sign my assemblies, but I can't because of LightInject:
```
Assembly generation failed -- Referenced assembly 'LightInject' does not have a strong name
Assembly generation failed -- Referenced assembly 'LightInject.WebApi' does not have a strong name
```

**Comment by seesharper** [comment]
Hi!

There is currently no plans for strong naming LightInject. 

There is however a solution to the problem. The following link explains how to sign an assembly for which you don't have the source code.

http://www.geekzilla.co.uk/ViewCE64BEF3-51A6-4F1C-90C9-6A76B015C9FB.htm

Best regards
Bernhard Richter

**Comment by YuriyIvon** [comment]
Thanks for the information

**Comment by pkoelbl** [comment]
I recommend this nuget package that auto signs things for you,
https://github.com/dsplaisted/strongnamer
