### ISSUE TITLE
Asynchronous factories

### ISSUE THREAD

**Issue by Firys** [seesharper/LightInject#213]
I've got a factory that asynchronously fetches authentication header from remote target and the result from async operation is used every time remote request is invoked. It looks more or less like this:
```csharp
interface ICookie { }

class Cookie : ICookie { }

interface ICookieFactory
{
	Task<ICookie> Create();
}

class CookieFactory : ICookieFactory
{
	public async Task<ICookie> Create()
	{
		// http request
		await Task.Delay(10);
		return new Cookie();
	}
}
```

Now, I'd like to use the token in my method by doing this:
```csharp
static async Task AsyncMethod()
{
	var Container = new ServiceContainer();
	Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
	Container.Register<ICookieFactory, CookieFactory>(new PerContainerLifetime());
	Container.Register<ICookie>(async (factory) => await factory.GetInstance<ICookieFactory>().Create(), new PerScopeLifetime());
	
	using(Container.BeginScope())
	{
		var cookie = Container.GetInstance<ICookie>();
	}
}
```
To accomplish that, I've written the following extension:
```csharp
public static class AsyncFactory 
{
    class SynchronizedFactory<TService>
    {
        Func<IServiceFactory, Task<TService>> _asyncFactory;
        public SynchronizedFactory(Func<IServiceFactory, Task<TService>> asyncFactory)
        {
            _asyncFactory = asyncFactory;
        }
        public TService Create(IServiceFactory serviceFactory)
        {
            var task = _asyncFactory(serviceFactory);
            task.Wait();
            return task.Result;
        }
    }

    public static void Register<TService>(this ServiceContainer container, Func<IServiceFactory, Task<TService>> factory, ILifetime lifetime)
    {
        var synchronizedFactory = new SynchronizedFactory<TService>(factory);
        container.Register<TService>((serviceFactory) => synchronizedFactory.Create(serviceFactory), lifetime);
    }
}
```

However, as you can see, my method is asynchronous and it could use syntax like this:
```csharp
var cookie = await Container.GetInstanceAsync<ICookie>();
```
Is doing this possible?

**Comment by seesharper** [comment]
Try this out 
```
public static async Task<T> GetInstanceAsync<T>(this IServiceContainer container)
{
    Task<T> task = Task.Run(() => container.GetInstance<T>());
    return await task;
} 
```

**Comment by Firys** [comment]
It would work syntactically, but doing `.Wait()` in my SynchronizedFactory makes async here pointless - it actually adds a cost of executing this task while still blocking one threads and makes my code less scalable. I did some tests:
```csharp
static async Task Invoke(Func<int, Task> action, int count)
{
    List<Task> tasks = new List<Task>();
    for (var index = 0; index < count; index++)
    {
        tasks.Add(action(index));
    }
    await Task.WhenAll(tasks);
}
static async Task AsyncMethod()
{
    var Container = new ServiceContainer();
    Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
    Container.Register<ICookieFactory, CookieFactory>(new PerContainerLifetime());
    Container.Register<ICookie>(async (factory) => await factory.GetInstance<ICookieFactory>().Create(), new PerScopeLifetime());
    await Invoke(async (index)=>{
        using(Container.BeginScope())
        {
                
            Console.WriteLine("Waiting for {0}", index);
            var cookie = await Container.GetInstanceAsync<ICookie>();
            Console.WriteLine("Constructed {0}", index);
        }
    },50);
}
```
Creating 50 requests like this takes really long time, but replacing
`var cookie = await Container.GetInstanceAsync<ICookie>();` with `var cookie = await Container.GetInstance<ICookieFactory>().Create();` works, but then you are unable to use ICookie anywhere.

I'd like to traverse the construction graph, find instances that return tasks, execute all asynchronous work, add all asynchronously-created elements to the scope and then construct an element synchronically. Is that possible?

**Comment by seesharper** [comment]
If you need to to inject an ICookie instance would it be an option to inject a Task<ICookie> instead and have the consuming service await the ICookie instance?

**Comment by Firys** [comment]
Imagine something like this:
```csharp
// actually the chain is more complicated, but I've simplified it to show an example.
class MyAuthorizationHeader : IHeaders { public MyAuthorizationHeader(ICookie cookie); }
class MyHttpClient : ITransport { public MyHttpClient(IHeaders headers); }
class MyApiClient : IApiClient { public MyApiClient(ITransport httpClient); }
interface IUser { string upn { get; } }
// use asynchronous factory for this
class ApiUser : IUser {
    public CurrentUser(IApiClient apiClient);
    public async Task ConstructAsync();
    public string upn { get; private set; }
}
// use synchronous factory for this
class IdUser : IUser { 
    public LocalUser(IIdentity identity);
    public string upn { get; private set; }
}
class MyController { public MyController (CurrentUser user); }
```
The problem is that almost every class in this chain, except MyApiClient and MyHttpClient is fully synchronous and it wouldn't really make sense to convert them into async, because they don't do any asynchronous work. Additionally, MyController expects CurrentUser with some data inside, but doesn't care how it's constructed - converting it into async would require a huge refactor so it's not really doable.

Actually, asynchronous resolving could be quite useful - especially useful in scenarious like loading configurations from databases, fetching data from remote servers, doing remote authentication and so on. Something like this:
```csharp
public async Task<IOutput> Create(IServiceFactory serviceFactory) {
    var i = await Container.GetInstanceAsync<IInput>();
    //some additional logic that actually creates IOutput
}
```

**Comment by seesharper** [comment]
This is quite an interesting topic with regards to asynchronous construction of service instances. LightInject creates a dynamic method using Reflection.Emit that constructs the object graph. This is a fully synchronous method and it would involve an extreme effort to make this method asynchronous as it would require LightInject to mimic all the compiler tricks that is done to handle synchronisation, continuation and cancelation tokens. If you look at the IL for a async method you will understand how complex this really is.  Another thing is when mixing  asynchronous and synchronous code there has to be a wait somewhere to go from asynchronous to synchronous and a Task.Run to go from synchronous to asynchronous. That being said I would really appreciate any input that might solve this problem.

Stephen Cleary sheds some light on this problem in this blog post. 

http://blog.stephencleary.com/2013/01/async-oop-2-constructors.html

**Comment by Firys** [comment]
Basic use case (without cancellation tokens) is not too difficult:
```csharp
struct WrappedFactory<TResult> : IAsyncStateMachine
{
	// 0+ in progress
	// -1 - failed
	// -2 - completed
	// -3 - cancelled
	public int state;
	public AsyncTaskMethodBuilder<TResult> builder;
        // we will need result from this, add such field for every async variable instantiated
	private TaskAwaiter<TResult> _resultAwaiter;
        // value factory for the result
	private Func<Task<TResult>> _factory;
	private WrappedFactory(Func<Task<TResult>> factory)
	{
		state = 0;
		builder = AsyncTaskMethodBuilder<TResult>.Create();
		_factory = factory;
	}
	void IAsyncStateMachine.MoveNext()
	{
		try
		{
			switch (state)
			{
				case 0:
					state = 1;
					// just an example for waterfall of actions, could be final awaiter
					var aw = Task.Delay(500).GetAwaiter();
					builder.AwaitUnsafeOnCompleted<TaskAwaiter, WrappedFactory<TResult>>(ref aw, ref this);
					return;
				case 1:
					state = 2;
					var aw2 = _resultAwaiter = _factory().GetAwaiter();
					builder.AwaitUnsafeOnCompleted<TaskAwaiter<TResult>, WrappedFactory<TResult>>(ref aw2, ref this);
					return;
				case 2:
					TResult result = _resultAwaiter.GetResult();
					this.state = -2;
					// instantiate everything else here, we have all async things prepared
					this.builder.SetResult(result);
					break;
			}
		}
		catch (Exception exception)
		{
			this.state = -1;
			this.builder.SetException(exception);
			return;
		}
	}

	void IAsyncStateMachine.SetStateMachine(IAsyncStateMachine stateMachine)
	{
		this.builder.SetStateMachine(stateMachine);
	}

	public static Task<TResult> BuildAndStartTask(Func<Task<TResult>> factory)
	{
		var task = new WrappedFactory<TResult>(factory);
		task.builder.Start<WrappedFactory<TResult>>(ref task);
		return (Task<TResult>)task.builder.Task;
	}
}
```
Usage is: `await WrappedFactory<IValue>.BuildAndStartTask(async () => await somethingAsync());`

IL code has a lot of boilerplate, but the true logic is invoked here: `_resultAwaiter = _factory().GetAwaiter();` (a single callvirt - nothing too fancy).
Async construction would make such "WrappedFactory" for each constructor, but for non-synchronic factories it'd just invoke Task.FromResult. I'm pretty sure it wouldn't work with current ILifetime and it'd require something IAsyncLifetime that'd use GetInstanceAsync and contain a list of tasks on top of plain list of objects.

**Comment by seesharper** [comment]
I have to take some time to wrap my head around this. It's been a while since I dived deep into the details of async and await :) Did you come up with this class based on a compiler generated statemachine?

**Comment by Firys** [comment]
Yeah, this is using the same idea as compiler-generated statemachines, just rewritten a little bit. 

Basic idea is that AwaitUnsafeOnCompleted ensures that whenever awaiter gets completed/failed, MoveNext is invoked. The implementation above is not entirely correct - I forgot to store Task.Delay(500).GetAwaiter(); in one of fields and GetResult() in the next step to ensure that all exceptions are getting rethrown to a correct place before the next step is invoked.

**Comment by seesharper** [comment]
You obviously know your async/await :) Is the WrapperFactory something that needs to be emitted at runtime or does it represent something generic that the emitted code can call into. Still trying to understand this:) 

Playing with the "new" API just to make sure that I have understood what you are trying to do.

```c#
public class Foo 
{
	public Foo(Bar bar)
	{
	}
}

public class Bar
{
}
```

In this example I assume that the Bar dependency is a service to be resolved asynchronously.

```c#
container.Register<Foo>();
container.RegisterAsync<Bar>();
```
The Foo service can be resolved as usual like this

```c#
container.GetInstance<Foo>();
```

When the Bar service is to be injected, LightInject will see that it has been registered using the RegisterAsync method and hence resolve the Bar instance asynchronously.

Does this make sense to you ?

If you think you know how to implement this in LightInject I will happily accept a pull request :)

**Comment by Firys** [comment]
Not entirely - instantiation method would need to contain some kind of logic that'd return Task and constructor can't do that OOTB, so the service can't really be resolved asynchronically unless it had some kind of initialization logic:
```csharp
interface IAsyncInstantiable {
    Task Initialize();
}
class Bar : IAsyncInstantiable {
    public async Task Initialize() {
         await Task.Delay(10);
    }
}
```
but for me the following would make more sense:
```csharp
interface IAsynchronousFactory {
    Task<object> Create(IServiceFactory serviceFactory);
}
interface IAsynchronousFactory<T> {
    Task<T> Create(IServiceFactory serviceFactory);
}
```
The problem with async tasks is quite an overhead (task must instantiate structure, delegate and `Task` object). Additionally, `GetInstance<Foo>();` would need to get synchronized somewhere - it'd be better to either tell the programmer that either he needs to register synchronous version of the factory if he wants to use regular `GetInstance<Foo>()` or tell the container how to synchronize async calls.

Asynchronous version `GetInstanceAsync<Foo>()` would look for an async version of the factory and if it doesn't exist, just build a simple, completed Task.FromResult() from synchronous code and if it does, it should just use the async delegates.

I might try fully grasping LightInject's architecture before I proceed into the world of unknown, though. :)

BTW, Tasks are simple: https://channel9.msdn.com/Series/Three-Essential-Tips-for-Async

**Comment by Firys** [comment]
After a bit of dwelling I've changed the idea to make it more compatible with LightInject, I have changed the idea into requesting `Task<T>`. That way it's possible to do this:
```csharp
interface IFoo { }
class SomeFactory
{
    Task<IFoo> Create(IServiceFactory serviceFactory)
    {
          create task here
    }
}
class SomeConsumer
{
    public SomeConsumer(Task<IFoo> asTask) ...
}

class SomeConsumerThatRequiresAsync
{
    public SomeConsumer(IFoo asSync) ...
}

container.Register((factory)=>SomeFactory.Create(factory));
// should work as usual
container.GetInstance<SomeConsumer>();
// should throw an exception of IFoo not being resolved
container.GetInstance<SomeConsumerThatRequiresAsync>();
// should return non-started
// (or started/completed if the task is using custom lifetime)
// task that can be used to await for creation of object
container.GetInstance<Task<SomeConsumerThatRequiresAsync>>();
// should use the above construct to get task and await it
container.GetInstanceAsync<SomeConsumerThatRequiresAsync>();
// should return the same task that's used in synchronic version of this method
container.GetInstanceAsync<Task<SomeConsumerThatRequiresAsync>>();
// should be able to get you func with task-creating method, more sane idea than non-started task
container.GetInstanceAsync<Func<Task<SomeConsumerThatRequiresAsync>>>();
```
I'll keep playing around with this concept a little bit to see what can it evolve into.

**Comment by seesharper** [comment]
The easiest way to add support for Task&lt;T&gt; would be to do something similar to the way LightInject handles Lazy&lt;T&gt; .
LightInject will automatically create a Lazy&lt;T&gt; for you.

```
container.Register<IFoo,Foo>();
var lazyFoo = container.GetInstance<Lazy<IFoo>>();
```

Maybe we can do the same for Task?

**Comment by Firys** [comment]
This construct would make sense except in Lazy we just emit something that will be resolved later and in Task we register a piece of asynchronous work before it's being requested. There wouldn't be a need to wrap Foo into Lazy<Foo> but to unwrap Lazy<Foo> when Foo is a constructor dependency, so this case would need to work (with Lazy it doesn't really make sense):
```csharp
container.Register<Lazy<Foo>>();
container.Register<IFoo>((f) => f.GetInstance<Foo>());
```
This would need some modifications in EmitConstructorDependencies and EmitPropertyDependencies, because it'd have to create non-task dependencies after all tasks are completed. All tasks should be state machines containing the following emitted code:
1. Start constructor dependencies (and store them in the internal array)
2. Use Task.WhenAll() to get awaiter from it (it's nice because it properly handles aggregated exceptions - it adds a bit of its own overhead, but i'm not sure if it can be adjusted to this case)
3. Use constructor dependencies and resolve all non-task ones, set proper result.
4. Do 3 above for each property dependency.

**Comment by Firys** [comment]
Well, I've re-read my comment and it's possible to do this by wrapping everything into tasks (either completed or executable), but it's wouldn't be the most optimal solution in this case.
