### ISSUE TITLE
Sign the assembly. A strongly-named assembly is required.

### ISSUE THREAD

**Issue by fernandostark** [seesharper/LightInject#216]
Hi, seesharper.

I'm a big fan of LightInject. I'd like to suggest signing the assembly with a strong name key file.

I got the following exception:
System.IO.FileLoadException: System.IO.FileLoadException: Could not load file or assembly 'LightInject, Version=4.0.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. A strongly-named assembly is required. (Exception from HRESULT: 0x80131044).

This framework is awesome. I hope you could help me.

Thanks.

**Comment by seesharper** [comment]
Take a look at issue #207 :)

**Comment by fernandostark** [comment]
Thanks!

Enviado pelo meu Windows Phone
________________________________
De: Bernhard Richter<mailto:notifications@github.com>
Enviada em: ‎02/‎10/‎2015 05:20
Para: seesharper/LightInject<mailto:LightInject@noreply.github.com>
Cc: fernandostark<mailto:fernando.stark@outlook.com>
Assunto: Re: [LightInject] Sign the assembly. A strongly-named assembly is required. (#216)

Take a look at issue #207 :)

---
