### ISSUE TITLE
Resolving multiple unnamed services

### ISSUE THREAD

**Issue by dezfowler** [seesharper/LightInject#217]
Encountered an unexpected behaviour when registering and resolving unnamed services.

The simplest example is the following (a variation of an example on the LightInject web site) which I expected to return both instances:

```csharp
container.Register<IThing, ThingA>();
container.Register<IThing, ThingB>();
var allInstances = container.GetAllInstances<IThing>().ToList();
Assert.That(allInstances, Has.Count.EqualTo(2)); // ==> FAIL!
```

This fails - it only returns one instance. So either the first registration was overwritten or the second registration was silently ignored so I tried this test...

```csharp
Assert.That(allInstances[0], Is.InstanceOf<ThingA>()); // ==> FAIL!
```

This fails too, it returns ThingB, not ThingA so it appears the registration is being overwritten.

This silent overwrite is unexpected, particularly given the container has a dedicated `Override()` method. I would instead expect both to be successfully registered and returned and would expect a call to `GetInstance<IThing>()` to fail with a "multiple registrations" exception.

Could you confirm whether this is a bug or not and, if not, could the `IEnumerable<T>` section of the documentation be updated to clarify what the expected behaviour is?

Cheers!

**Comment by seesharper** [comment]
LightInject does not support multiple unnamed registrations. The only way
you can register multiple implementations for a given service type, is to
give each implementation an unique name.

I do however recognize that the documentation could be more explicit
regarding this behavior.

Best regards
Bernhard Richter

**Comment by dezfowler** [comment]
Thanks for the swift response.

That does sound odd though - especially given the covariance behaviour illustrated by this other example from the LightInject site:

```csharp
container.Register<Foo>();
container.Register<DerivedFoo>();
var instances = container.GetAllInstances<Foo>();
Assert.AreEqual(2, instances.Count());
```

This also works if Foo inherits from IFoo and you do:

```csharp
var instances = container.GetAllInstances<IFoo>();
Assert.AreEqual(2, instances.Count());
```

It looks similar but the result is very different.

**Comment by seesharper** [comment]
In the covariance example, we register two different services, Foo and DerivedFoo. Since they are both concrete classes their service type and implementing type are the same. So its not the same as registering two types that share the same service type. 

By default, LightInject uses covariance when resolving multiple instance meaning that it will yield services that are assignable to the requested service type, Foo and IFoo in your example. 

Best regards 
Bernhard Richter
