### ISSUE TITLE
InvalidOperationException in ScopeManager

### ISSUE THREAD

**Issue by l0nley** [seesharper/LightInject#219]
Hi!
I am trying to use LightInject in my SPA/WebApi application. Sometimes i have error when my project 
running under visual studio debug:
InvalidOperationException
Attempt to end a scope before all child scopes are completed.
   at LightInject.ScopeManager.EndScope(Scope scope) in c:\Github\LightInject\src\LightInject\NuGet\tmp\Net45\Binary\LightInject\LightInject.cs:line 6339

Synopsis: just doing nothing about 1-2 minutes. Then trying to make request to webapi, and it hangs.
after 10-15 secs, i have such exception in light inject.
I have a about 10 services, registered with PerContainerLifetime.
Could you point me, what can cause error?

**Comment by seesharper** [comment]
Before I can help I need to know if this a selfhosted Web Api (aka console application) or an application hosted in IIS. Is it for instance based on Owin?

**Comment by l0nley** [comment]
I use IIS Express. No, it is not an Owin application.

**Comment by seesharper** [comment]
You can use LightInject.Web to ensure that you services are scoped per Web request. Even though your services are PerContainer, the controllers are per scope where the scope should be per web request.

**Comment by l0nley** [comment]
So, per-container lifescope equals per request? Does i understand you correctly?

**Comment by seesharper** [comment]
No, PerContainer is per container meaning that it acts like a singleton. PerScopeLifetime is per scope where Scope in the context of a web application is per web request.

**Comment by l0nley** [comment]
So, i dont need "You can use LightInject.Web to ensure that you services are scoped per Web request", i need singletons. Does it mean, that i cannot use singletons in my controllers, because they have different lifetime?

**Comment by seesharper** [comment]
You can use singletons, but the actual controllers are per scope
