### ISSUE TITLE
Register constructor with Web API

### ISSUE THREAD

**Issue by tinngv** [seesharper/LightInject#220]
I have code in my controller

 public class HomeController : Controller
    {
        private ITest _svc;        

        public HomeController(ITest svc)
        {
            _svc = svc;
        }       

        public ActionResult Index()
        {
            ViewBag.Title = "Home Page";
            _svc.GetFile();

            return View();
        }
    }

//Example class
public interface ITest
    {
        void GetFile();
    }

    public class TestClass : ITest
    {
        public void GetFile()
        {
            //adsfdsf
        }
    }

Register container
protected void Application_Start()
        {
            AreaRegistration.RegisterAllAreas();
            GlobalConfiguration.Configure(WebApiConfig.Register);
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);

            var container = new ServiceContainer();
            container.RegisterApiControllers();
            //register other services
//            container.EnablePerWebRequestScope();
            container.EnableWebApi(GlobalConfiguration.Configuration);

            container.Register<ITest, TestClass>();
        }

But exception throw
"No parameterless constructor defined for this object"

I'm newbie, please help!

**Comment by seesharper** [comment]
Any chance you could zip the project and send it to me at bernhard.richter@gmail.com?
Or is it available here on GitHub?

**Comment by tinngv** [comment]
@seesharper: I sent email to you. Is there a bug?

**Comment by seesharper** [comment]
I have sent an email to you with a working version of the application.

Bottom line is that the controller that you were trying to inject the dependency into was a MVC controller, not a Web API controller. You need LightInject.Mvc for that. There was also a mix of binary/source versions of LightInject in you solution. I took care of that as well. You should be able to run the application now.
