### ISSUE TITLE
Using common generics

### ISSUE THREAD

**Issue by tg2805** [seesharper/LightInject#221]
LightInject version 4.0.0.0. .NET 4
I have some class MyCollection< T > that only implements ICollection< T >: 
<code>
public MyCollection< T > : ICollection< T > { ... }
</code>
Trying to register/resolve it within container and then verify actual type of resolved instance:
<code>
container.Register(typeof(ICollection<>), typeof(MyCollection<>), "Name");
</code> <br>
<code>
var collection = container.GetInstance< ICollection< int > >("Name"); 
</code> <br>
and then
<code> Type type = collection.GetType(); </code>

I see that the type is <br> <code> System.Collections.Generic.List< int > </code> <br>
<code> (System.Collections.Generic.List`1[System.Int32]) </code>
 
instead of expected <code> MyCollection< int > </code>

**Comment by seesharper** [comment]
Can you produce a fully "working" console app that shows the problem?
Less guesswork :)

**Comment by tg2805** [comment]
Hi, here is a working console app:


using LightInject;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace TestLightInject
{
    public class MyCollection<V> : ICollection<V>
    {
        private IList<V> list = new List<V>();

        public void Add(V item)
        {
            list.Add(item);
        }

        public void Clear()
        {
            list.Clear();
        }

        public bool Contains(V item)
        {
            return list.Contains(item);
        }

        public void CopyTo(V[] array, int arrayIndex)
        {
            list.CopyTo(array, arrayIndex);
        }

        public int Count
        {
            get { return list.Count; }
        }

        public bool IsReadOnly
        {
            get { return false; }
        }

        public bool Remove(V item)
        {
            return list.Remove(item);
        }

        public IEnumerator<V> GetEnumerator()
        {
            return list.GetEnumerator();
        }

        System.Collections.IEnumerator System.Collections.IEnumerable.GetEnumerator()
        {
            return list.GetEnumerator();
        }

    }

    class Program
    {
        static void Main(string[] args)
        {
            ServiceContainer container = new ServiceContainer();

            container.Register(typeof(ICollection<>), typeof(MyCollection<>), "Name");

            var collection = container.GetInstance<ICollection<int>>("Name");
            Type type = collection.GetType();
        }
    }
}

**Comment by seesharper** [comment]
Bug confirmed. Looking into it
