### ISSUE TITLE
LightInject.SignalR causes "Attempt to create a scoped instance without a current scope."

### ISSUE THREAD

**Issue by vegardlarsen** [seesharper/LightInject#222]
I've been having a few issues with the SignalR integration. First, as someone else has mentioned, the documented `RegisterHubs` method does not exist.

I discovered this in one of our older projects, but was able to reproduce it in a minimal new project, which can be [downloaded here](https://dl.dropboxusercontent.com/u/12591686/LightinjectSignalrBug.zip).

Installed Nuget packages (in addition to defaults for a new web project):

```xml
LightInject 4.0.0
LightInject.Interception 1.0.0.8
LightInject.Mvc 1.0.0.4
LightInject.SignalR 1.0.0.1
LightInject.Web 1.0.0.4
LightInject.WebApi 1.0.0.4
Microsoft.AspNet.SignalR 2.2.0 (and dependencies)
```

In addition, I have followed instructions from [this article](http://tech.trailmax.info/2014/09/aspnet-identity-and-ioc-container-registration/) in regards to how to get ASP.net Identity to work well with DI.

To "toggle" the bug, in `Startup.cs`, comment/uncomment this line:

```cs
app.MapSignalR(LightInjectConfig.Container.EnableSignalR());
```

When this line is in place, it causes a `InvalidOperationException`:

```
[InvalidOperationException: Attempt to create a disposable instance without a current scope.]
   LightInject.PerRequestLifeTime.TrackInstance(Scope scope, IDisposable disposable) in c:\Github\LightInject\src\LightInject\NuGet\tmp\Net46\Binary\LightInject\LightInject.cs:6225
   LightInject.PerRequestLifeTime.GetInstance(Func`1 createInstance, Scope scope) in c:\Github\LightInject\src\LightInject\NuGet\tmp\Net46\Binary\LightInject\LightInject.cs:6211
   DynamicMethod(Object[] ) +97
   LightInject.ServiceContainer.TryGetInstance(Type serviceType) in c:\Github\LightInject\src\LightInject\NuGet\tmp\Net46\Binary\LightInject\LightInject.cs:3008
   LightInject.Mvc.LightInjectMvcDependencyResolver.GetService(Type serviceType) in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject.Mvc\LightInject.Mvc.cs:143
   System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +41

[InvalidOperationException: An error occurred when trying to create a controller of type 'WebApplication3.Controllers.HomeController'. Make sure that the controller has a parameterless public constructor.]
   System.Web.Mvc.DefaultControllerActivator.Create(RequestContext requestContext, Type controllerType) +178
   System.Web.Mvc.DefaultControllerFactory.GetControllerInstance(RequestContext requestContext, Type controllerType) +76
   System.Web.Mvc.DefaultControllerFactory.CreateController(RequestContext requestContext, String controllerName) +88
   System.Web.Mvc.MvcHandler.ProcessRequestInit(HttpContextBase httpContext, IController& controller, IControllerFactory& factory) +191
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContextBase httpContext, AsyncCallback callback, Object state) +50
   System.Web.Mvc.MvcHandler.BeginProcessRequest(HttpContext httpContext, AsyncCallback callback, Object state) +48
   System.Web.Mvc.MvcHandler.System.Web.IHttpAsyncHandler.BeginProcessRequest(HttpContext context, AsyncCallback cb, Object extraData) +16
   System.Web.CallHandlerExecutionStep.System.Web.HttpApplication.IExecutionStep.Execute() +103
   System.Web.HttpApplication.ExecuteStep(IExecutionStep step, Boolean& completedSynchronously) +155
```

**Comment by seesharper** [comment]
I got it working if I moved the EnablePerWebRequestScope after enabling SignalR

```
    public partial class Startup
    {
        public void Configuration(IAppBuilder app)
        {
            ConfigureAuth(app);
            app.MapSignalR(LightInjectConfig.Container.EnableSignalR());
            LightInjectConfig.Container.EnablePerWebRequestScope();
        }
    }
```

This is because the EnableSignalR method replaces the scope manager provider with PerLogicalScopeManagerProvider.

Mixing SignalR and Mvc/Web Api withing the same container might not be the best idea.

It would be a lot safer to use two containers, one for mvc/web api and one for SignalR. 

You should also consider whether you really need dependency injection in your hubs. The current version of SignalR does not really support this and LightInject.SignalR makes this possible by creating a scope everytime a hub is created which is everytime it is invoked. SignalR "request" are NOT scoped per web request.

asp.net 5 (vnext) changes this as they provide a common DI abstraction that works across all asp.net technologies. 

My advice here is to either use two containers as described above or drop dependency injection in your hubs all together if you don't actually need it. 

Best regards 
Bernhard Richter

**Comment by vegardlarsen** [comment]
Thanks for the fast reply. I was blocked on this, so I appreciate it a lot! :)

I'll be taking your advice and create two separate containers for SignalR and WebAPI/MVC. :)

If I may make a suggestion; it may be helpful having a sample solution with a complete sample of the recommended setup with all the supported technologies (MVC, WebAPI, SignalR, xUnit, WCF and Nancy), and some guidance on why it is a good idea with separate containers.

It may be less necessary in vNext, but still useful.

**Comment by puzsol** [comment]
Use websockets and the no-scope issue will probably re-surface when the client tries to call a server method (no web request to start the scope).... You might be interested in my response here:
https://github.com/seesharper/LightInject/issues/215

Happy coding :smile:
