### ISSUE TITLE
NRE on LightInjectHttpModule.EndRequest when BeginRequest was not called

### ISSUE THREAD

**Issue by pperboires** [seesharper/LightInject#223]
In my case, I'm using DevExpress components and DevExpress has a HttpModule (ASPxHttpHandlerModule) that when executed prevent next one to execute BeginRequest in some cases. As LightInjectHttpModule is registered after ASPxHttpHandlerModule, LightInjectHttpModule.BeginRequest is not called and therefore the ScopeManager is not added at HttpContext.Current.Items.

**Comment by seesharper** [comment]
Are you using the latest bits?

LightInject.Web version 1.0.0.7

**Comment by pperboires** [comment]
LightInject.Web.Source 1.0.0.4. 
Sorry, I just saw a PR #143 fixing it. 
Thanks!
