### ISSUE TITLE
Understanding GetAllInstances

### ISSUE THREAD

**Issue by zpqrtbnk** [seesharper/LightInject#231]
Trying to understand how default / unnamed service works. I'm probably missing something, but why would the following test fail if the commented out line is un-commented? But not if the service is not named?
```
var container = new ServiceContainer();
container.Register<IFoo, Foo>("foo", new PerContainerLifetime());
// un-comment and the test fails
//var foo = container.GetInstance<IFoo>();
Assert.AreEqual(1, container.GetAllInstances<IFoo>().Count());
```

(version 4.0.1.0 from NuGet)

**Comment by zpqrtbnk** [comment]
wow, that was fast ;-)

**Comment by seesharper** [comment]
Pushed to Nuget. LightInject 4.0.2 :)
