### ISSUE TITLE
Moving From Unity to LightInject Struggling With ASP.NET MVC & Quartz.NET?

### ISSUE THREAD

**Issue by leen3o** [seesharper/LightInject#236]
I am trying to move my project from Unity to LightInject, but I use Quartz.net. This comes with some Unity wrappers, and I tried to deconstruct those and try to relate/map them to the methods available in LightInject... But with no luck.

I tried to follow a couple of other tutorials about integrating Quartz.NET with your favourite Ioc. However, they all revolve around passing the container around. Something I can't do with LightInject as the service container is internal.

Has anyone got Quartz.net working with LightInject in an ASP.NET MVC application?

Quartz has made is simple with Unity and a one liner

container.AddNewExtension<QuartzUnityExtension>();
https://github.com/hbiarge/Quartz.Unity/blob/master/Quartz.Net/Quartz.Unity.40/QuartzUnityExtension.cs

**Comment by seesharper** [comment]
You could either use the binary version of LightInject or create a public
wrapper to be passed around

**Comment by seesharper** [comment]
Seems like this is based on creating custom factory classes. Make the constructors of these classes internal and you can still pass in an internal interface(IServiceContainer).
