### ISSUE TITLE
WCF Integration Error - The sequence contains more than one element

### ISSUE THREAD

**Issue by gktrainer** [seesharper/LightInject#252]
Hi!

I try to use the highest version of LightInject with WCF Integration, but not works, it occurs the below error. With lowest package (LightInject 3.0.2.6, LightInject.Interception 1.0.0.7, LightInject.Wcf 1.0.0.1) for WCF integration, it works!!!

[InvalidOperationException: The sequence contains more than one element]
   System.Linq.Enumerable.Single(IEnumerable`1 source) +396
   LightInject.Interception.ProxyBuilder.CreateCustomAttributeBuilder(CustomAttributeData customAttributeData) in C:\projects\lightinject-interception\build\tmp\Net46\Binary\LightInject.Interception\LightInject.Interception.cs:1235
   LightInject.Interception.ProxyBuilder.ApplyTypeAttributes() in C:\projects\lightinject-interception\build\tmp\Net46\Binary\LightInject.Interception\LightInject.Interception.cs:1435
   LightInject.Interception.ProxyBuilder.GetProxyType(ProxyDefinition definition) in C:\projects\lightinject-interception\build\tmp\Net46\Binary\LightInject.Interception\LightInject.Interception.cs:1187
   LightInject.Wcf.LightInjectServiceHostFactory.CreateServiceProxyType(Type serviceType) in c:\Users\bri\AppData\Local\Temp\ranut2g2\LightInject.Wcf\LightInject.Wcf.cs:275
   LightInject.Wcf.LightInjectServiceHostFactory.CreateServiceHost(Type serviceType, String constructorString, Uri[] baseAddresses) in c:\Users\bri\AppData\Local\Temp\ranut2g2\LightInject.Wcf\LightInject.Wcf.cs:212
   LightInject.Wcf.LightInjectServiceHostFactory.CreateServiceHost(String constructorString, Uri[] baseAddresses) in c:\Users\bri\AppData\Local\Temp\ranut2g2\LightInject.Wcf\LightInject.Wcf.cs:169
   System.ServiceModel.HostingManager.CreateService(String normalizedVirtualPath, EventTraceActivity eventTraceActivity) +1420
   System.ServiceModel.HostingManager.ActivateService(ServiceActivationInfo serviceActivationInfo, EventTraceActivity eventTraceActivity) +52
   System.ServiceModel.HostingManager.EnsureServiceAvailable(String normalizedVirtualPath, EventTraceActivity eventTraceActivity) +641

[ServiceActivationException: Não é possível ativar o serviço '/AnalisadoraService.svc' devido a uma exceção durante a compilação. A mensagem da exceção é: The sequence contains more than one element.]
   System.Runtime.AsyncResult.End(IAsyncResult result) +489035
   System.ServiceModel.Activation.HostedHttpRequestAsyncResult.End(IAsyncResult result) +174
   System.ServiceModel.Activation.ServiceHttpHandler.EndProcessRequest(IAsyncResult result) +11
   System.Web.CallHandlerExecutionStep.OnAsyncHandlerCompletion(IAsyncResult ar) +129

**Comment by seesharper** [comment]
Please provide a demo project.

https://github.com/seesharper/LightInject/blob/master/contributing.md
