### ISSUE TITLE
"Unable to resolve type: System.Threading.Tasks.Task" exception in WebApi application

### ISSUE THREAD

**Issue by the-spyke** [seesharper/LightInject#262]
I'm trying to resolve my own OAuthAuthorizationServerProvider for injecting it into OAuthOptions in my application. But I'm getting a strange exception on app start. I've tried many cases, and it works if I use RegisterInstance method. 

```
Server Error in '/' Application.
Unable to resolve type: System.Threading.Tasks.Task, service name:
[InvalidOperationException: Unable to resolve type: System.Threading.Tasks.Task, service name: ]
   LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:3999
   LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:3970
   LightInject.ServiceContainer.GetInstance(Type serviceType, Object[] arguments) in c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:2675
   LightInject.ServiceContainer.GetInstance(T value) in c:\GitHub\LightInject\NuGet\Build\Net45\LightInject\LightInject.cs:2736
Microsoft.Owin.Security.OAuth.OAuthAuthorizationServerProvider.MatchEndpoint(OAuthMatchEndpointContext context) +10
   Microsoft.Owin.Security.OAuth.<InvokeAsync>d__0.MoveNext() +421
   System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task) +92
   System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task) +58
   Microsoft.Owin.Security.Infrastructure.<Invoke>d__0.MoveNext() +383
```

Steps to reproduce (easy):
1. Create a new standard ASP.Net 4.5.2 Template "Web API" solution
2. Add package "LightInject.WebApi 1.0.0.4"
3. Open "ApplicationOAuthProvider.cs" and remove all constructors
4. Open "Startup.Auth.cs", change creation of OAuthOptions to the following and start the application:

```
var container = new ServiceContainer();
container.Register<ApplicationOAuthProvider, ApplicationOAuthProvider>();

OAuthOptions = new OAuthAuthorizationServerOptions
{
    TokenEndpointPath = new PathString("/Token"),
    Provider = container.GetInstance<ApplicationOAuthProvider>(), // this is the modified line
    AuthorizeEndpointPath = new PathString("/api/Account/ExternalLogin"),
    AccessTokenExpireTimeSpan = TimeSpan.FromDays(14),
    AllowInsecureHttp = true
};
```

```
<package id="LightInject" version="3.0.2.7" targetFramework="net452" />
<package id="LightInject.WebApi" version="1.0.0.4" targetFramework="net452" />
Project target: .Net Framework 4.5.2 "Any CPU"
Windows 10 x64, VS 2015
```

**Comment by the-spyke** [comment]
Another example.
These are my registrations on app start:
`container.Register<MyDbContext>(new PerRequestLifeTime());
container.Register<MyUserManager>(new PerRequestLifeTime());`
This doesn't work:
`container.Register<IOAuthAuthorizationServerProvider, MyAuthorizationServerProvider>(new PerRequestLifeTime());`
And this hack works fine:
`Func<IServiceFactory, IOAuthAuthorizationServerProvider> authProviderFactory =
	sf =>
	{
		using (sf.BeginScope())
		{
			var dbContext = sf.GetInstance<MyDbContext>();
			var userManager = sf.GetInstance<MyUserManager>();

			return new MyAuthorizationServerProvider(dbContext, userManager);
		}
	};

container.Register<IOAuthAuthorizationServerProvider>(authProviderFactory, new PerRequestLifeTime());`

**Comment by kbiel** [comment]
I just ran into this exact same problem. It occurs because the `OAuthAuthorizationServerProvider` base class contains a bunch of `On_Xxxx_` properties with `Func<OAuth_Xxxx_Context, Task>` signatures. LightInject is attempting to inject values by setting those properties. Your work-around is not a hack, but the correct way to fix this. Instead of relying on LightInject to automatically figure out what needs to be injected and what does not, you are telling it explicitly how to construct the object. Alternatively, you could just inherit from `IOAuthAuthorizationServerProvider` since `OAuthAuthorizationServerProvider` is just implementing the interface with all the methods returning null for your convenience.

**Comment by the-spyke** [comment]
@kbiel Thanks for clarification!

**Comment by seesharper** [comment]
You can also disable property injection at the container level
```
containerOptions.EnablePropertyInjection = false 
```

**Comment by the-spyke** [comment]
@seesharper Thank you :)
