### ISSUE TITLE
ServiceLocator.delegates search not working causing major performance issue with Xamarin

### ISSUE THREAD

**Issue by instriker** [seesharper/LightInject#266]
# Environment
LightInject 4.0.8
Platform : Xamarin iOS 

# ISSUE #

When doing myServiceLocator.GetInstance(Type serviceType), the ServiceLocator internally search for  a created delegates by calling delegates.Search(serviceType); If it can't find one, it will create a new delegate and add it to the delegates collection in CreateDefaultDelegate.

The issue is when we run this code in Xamarin (tested with iOS), delegates.Search always returns null. This cause an issue where calling myServiceLocator.GetInstance() too often will grow the delegates collection so big that the application become unresponsive. (got cases where the delegates collection could containts 16000 items for 240 items). We got this kind of issue when the OS is reporting upload progress to the application.

# Code Sample
`

    public interface ISample
    {
    }

    public class Sample:ISample
    {
    }
    public partial class ViewController : UIViewController
    {
        public ViewController(IntPtr handle)
            : base(handle)
        {
        }

        public override void ViewDidLoad()
        {
            base.ViewDidLoad();

            var container = new ServiceContainer();
            var sample = new Sample();
            container.RegisterInstance<ISample>(sample);
            Task.Run(() => SampleIssueStart(container));
        }

        private async Task SampleIssueStart(ServiceContainer container)
        {
            while (true)
            {
                // Issue location : ImmutableHashTableExtensions.Search<TValue>(this ImmutableHashTable<Type, TValue> hashTable, Type key)
                // 
                await Task.Delay(1);
                container.GetInstance<ISample>();
            }
        }
    }`

# CAUSE

* Class : ImmutableHashTableExtensions
* Method: 
 public static TValue Search<TValue>(this ImmutableHashTable<Type, TValue> hashTable, Type key)
* Line of code:
var hashCode = RuntimeHelpers.GetHashCode(key);

The RuntimeHelpers.GetHashsCode(key) is used, but everywhere else it's using key.GetHashCode(). On a pure .Net console apps, it produce the same result, but on Xamarin iOS, it gives differents results. 

Because the results are not the same and we are adding the delegates to the collection inside the ImmutableHashTable constructor with key.GetHashCode() but searching in the Search with RuntimeHelpers.GetHashCode(key), we are never finding the created delegates.

The performance issue then seems to be caused by the fact that the delegates are unmutable and we start creating tons on instances that is getting larger and larger.

# SOLUTION

* Class : ImmutableHashTableExtensions
* Method: 
 public static TValue Search<TValue>(this ImmutableHashTable<Type, TValue> hashTable, Type key)
* Replace Line of code:
var hashCode = RuntimeHelpers.GetHashCode(key);
* By:
var hashCode = key.GetHashCode();

All unit tests still pass when doing this.Also note it's consistent with the other methods that really looks the same:

public static TValue Search<TKey, TValue>(this ImmutableHashTable<TKey, TValue> hashTable, TKey key)

**Comment by seesharper** [comment]
LightInject 4.0.9 has just been published to the official NuGet feed
