### ISSUE TITLE
RegisterFallback( ) not providing servicename as expected

### ISSUE THREAD

**Issue by vegar** [seesharper/LightInject#271]
I'm trying to find a generic way of injecting mongo collection into services. The only way I have found is using a `RegisterFallback` that can return a new collection based on a dynamic call to the `IMongoDatabase`:

```
 serviceRegistry.RegisterFallback((type, s) => type.IsSubclassOfRawGeneric(typeof (IMongoCollection<>)),
                request =>
                {
                    var mongoDb = request.ServiceFactory.GetInstance<IMongoDatabase>();

                    var collectionType = request.ServiceType.GenericTypeArguments[0];
                    var method = mongoDb.GetType().GetMethod("GetCollection");
                    var methodInfo = method.MakeGenericMethod(collectionType);

                    return methodInfo.Invoke(mongoDb, new object[] {collectionType.Name, null});
                }, new PerContainerLifetime());
```

This allows me to inject collections into constructors, but only as long as the type of the collection matches the name of the collection.

e.g.  The mongo collection `Customer` can be injected into a class as `IMongoCollection<Customer>`, but as soon as I want to get the same collection but as a collection of `BsonDocument` instead, I have trouble..

I tried to solve this using the service name, but the `RegisterFallback` delegate doesn't get the service name.

First I expected it to be the name of the parameter, so for

  `public  CustomerService(IMongoCollection<Customer> customerCollection)`

I expected the servicename to be `customerCollection`. 

Then I tried the annotation addon, changing the constructor to

  `public  CustomerService([Inject("customerCollection")]IMongoCollection<Customer> customerCollection)`

expecting the service name `customerCollection` to be available in the registered fallback. But no luck there either....

Why ain't the service name provided to the fallback method?
Is this the complete wrong path for injecting arbitrary generic interfaces?

**Comment by seesharper** [comment]
You might want to check out the RegisterConstructorDependency method that allows you dynamically construct a value for the given dependency (ParameterInfo).

**Comment by vegar** [comment]
`RegisterConstructorDependency` doesn't handle open generics, though?

I want be able to say 'If anyone asks for a IMongoCollection<> of any type, come to me'. And that's what I'm able to do with the fallback.

**Comment by vegar** [comment]
Ok - I think I see what I'm doing wrong.

My fallback predicate is too simple.

As long as I'm returning true for all requests for IMongoCollection<>, it will ask me for the instance without a service name.

If I'm returning false for a request for a IMongoCollection<> without a service name, it will try once more *with* the service name.

And as always, the source gives away the truth:

```
        private Action<IEmitter> GetEmitMethodForDependency(Dependency dependency)
        {
            if (dependency.FactoryExpression != null)
            {
                return skeleton => EmitDependencyUsingFactoryExpression(skeleton, dependency);
            }

            Action<IEmitter> emitter = GetEmitMethod(dependency.ServiceType, dependency.ServiceName);
            if (emitter == null)
            {
                emitter = GetEmitMethod(dependency.ServiceType, dependency.Name);
                if (emitter == null && dependency.IsRequired)
                {
                    throw new InvalidOperationException(string.Format(UnresolvedDependencyError, dependency));
                }
            }

            return emitter;
        }
```

It first tries with to resolve the dependency with the ServiceName, then the parameter name.

This doesn't explain why my `[Inject(....)]` attempt didn't work, but it solved the problem without attributes, so I'm happy :-)

**Comment by vegar** [comment]
Got an new issue....
After getting a hit once, it'll never call the fallback again, so it passes the same collection to both constructor parameters, even after fixing the predicate and removing the `PerContainerLifete` specifier.

**Comment by seesharper** [comment]
Okay, that is a little strange. Take a look at the following example. At least this seems to work and I think this resembles what you are trying to do here

```
class Program
{
    static void Main(string[] args)
    {
        var container = new ServiceContainer();

        container.Register<Foo>();

        container.RegisterFallback((type, s) => true, sr => CreateBar(sr.ServiceType));

        var firstFoo = container.GetInstance<Foo>();
        var secondFoo = container.GetInstance<Foo>();

        Debug.Assert(firstFoo.Bar != secondFoo.Bar);
    }

    private static object CreateBar(Type closedGenericServiceType)
    {
        Type closedGenericImplementingType = typeof (Bar<>).MakeGenericType(closedGenericServiceType.GenericTypeArguments);
        return Activator.CreateInstance(closedGenericImplementingType);
    }
}


public class Foo
{
    public IBar<string> Bar { get; private set; }

    public Foo(IBar<string> bar)
    {
        Bar = bar;
    }
}

public interface IBar<T>
{        
}

public class Bar<T> : IBar<T>
{        
}
```

That being said, this might call for another non-generic Register method overload that makes it possible to register a factory delegate for a given type.

```
container.Register(typeof(IBar<>), serviceRequest => [return instance here]);
```

**Comment by vegar** [comment]
A simpler solution would of cause be great, but I think the current solution ought to work as well.

Take a look at the following code. It fails.

```
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using LightInject;

namespace ConsoleApplication2
{
    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();

            container.Register<IBar, Bar>();

            container.RegisterFallback((t, s) =>
                                       {
                                           return !string.IsNullOrEmpty(s);
                                       },
                request =>
                {
                    var genericType = request.ServiceType.GenericTypeArguments[0];

                    var concreteType = typeof (Foo<>).MakeGenericType(genericType);
                    return Activator.CreateInstance(concreteType, request.ServiceName);
                });


            var bar = container.GetInstance<IBar>();

            Debug.Assert(bar != null);
            Debug.Assert(bar.Foo1 != bar.Foo2);

            Debug.Assert(bar.Foo1.ServiceName == "foo1");
            Debug.Assert(bar.Foo2.ServiceName == "foo2");
        }

        public interface IFoo<T>
        {
            string ServiceName { get; set; }
        }

        public class Foo<T> : IFoo<T>
        {
            public Foo(string serviceName)
            {
                ServiceName = serviceName;
            }

            public string ServiceName { get; set; }
        }

        public interface IBar
        {
            IFoo<object> Foo1 { get; set; }
            IFoo<object> Foo2 { get; set; }
        }

        public class Bar : IBar
        {
            public IFoo<object> Foo1 { get; set; }
            public IFoo<object> Foo2 { get; set; }

            public Bar(IFoo<Object>  foo1, IFoo<Object> foo2)
            {
                Foo1 = foo1;
                Foo2 = foo2;
            }
        }
    }
}

```

As you can see from the following screenshot, Foo2 has the wrong service name:

![image](https://cloud.githubusercontent.com/assets/764517/14618728/4ec13dac-05b4-11e6-877a-889ffdb225bc.png)

**Comment by seesharper** [comment]
Okay, I think I see what is going on here. The fallback mechanism resolves the first foo ("foo1") as the  services and since when injecting the second instance which really starts off without a service name since using the parameter name is considered a last resort, it injects the first instance. 

My question is, do you really need to make this rather loose coupling between the parameter name and a named service? Wouldn't it be enough if LightInject could resolve the closed generic type based on the generic parameter type as demonstrated in the first example I sent you? 

IMHO, relying on a parameter to be named in a certain way makes the code very brittle as you would get no compiler error if you or someone else changes the name of the parameter.

"e.g. The mongo collection Customer can be injected into a class as IMongoCollection<Customer>, but as soon as I want to get the same collection but as a collection of BsonDocument instead, I have trouble.."

Wouldn't this be another collection all together? Or would it still be IMongoCollection<Customer> only somehow with a different representation behind the scenes?

**Comment by vegar** [comment]
I do agree  that param names are a loose and brittle way of setting up dependencies, but this is the alternative I have found. Almost found... ...since it doesn't work... :-) I tried making it a little less 'magic' by having the `[Inject("servicename")]` annotation, but it didn't seem to help...

The way the c# mongo driver works, is that an `IMongoCollection<>` represents a collection of documents in a database. Since mongo doesn't have any schema, a collection can contain different documents with different properties.

When you add type to the collection, like `IMongoCollection<Customer>`, you give a hint to the driver on how the documents look. It will give you a lot of help when constructing filters and queries and so on, and it will also serialize documents using this definition.

When getting a `IMongoCollection<BsonDocument>` reference to a collection, you are basically saying that you don't know/care what type of documents there are. You don't have a .net class representation of it. What you get instead is something like a json structure or dictionary of dictionaries. This is great when you need to change how documents are stored. Like if you have done major changes to your `Customer` class, you wan't be able to deserialize the document into a `Customer`. So you will need to load the document as a `BsonDocument`, restructure the content, and save it. Then you can load it again as a `Customer`. 

So in my case, I want a reference to two mongo collections, 'foo1' and 'foo2', and I want to treat them as a collection of `BsonDocument`s. 

I don't know how this *should* be done, but I really like the idea of injecting the collections into my service instead of having the service bringing in the collections by it self. (In tests, I'm namespacing the collection names to allow for multiple testruns agains the same database. This will be much less tidy if the service fetches the collection it self, since it then needs to know about this namespacing...)

If there are no easy solution, I'll just have to inject the `IMongoDatabase` interface instead, and do fetch the collections inside of the service, but I would love for another solution.

**Comment by vegar** [comment]
OK. Think I found a workaround.

I register a `IMongoCollection<BsonDocument>` factory that takes the collection name as parameter.

```
            serviceRegistry.Register<string, IMongoCollection<BsonDocument>>((factory, s) =>
                                                                             {
                                                                                 var mongoDb = factory.GetInstance<IMongoDatabase>();

                                                                                 return mongoDb.GetCollection<BsonDocument>(s);
                                                                             });
```

So my service constructor now takes a `Func<string, IMongoCollection<BsonDocument>>` instead of the `IMongoCollection<BsonDocument>`.

In my test, I just give it a delegate returning the namespaced collection.

Still would like a way of getting the `IMongoCollection<BsonDocument>` directly, but a factory is better than nothing :-)

**Comment by seesharper** [comment]
I think that it is a very good workaround too. Instead of injecting data, you are now injecting a factory to get the data. You might consider being even more explicit than just a Func by creating your own interface called ICollectionFactory or something similar. I often find that Func delegates expresses the intent rather vaguely as opposed to an explicit interface. But that is just a matter of opinion :)

**Comment by seesharper** [comment]
Any reason you can't do this?

```
container.RegisterConstructorDependency<IMongoCollection<BsonDocument>>((factory, parameterInfo) =>
{
    //Do something with the parameterinfo here such as looking at the name of the parameter
    //return collection here 
});
```

**Comment by vegar** [comment]
At the start of this thread, I tried handling both `IMongoCollection<BsonDocument>` and all other `IMongoCollection< >` variants.

`RegisterConstructorDependency<>` doesn't allow for open generics, so that's why I didn't go further with that option.

For handling only `IMongoCollection<BsonDocument>` this might be a great solution - if the delegate is always called: If the container doesn't try to be smart and gives me the same collection twice like it did for the fallback attempt...

I'll try it out tomorrow, but to night I have to play with [LearnToMod](http://mod.learntomod.com/) so that I'm able to teach a bunch of kids tomorrow.. :-)

**Comment by seesharper** [comment]
The delegate will be called every time :)

**Comment by vegar** [comment]
On the other hand, the factory will create a tighter link - not relying on the parameter name, so I guess keeping to the factory is best after all...
