### ISSUE TITLE
Change Log Missing?

### ISSUE THREAD

**Issue by pagebrooks** [seesharper/LightInject#272]
Hi! It seems that your release history link is not working and I can't seem to find the actual change log anywhere:

On the Nuget Gallery page:
http://www.lightinject.net/#whatsnew

Do you have a change log for the versions 4.0.0 through 4.0.9?

Thanks!

**Comment by dixonwille** [comment]
I would like to see changelog from 4.1.5 to 5.0.0

**Comment by seesharper** [comment]
Changes between tags  https://github.com/seesharper/LightInject/compare/v4.1.5...v5.0.0

Future releases will provide a "What's new" on GitHub Releases 👍
