### ISSUE TITLE
LightInject.SignalR repository removed

### ISSUE THREAD

**Issue by modernist** [seesharper/LightInject#273]
I noticed that the LightInject.SignalR repository was recently removed. The package is still available on NuGet. Are there any plans to maintain this project or is it abandoned?

**Comment by seesharper** [comment]
It is not removed, just moved :)

https://github.com/seesharper/LightInject/tree/master/oldsource/LightInject.SignalR

I am in the process of moving all extensions into its own repo so that is why it is located under the oldsource folder
