### ISSUE TITLE
NuGet packs missing .NET 4.0 (since 4.0.1)

### ISSUE THREAD

**Issue by michal-ciechan** [seesharper/LightInject#275]
Cannot install any version of LightInject since 4.0.0 in a .NET 4.0 project.

Seems that the net40 is missing from the newer NuGet packages

**Comment by seesharper** [comment]
That is correct. .Net 4.0 is no longer a supported framework.

https://blogs.msdn.microsoft.com/dotnet/2015/12/09/support-ending-for-the-net-framework-4-4-5-and-4-5-1/
