### ISSUE TITLE
ASP.Net core with SPA routes cause an unhandled exception

### ISSUE THREAD

**Issue by AlexFlat** [seesharper/LightInject#276]
We are using LightInject with an MVC6 app and have recently introduced a SPA to the site.
The SPA requires MVC to listen to all/any routes the client asks for.

When adding the wildcard route to MVC LightInject fails with;
An unhandled exception occurred while processing the request.
InvalidOperationException: Attempt to create a scoped instance without a current scope.

When using another IoC this error cannot be reproduced.

Config:
DNX 4.5.1
LightInject 4.0.9
LightInject.Microsoft.Dependency.Injection 1.0.1-rc2
Windows Server 2012 R2

Reproduction Steps:
1. Create a new MVC application using the ASP.Net 5 Template
2. Add a WildCard routes to the MVC Routes
                routes.MapRoute(
                    name: "spa",
                    template: "{*url}",
                    defaults: new { controller = "Home", action = "Index" });
3. Add LightInject (4.0.9) and LightInject.Microsoft.Dependency.Injection (1.0.1-rc2)
4. Update the ConfigureServices in Startup to return the IServiceProvider from LightInject
            var container = new LightInject.ServiceContainer();
            return container.CreateServiceProvider(services);
5. Start the App
6. Load a Route that is NOT in MVC (eg. http://localhost:5000/abcdefg

Expected:
The Home View loads

Actual:
Exception in the page
InvalidOperationException: Attempt to create a scoped instance without a current scope.
LightInject.PerScopeLifetime.GetInstance(Func`1 createInstance, Scope scope) in LightInject.cs
DynamicMethod(Object[] )
LightInject.ServiceContainer.TryGetInstance(Type serviceType) in LightInject.cs
LightInject.Microsoft.DependencyInjection.LightInjectServiceProvider.GetService(Type serviceType) in LightInject.Microsoft.DependencyInjection.cs
Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
Microsoft.Extensions.DependencyInjection.ServiceProviderExtensions.GetRequiredService[T](IServiceProvider provider)
Microsoft.AspNet.Mvc.ViewFeatures.SaveTempDataAttribute.CreateInstance(IServiceProvider serviceProvider)
Microsoft.AspNet.Mvc.Filters.DefaultFilterProvider.ProvideFilter(FilterProviderContext context, FilterItem filterItem)
Microsoft.AspNet.Mvc.Filters.DefaultFilterProvider.OnProvidersExecuting(FilterProviderContext context)
Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.GetFilters()
Microsoft.AspNet.Mvc.Controllers.FilterActionInvoker.<InvokeAsync>d__44.MoveNext()

[LightInjectException.txt](https://github.com/seesharper/LightInject/files/260385/LightInjectException.txt)

**Comment by seesharper** [comment]
Just tried it and I am unable to reproduce the error. Could you push the example up on Gitgub so that I can take a look at it?

**Comment by AlexFlat** [comment]
Thanks for the quick reply.

I will try to publish it tomorrow.


I'm a bit of a noob to git so will let you know when I do it.


Thanks again,


Alex





On Thu, May 12, 2016 at 2:43 AM -0700, "Bernhard Richter" <notifications@github.com> wrote:












Just tried it and I am unable to reproduce the error. Could you push the example up on Gitgub so that I can take a look at it?

**Comment by AlexFlat** [comment]
Hi,

Just to confirm, I uploaded the code to:
https://github.com/AlexFlat/LightInjectTest

Let me know if you need anything else.

Thanks for your time.

**Comment by seesharper** [comment]
I also need to update this to the latest RC2 bits and build with the dotnet CLI. This means a new release of LightInject.Microsoft.DependencyInjection and LightInject itself. Will be available next week. If you need to get things running before that, uninstall the LightInject.Microsoft.DependencyInjection package and include the source file in your project.
https://raw.githubusercontent.com/seesharper/LightInject.Microsoft.DependencyInjection/master/src/LightInject.Microsoft.DependencyInjection/LightInject.Microsoft.DependencyInjection.cs

**Comment by AlexFlat** [comment]
Thanks for your time on this.
We are still in development and will be moving to RC2 in the next few
weeks, so we will wait til you release it.

Thanks again for your work,

Alex

**Comment by AlexFlat** [comment]
We just updated to .Net Core RC2 and the bug is fixed.
Thanks again for your time on this.

Alex
