### ISSUE TITLE
Can IServiceFactory implement System.IServiceProvider ?

### ISSUE THREAD

**Issue by Shazwazza** [seesharper/LightInject#283]
I can make a PR for this if you like but it would be great to have `IServiceFactory` implement `System.IServiceProvider` to make it more inline with aspnetcore's DI framework since it assumes that the container used there implements this interface. 

I can create a work around in my own code without issue but was hoping this could be part of Light Inject's core?

**Comment by Shazwazza** [comment]
Ah, i do see the work around is part of `LightInject.Microsoft.DependencyInjection` @ https://github.com/seesharper/LightInject.Microsoft.DependencyInjection 

I can use that instead but wondering if there's any reason to not just make the IServiceFactory implement IServiceProvider, even explicitly

**Comment by seesharper** [comment]
No particular reason really besides from one less dependency to worry about. Another "issue" is that the IServiceProvider interface is often used as a all-purpose object factory that might encourage the service locator pattern which is considered bad practice. Decided not to implement at this time. Hope that you can live with that :)

**Comment by Shazwazza** [comment]
Fair enough :) Another solution could be to explicitly implement the interface so it would need to be cast to IServiceProvider if required. I'm ok with the work around though so no issue for me :)
