### ISSUE TITLE
LightInject.Mocking throws MethodNotFoundException

### ISSUE THREAD

**Issue by modernist** [seesharper/LightInject#286]
I am using LightInject 4.0.10-rc2-2, LightInject.Mocking 1.0.0.5, Moq 4.5.10 and Castle.Core 3.3.3. When using the StartMocking extension method on my container, I get this exception:
```csharp
System.MissingMethodException: Method not found: 'Void LightInject.Registration.set_FactoryExpression(System.Linq.Expressions.LambdaExpression)'.
at LightInject.Mocking.LightInjectMocking.CreateFactoryBasedMockServiceRegistration[TService](Func`1 mockFactory, String serviceName, ILifetime lifeTime)
   at LightInject.Mocking.LightInjectMocking.StartMocking[TService](IServiceRegistry serviceRegistry, Func`1 mockFactory, String serviceName) in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject.Mocking\LightInject.Mocking.cs:line 103
   at LightInject.Mocking.LightInjectMocking.StartMocking[TService](IServiceRegistry serviceRegistry, Func`1 mockFactory) in c:\Users\bri\Documents\GitHub\LightInject\NuGet\Build\Net45\LightInject.Mocking\LightInject.Mocking.cs:line 117
   at LightInjectMockingTest.Tests.MockingUnitTest.TestWithMocking() in M:\Projects\Test Projects\LightInjectMockingTest\LightInject

MockingTest.Tests\MockingUnitTest.cs:line 40
```

The issue manifests with version 4.0.9 as well. You can find a test project here: https://github.com/modernist/LightInjectMockingTest  - try running the unit tests, the TestWithMocking test fails because the exception is thrown.

**Comment by modernist** [comment]
I believe this issue is related to the various #if / #endif directives used in the code, as well as version mismatches between the NuGet packages. In the version used when compiling the LightInject.Mocking NuGet package, the `Registration.FactoryExpression` member is defined as a `Delegate`, whereas in the main source tree it is defined as a `LambdaExpression`, thus the automatic cast in the assignment fails and the call to `Compile` is required. I have been able to overcome the error by manually adding the source code for LightInject.Mocking in my test project and changing the `CreateFactoryBasedMockServiceRegistration` method as follows:

```csharp
var mockServiceRegistration = new ServiceRegistration { ServiceType = typeof(TService), ServiceName = serviceName, Lifetime = lifeTime, IsReadOnly = true };
Expression<Func<IServiceFactory, TService>> factoryExpression = factory => mockFactory();
mockServiceRegistration.FactoryExpression = factoryExpression.Compile();
return mockServiceRegistration;
```

**Comment by seesharper** [comment]
LightInject.Mocking is a library that going to be depreciated as it relied on changing the configuration of the container after the first GetService had been made to the container. This could in certain cases cause bugs that were very hard to find. 

LightInject.Mocking also encourage sharing state and altering between test methods which was a really bad idea. Most modern test frameworks today run tests in parallel and that makes it even more important that test methods does not alter shared state.

**Comment by kreediam** [comment]
Thanks @seesharper, would you consider updating your documentation with this information for future seekers?

Is there a safe alternative that you would recommend to achieve a similar result? Perhaps [LightInject.AutoMoq](https://github.com/apjanes/LightInject.AutoMoq) for Moq users?

**Comment by seesharper** [comment]
All register methods will overwrite the existing registration as long as it is done before the first call to GetInstance. This means that we can register the actual services as we would in a production app and then   register the mocks needed in each particular test. 

Something like this
```
container.RegisterFrom<ProductionCompositionRoot>();
container.Register<IFoo>(factory => fooMock.Object);
```
