### ISSUE TITLE
Allow services to be retrieved directly from the scope

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject#291]
```
using(var scope = container.BeginScope())
{
    var foo = scope.GetInstance<IFoo>();
}
```

**Comment by geirsagberg** [comment]
This would be really useful :) Has any work been done on this? If not I might have a go...

**Comment by geirsagberg** [comment]
Could be implemented simply by letting `Scope` have a reference to the container as a `IServiceFactory`:

    using(var scope = container.BeginScope())
    {
        var foo = scope.ServiceFactory.GetInstance<IFoo>();
    }

That way Scope wouldn't have to implement `IServiceFactory` itself.

The other alternatives I see are:
- Create a new limited interface `IScopedServiceFactory` with fewer methods, implemented by `Scope`
- Implement `IServiceFactory` on `Scope` but pass all calls to the inner container

**Comment by seesharper** [comment]
Actually I did a spike a while ago and the approach was quite similar to the one that you are describing here. The reason I started to think about this was because of the integration with Microsoft.Extensions.DependencyInjection. This feature would have made that integration much smoother.  One thing to remember is that we are stepping into a dangerous territory when possibly changing the internal workings of the scoping mechanism. 

The challenge here is going from ambient scopes handled by the ScopeManager class to retrieving instances directly off the scope. 

This code sort of illustrates the challenge :)

```
using(var outerscope = container.BeginScope())
{
    using(var innerscope= container.BeginScope())
    {
         var foo = outerscope.ServiceFactory.GetInstance<IFoo>();        
    }    
}
```

**Comment by geirsagberg** [comment]
Ah, I see how this might be less than straight-forward :)

My use case is not as complex, so I think I'll use a workaround for now, but will let you know if I find a good way to handle this issue.

**Comment by seesharper** [comment]
Related to #112

**Comment by seesharper** [comment]
We could slim down the IServiceFactory to the a bare minimum and implement all the GetInstance methods as extension methods. That way we don't need to reimplement all the methods in the Scope class

**Comment by geirsagberg** [comment]
Sounds like a good idea, I generally prefer extension methods rather than multiply-overloaded interfaces for this exact reason :)

**Comment by geirsagberg** [comment]
As far as I can see, all the `GetInstance` methods can be implemented as calls to this method I created: 

```csharp
public object GetInstance(Type serviceType, string serviceName, IEnumerable arguments, bool throwIfNotFound)
{
    GetInstanceDelegate instanceDelegate;
    if (serviceName != null) {
        var key = Tuple.Create(serviceType, serviceName);
        instanceDelegate = namedDelegates.Search(key) ?? CreateNamedDelegate(key, throwIfNotFound);
    } else {
        instanceDelegate = delegates.Search(serviceType) ?? CreateDefaultDelegate(serviceType, throwIfNotFound);
    }

    var constantsWithArguments = arguments != null 
        ? constants.Items.Concat(new object[] {arguments}).ToArray()
        : constants.Items;

    return instanceDelegate(constantsWithArguments);
}
```

One caveat with extension methods is that one can no longer use private members in the future, without reverting to non-extension methods. Not sure if this might be an issue?

**Comment by seesharper** [comment]
I don't think we can route everything through a single method mostly because of performance reasons. It is however very few methods that needs to remain interface/instance methods and there should not be any performance issues related to moving most of the "sugar" into extension methods. 

To illustrate consider this code

```
public class Container
{
	public object GetInstance(Type serviceType)
	{
		return null;
	}
	
	public T GetInstance<T>()
	{
		return (T)GetInstance(typeof(T));
	}
}

```

The IL generated for the generic GetInstance method

```
Container.GetInstance:
IL_0000:  ldarg.0     
IL_0001:  ldtoken     01 00 00 1B 
IL_0006:  call        System.Type.GetTypeFromHandle
IL_000B:  call        Container.GetInstance
IL_0010:  unbox.any   01 00 00 1B 
IL_0015:  ret     
```

Then we move the generic GetInstance method into an extension method like this

```
public static class CopntainerExtensions
{
	public static T GetInstanceExtensionMethod<T>(this Container container)
	{
		return (T)container.GetInstance(typeof(T));
	}
}
```

The IL generated for the extension method is ALMOST the same. 
It still has to load the target instance which is the first parameter of any extension method.

```
CopntainerExtensions.GetInstanceExtensionMethod:
IL_0000:  ldarg.0     
IL_0001:  ldtoken     01 00 00 1B 
IL_0006:  call        System.Type.GetTypeFromHandle
IL_000B:  callvirt    Container.GetInstance
IL_0010:  unbox.any   01 00 00 1B 
IL_0015:  ret       
```

Notice the difference? The call to the non generic GetInstance method is emitted as a OpCodes.callvirt rather than OpCodes.call which I seem to remember is slightly less performant. 
This is geeky stuff, I know :) But it is this attention to details that makes LightInject so fast :)

That being said, I do think that the performance hit is negligible, but I need to measure it to be sure :)

**Comment by geirsagberg** [comment]
Np, thanks for explaining, I agree we shouldn't compromise the blazing fast performance of LightInject :)

**Comment by seesharper** [comment]
Part of LightInject. 5.0.0
