### ISSUE TITLE
LightInject.Source: undeclared symbols

### ISSUE THREAD

**Issue by yodasad** [seesharper/LightInject#292]
Hello!

If I create a simple .NET project (not .NET Core) and install LightInject.Source package, the project stops compiling due to undeclared symbols (NET45, NET46 and so on). Should I declare these symbols manually in .csproj (or with /define: option) or is there some problem with the package? I didn't find any information about it in the documentation.

**Comment by seesharper** [comment]
You can just declare them in your project properties page

**Comment by yodasad** [comment]
OK. Thank you!

**Comment by karunagoyal** [comment]
Below piece of code is giving error when I include source for lightinject.cs . It says The name 'CreateDynamicMethod' does not exist in the current context	`EPPS.LightInject`
 public DynamicMethodSkeleton(Type returnType, Type[] parameterTypes)
            {
                CreateDynamicMethod(returnType, parameterTypes);
            }

            public IEmitter GetEmitter()
            {
                return emitter;
            }

            public Delegate CreateDelegate(Type delegateType)
            {
                return dynamicMethod.CreateDelegate(delegateType);
            }

#if NET452 || NET46
            private void CreateDynamicMethod(Type returnType, Type[] parameterTypes)
            {
                dynamicMethod = new DynamicMethod(
                    "DynamicMethod", returnType, parameterTypes, typeof(ServiceContainer).GetTypeInfo().Module, true);
                emitter = new Emitter(dynamicMethod.GetILGenerator(), parameterTypes);
            }
#endif
#if NETSTANDARD1_1 || NETSTANDARD1_3 || NETSTANDARD1_6
            private void CreateDynamicMethod(Type returnType, Type[] parameterTypes)
            {
                dynamicMethod = new DynamicMethod(returnType, parameterTypes);
                emitter = new Emitter(dynamicMethod.GetILGenerator(), parameterTypes);
            }
#endif
        }

**Comment by karunagoyal** [comment]
`public DynamicMethodSkeleton(Type returnType, Type[] parameterTypes)
            {
                CreateDynamicMethod(returnType, parameterTypes);
            }

            public IEmitter GetEmitter()
            {
                return emitter;
            }

            public Delegate CreateDelegate(Type delegateType)
            {
                return dynamicMethod.CreateDelegate(delegateType);
            }

#if NET452 || NET46
            private void CreateDynamicMethod(Type returnType, Type[] parameterTypes)
            {
                dynamicMethod = new DynamicMethod(
                    "DynamicMethod", returnType, parameterTypes, typeof(ServiceContainer).GetTypeInfo().Module, true);
                emitter = new Emitter(dynamicMethod.GetILGenerator(), parameterTypes);
            }
#endif
#if NETSTANDARD1_1 || NETSTANDARD1_3 || NETSTANDARD1_6
            private void CreateDynamicMethod(Type returnType, Type[] parameterTypes)
            {
                dynamicMethod = new DynamicMethod(returnType, parameterTypes);
                emitter = new Emitter(dynamicMethod.GetILGenerator(), parameterTypes);
            }
#endif
        }
`

Sorry for bad formatting
