### ISSUE TITLE
something wrong with container.GetAllInstance?

### ISSUE THREAD

**Issue by liiujinfu** [seesharper/LightInject#293]
hi:
 here is code:
`interface IA{}`
`class A : IA {}`

I tried to register A like this: container.Register(A) and container.Register(IA, A) at the same time,but when I call the container.GetAllInstance(IA), that returns two instances of A, is someting wrong with them?

**Comment by seesharper** [comment]
http://www.lightinject.net/#ienumerablet

To disable variance

```
var container = new ServiceContainer(new ContainerOptions { EnableVariance = false });
```
