### ISSUE TITLE
Consider making Register calls return IServiceContainer for fluent chaining

### ISSUE THREAD

**Issue by geirsagberg** [seesharper/LightInject#295]
As far as I can see, all `Register`-methods return `void` today. If they instead returned the `IServiceContainer`, they could be chained fluently, so instead of:

    container.Register<IFoo, Foo>();
    container.Register<IBar, Bar>();
    container.RegisterAssembly(...);

One could do:

    container.Register<IFoo, Foo>()
      .Register<IBar, Bar>()
      .RegisterAssembly(...);

Would you be open for a pull request?

**Comment by seesharper** [comment]
That would be great. It should however return IServiceRegistry which is the
interface that contains all the registration methods.

**Comment by geirsagberg** [comment]
Pull request #296 added :)

**Comment by seesharper** [comment]
Currently on vacation. Will merge this first thing next week:)

**Comment by geirsagberg** [comment]
Closing this as #296 is merged, thanks :)
