### ISSUE TITLE
Interception: Method not found 'LightInject.IServiceRegistry.Decorate'

### ISSUE THREAD

**Issue by thenem** [seesharper/LightInject#302]
I am currently using the following packages:
- LightInject v4.1.0
- LightInject.Interception v1.0.0.11
- LightInject.Wcf v1.0.0.1

I am experiencing the following error when trying to register an interception:
> _An exception of type 'System.MissingMethodException' occurred in LightInject.Interception.dll but was not handled in user code_

> _Additional information: Method not found: 'Void LightInject.IServiceRegistry.Decorate(LightInject.DecoratorRegistration)'._

I found that when I downgraded the LightInject package to **v4.0.11**, the error did not occur anymore.

**Comment by seesharper** [comment]
Yeah I know. Working on a fix right now. Stay tuned:)

**Comment by geirsagberg** [comment]
Made a PR: https://github.com/seesharper/LightInject.Interception/pull/6

**Comment by thenem** [comment]
Works for me now. Thanks so much for the quick turnaround!
