### ISSUE TITLE
Bump to 5.0.0 beacuse of breaking change

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject#303]
The breaking change does not require any code changes, but because we have changed the signature of all IServiceRegistry methods, all assemblies compiled with a reference to LightInject needs to be recompiled.  The only thing that has changed is that all Registerxxx methods now returns IServiceRegistry to allow for a more fluent registration API. 

https://github.com/seesharper/LightInject/pull/296

http://stackoverflow.com/questions/9178533/why-adding-a-return-type-to-a-void-returning-method-causes-a-missingmethodexcept

**Comment by geirsagberg** [comment]
By the way, maybe the .nuspec dependencies should be specified with an exclusive upper bound, e.g. `[5.0,6.0), otherwise nuget will download a new (potentially) major version (if specifying highest dependency available).

**Comment by seesharper** [comment]
Decided to stick with just bumping the minor on this one
