### ISSUE TITLE
Can't add nuget package to UWP app

### ISSUE THREAD

**Issue by stalek71** [seesharper/LightInject#305]
I created UWP app from Blank App(Universal Windows) template. and can't add reference to LightInject through nuget package. I receive error/info like below:

```
System.Reflection.Emit.ILGeneration 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.ILGeneration on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
System.Reflection.Emit.Lightweight 4.0.1 provides a compile-time reference assembly for System.Reflection.Emit.Lightweight on UAP,Version=v10.0, but there is no run-time assembly compatible with win10-arm-aot.
One or more packages are incompatible with UAP,Version=v10.0 (win10-arm-aot).
```

Is it possible to use it win Win10 apps?
I was trying to add latest stable version (4.1.0)

**Comment by seesharper** [comment]
I know how to fix this, but I don't understand why :)

https://github.com/dotnet/corefx/issues/11429

In the meantime, if you reference the PCL version from the NuGet package, you should have no problem using LightInject in a UWP app.

**Comment by stalek71** [comment]
I will wait a bit yet to see if MS clarify what to do with IL emit :)   
In my case I need "static" resolving after container initialization(s).   

btw: Is it possible to generate some code(template specializations in c# for instance) from container data (when the container has been fully initialized and knows all the dependencies), so I can reference such file instead of dynamically configured container? I understand of course such template specializations have to honor scoped allocations and so on, but maybe it's available already, but I just don't know about it yet ...

**Comment by seesharper** [comment]
Published to NuGet

**Comment by stalek71** [comment]
Works like a charm :)
Thanks for so quick response :)

**Comment by stalek71** [comment]
One more question yet :)
do you plan to port AutoFactory to UWP in the nearest time?
I can create manually interfaces to factories when necessary of course, but if it's available and "almost" ready why not to take it into account :) ...

**Comment by seesharper** [comment]
I am afraid that is not possible since the UWP platform does not allow creating new types at runtime.

**Comment by stalek71** [comment]
Yes, I was supposing it will be your answer because of the platform restrictions :(
AppDomain unavailability forced me also to change the way I update the code, because I can't just unload some app fragment created as some domain and to replace it with new code on the fly. I have not found any way to unload libs from running app yet, but maybe such feature appeared in some other area/namespace and I just don't know about it yet ... :(
Thanks for the answer...

**Comment by seesharper** [comment]
https://msdn.microsoft.com/en-us/windows/uwp/porting/desktop-to-uwp-root

Seems like the Windows Store has some auto update feature you might use

**Comment by stalek71** [comment]
I have seen this feature already, but didn't play with it yet :)
Silent installation can't/shouldn't close working apps so restart of working app is probably necessary again (when they loaded old libs into process space already). I wonder if store apps work on shadow libs or locks them directly in place (where they have been installed). I have to check it when I have some more time... Thanks for pointing it out :)
