### ISSUE TITLE
#TryGetInstance throws Exception

### ISSUE THREAD

**Issue by jmattheis** [seesharper/LightInject#306]
LightInject Version: 4.1.1
.Net Version: 4.5.2
OS: Windows10 64x

```
namespace jmattheis.lightinject
{
    class Program
    {
        static void Main(string[] args)
        {
            LightInject.ServiceContainer container = new LightInject.ServiceContainer();
            container.RegisterAssembly(typeof(Program).Assembly);
            container.TryGetInstance(typeof(IC)); // <-- throws InvalidOperationException
        }
    }

    interface IA { }
    interface IC { }

    class C : IC
    {
        public C(IA a) { }
    }
}
```
When trying to get the instance of an constructor injected parameter which doesn't have an implemented class the ``ServiceContainer#TryGetInstance`` throws an ``InvalidOperationException``.
The c#doc says 

> Returns:
>     The requested service instance if available, otherwise null.

So it should return null if it can't get the instance of an constructor injected parameter.

**Comment by seesharper** [comment]
Actually, IC is available and LightInject will try to resolve it, but fail because of the missing IA dependency

**Comment by jmattheis** [comment]
Yes, but still it should return null?

**Comment by seesharper** [comment]
It will return null if there the requested service is unavailable. In your case you have an implementation for IC. In such a scenario will try to fully resolve the dependencies and that why your are getting an error. Otherwise it would be very difficult to figure out why TryGetInstance returns null.

**Comment by seesharper** [comment]
That being said, I see know that this could use some TLC in the documentation

**Comment by jmattheis** [comment]
Okay, I understand this, then I would like to request a additional function which also return null when it fails to resolve a constructor injected parameter.

**Comment by seesharper** [comment]
You can easily create an extension method for this.
```
   public static class ContainerExtensions
    {
        public static T GetInstanceOrDefault<T>(this IServiceContainer container)
        {
            if (container.CanGetInstance(typeof (T), string.Empty))
            {
                return container.GetInstance<T>();
            }
            return default(T);
        }
    }
```

**Comment by jmattheis** [comment]
Your Extension method doesn't work ``ServiceContainer#CanGetInstance(Type, String)`` still returns ``true`` and not ``false`` therefore when calling ``ServiceContainer#GetInstance<T>()`` an ``InvalidOperationException`` is thrown.
