### ISSUE TITLE
Improve scoping mechanism

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject#314]
The implementation today consists of the following main components 
- Scope - The actual scope 
- ScopeManager - A manager class that manages scopes and keeps track of the current scope.
- IScopeManagerProvider 
  - PerThreadScopeManagerProvider (default)
  - PerLogicalCallContextScopeManagerProvider (async/await)
  - PerWebRequestScopeManagerProvider(LightInject.Web) 

So the IScopeManagerProvider is providing scope managers either per thread or per logical call context (AsyncLocal&lt;T&gt;)

In order to support resolving services directly off the scope (#291), we need to be able to set the current scope managed by the scope manager. By creating context specific scope managers (PerThreadScopeManager, PerLogicalCallContextScopeManager) we will not only simplify the current implementation, but we will also lay the foundation for supporting both parallell scopes(#112) and resolving services directly off the scope.

**Comment by dadhi** [comment]
Hello,

It is interesting to see how the impl / ideas are developed in sync for similar tools. I've played with idea for container implementing the "scope manager" abstraction to enable "parallel" / container-bound scopes.

**Comment by seesharper** [comment]
Absolutely. It is one of the really nice things about open source. We can learn from each other 👍

**Comment by seesharper** [comment]
On second thought, we start off with a subset of IServiceFactory. Not all methods are relevant for this

**Comment by seesharper** [comment]
Implemented all GetInstance convenience methods as extension methods so that we don't need to reimplement  all these method on the Scope class
