### ISSUE TITLE
Resolving PerRequestLifeTime-services failes when outside of request scope

### ISSUE THREAD

**Issue by vegar** [seesharper/LightInject#319]
Which is kind of obvious, I guess, but....

I have services I like to be unique within requests. 
But some times, those services is also used outside of the request scope, like during application startup.

E.g. a feature toggle service. The feature toggle context needs to be uniquely setup for each request to incorporate context from both signed in user and the request it self. But I also need to access the feature toggle service during application startup. 

Would it be possible to have a 'one-new-instance-for-each-request-and-a-short-lived-instance-for-each-use-outside-of-requests'-lifetime?

**Comment by seesharper** [comment]
You could use named services for this.
```
container.Register<IFoo, Foo>(new PerRequestLifetime())
container.Register<IFoo, Foo>("AnotherFoo")
```

**Comment by vegar** [comment]
So, when out of the normal lifetime scope, I would need to ask for the named service instead of the default service?

How will the container select the right one for constructor injections? Will it test and see if the scope is available and if not, it will use the named service (if it matches the parameter name) ?

**Comment by seesharper** [comment]
Normal constructor injection will pick the default registration meaning the one without a name. 

Where there is ambiguity it will try the parameter name as the service name

**Comment by vegar** [comment]
So in this case, it'll try the default one, which is with a `PerRequestLifeTime` scope, and it will fail, since the request is not available.

Without a 'forgiving' request-scope implementation, I can not see any other solution than factories?

**Comment by seesharper** [comment]
You could name both services like this 

```
    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.Register<IFoo, Foo>("Foo", new PerScopeLifetime());
            container.Register<IFoo, Foo>("AnotherFoo");
            container.Register<Bar>();

            var bar = container.GetInstance<Bar>();
        }
    }

    public class Bar
    {
        public Bar(IFoo anotherFoo)
        {
        }
    }


    public interface IFoo
    {
    }


    public class Foo : IFoo
    {
        
    }
```

That being said it might be better to have the feature toggle service as a singleton and inject function factories that retrieves the current user. 

If this is a Web API application you could inject a function that get the current HttpRequestMessage.

**Comment by vegar** [comment]
Relying on correctly typed parameter names is a little too risky... :-)

We'll have to look at this from a completely different angle.

It is for a Web API app, and the actual problem is having two mongo connections, one with logging and one without, and switching between them 'on will' based on a feature toggle stored in the database it self...

We have already solved this on another level, but it's still interesting to learn more about how the ioc container can be (ab)used.
