### ISSUE TITLE
Using GetInstance from within ICompositionRoot?

### ISSUE THREAD

**Issue by vector-man** [seesharper/LightInject#324]
What is the correct way of getting an instance from within ICompositionRoot?

    public class CompositionRoot : ICompositionRoot
    {
        public void Compose(IServiceRegistry serviceRegistry)
        {
          // Register some services up here:

          // Need to get instances of the registered service here:
        }
    }

I need to get the instances so that I can inject them into another service's constructor. Sorry if it is somewhere in the documentation, but I couldn't figure it out.

Edit: I'm thinking this might work, but not sure if there is a cleaner way:

    var service = serviceRegistry.AvailableServices.Where((x) => x.ServiceType  == typeof(ImageList)).First().Value as ImageList

**Comment by seesharper** [comment]
Show me a complete example of what you are trying to do and I will help you out :)

**Comment by mesakomarevich** [comment]
For those like myself that are trying to do something similar, you can do something like this in your Compose method:

```
public class CompositionRoot : ICompositionRoot
{
    public void Compose(IServiceRegistry serviceRegistry)
    {
        // Register some services up here:

        // Need to get instances of the registered service here:
        if (serviceRegistry is ServiceContainer container)
        {
            var service = container.GetInstance<TypeThatYouAreTotallySureCanBeResolvedHere>();
        }
    }
}
```
You must take into consideration that you can throw exceptions here if `TypeThatYouAreTotallySureCanBeResolvedHere` cannot, in fact, have all of it's constructor dependencies resolved.
