### ISSUE TITLE
LightInject 4.1.4 fails with LightInject.WebApi 1.1.0

### ISSUE THREAD

**Issue by geirsagberg** [seesharper/LightInject#330]
After upgrading to LightInject 4.1.4, I get the following error:

```
The given key was not present in the dictionary.

Description: An unhandled exception occurred during the execution of the current web request. Please review the stack trace for more information about the error and where it originated in the code. 

Exception Details: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

Source Error: 


Line 3748:            if (actualServiceType.GetTypeInfo().IsGenericType)
Line 3749:            {
Line 3750:                EnsureEmitMethodsForOpenGenericTypesAreCreated(actualServiceType);
Line 3751:            }
Line 3752:

Source File: C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs    Line: 3750 

Stack Trace: 


[KeyNotFoundException: The given key was not present in the dictionary.]
   System.Collections.Generic.Dictionary`2.get_Item(TKey key) +12465717
   LightInject.<>c__DisplayClass186_0.<CreateEmitMethodBasedOnClosedGenericServiceRequest>b__1(String parameterName) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:3750
   System.Linq.WhereSelectArrayIterator`2.MoveNext() +80
   System.Linq.Buffer`1..ctor(IEnumerable`1 source) +239
   System.Linq.Enumerable.ToArray(IEnumerable`1 source) +77
   LightInject.ServiceContainer.CreateEmitMethodBasedOnClosedGenericServiceRequest(Type closedGenericServiceType, String serviceName) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:3750
   LightInject.ServiceContainer.GetRegisteredEmitMethod(Type serviceType, String serviceName) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:3143
   LightInject.ServiceContainer.GetEmitMethod(Type serviceType, String serviceName) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:3072
   LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:3963
   LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:3939
   LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:2538
   LightInject.ServiceContainer.GetAllInstances(Type serviceType) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:2811
   LightInject.WebApi.LightInjectWebApiDependencyResolver.GetServices(Type serviceType) in C:\projects\lightinject-webapi\build\tmp\Net46\Binary\LightInject.WebApi\LightInject.WebApi.cs:145
   System.Web.Http.Services.DefaultServices.GetServices(Type serviceType) +114
   System.Web.Http.ServicesExtensions.GetServices(ServicesContainer services) +53
   LightInject.WebApiContainerExtensions.EnableWebApi(IServiceContainer serviceContainer, HttpConfiguration httpConfiguration) in C:\projects\lightinject-webapi\build\tmp\Net46\Binary\LightInject.WebApi\LightInject.WebApi.cs:57
```

Maybe LightInject.WebApi needs a new version to support 4.1.4?

**Comment by seesharper** [comment]
I did some work in 4.1.3 and 4.1.4 to improve working with partially closed generic types. Probably not related to Web API though. Could you provide some more information about the type being requested in this case?

**Comment by geirsagberg** [comment]
Seems it fails when attempting to call `CreateEmitMethodForEnumerableServiceServiceRequest` with service type `System.Collections.Generic.IEnumerable`1[[System.Web.Http.Filters.IFilterProvider, System.Web.Http, Version=5.2.3.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35]]`

**Comment by seesharper** [comment]
This is strange. I am not able to reproduce this on my side. Could I ask you to try to reproduce this error?

**Comment by geirsagberg** [comment]
Hmm I am not able to reproduce the error in a simple solution. I can unfortunately not share the code causing the problem. I will attempt to debug some more. Reverting to 4.1.2 solved the problem, so it seems to be related to the partially closed generic type changes.

**Comment by seesharper** [comment]
Thanks a lot. Does this happen at startup or during a request?

**Comment by geirsagberg** [comment]
It happens at startup, when calling `EnableWebApi`. My code looks something like this:

```
        public static void EnableWebApi(HttpConfiguration config, Assembly assembly)
        {
            WebContainer.RegisterApiControllers(assembly);
            WebContainer.EnablePerWebRequestScope();
            WebContainer.EnableWebApi(config);
        }
```

**Comment by seesharper** [comment]
Could it be related to generic filter attributes?

**Comment by geirsagberg** [comment]
I tried removing all registered filter attributes, but still get the same error. I will try to whittle away the registered services until it starts working, to get an idea of which service is causing trouble.

**Comment by seesharper** [comment]
Perfect, thanks a lot for your help. Appreciate it

**Comment by geirsagberg** [comment]
The offender was this class, ripped from EF Core:

```csharp
﻿using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;

namespace Ctrl.Data
{
    public class IncludableQueryable<TEntity, TProperty> : IIncludableQueryable<TEntity, TProperty>, IQueryable<TEntity>, IEnumerable<TEntity>, IEnumerable, IQueryable, IAsyncEnumerable<TEntity>
    {
        private readonly IQueryable<TEntity> _queryable;

        public Expression Expression
        {
            get
            {
                return this._queryable.Expression;
            }
        }

        public Type ElementType
        {
            get
            {
                return this._queryable.ElementType;
            }
        }

        public IQueryProvider Provider
        {
            get
            {
                return this._queryable.Provider;
            }
        }

        public IncludableQueryable(IQueryable<TEntity> queryable)
        {
            this._queryable = queryable;
        }

        public IEnumerator<TEntity> GetEnumerator()
        {
            return this._queryable.GetEnumerator();
        }

        IEnumerator IEnumerable.GetEnumerator()
        {
            return (IEnumerator)this.GetEnumerator();
        }

        IAsyncEnumerator<TEntity> IAsyncEnumerable<TEntity>.GetEnumerator()
        {
            return ((IAsyncEnumerable<TEntity>)this._queryable).GetEnumerator();
        }
    }

    /// <summary>
    ///     Supports queryable Include/ThenInclude chaining operators.
    /// </summary>
    /// <typeparam name="TEntity"> The entity type. </typeparam>
    /// <typeparam name="TProperty"> The property type. </typeparam>
    public interface IIncludableQueryable<out TEntity, out TProperty> : IQueryable<TEntity>, IEnumerable<TEntity>, IEnumerable, IQueryable
    {
    }
}
```

In `CreateEmitMethodBasedOnClosedGenericServiceRequest`, `GetOpenGenericServiceRegistration()` returned the registration for this type when `closedGenericServiceType` was `IEnumerable<IFilterProvider>`. 

`genericParameterNames` had two names, `TEntity` and `TProperty`, but `genericArgumentMap` only contained `TProperty`, so the following line caused an error:

    var typeArguments = genericParameterNames.Select(parameterName => genericArgumentMap[parameterName]).ToArray();

I tried to create a simple test to recreate this, but couldn't reproduce it. I removed the offending class (it wasn't actually in use),

**Comment by geirsagberg** [comment]
Hard to understand what the actual problem is here, maybe it is just mis-registration of services.

In either case, it would be helpful if there was a check to see if all the `genericParameterNames` were contained in the map, and if not, throw a reasonable exception.

**Comment by seesharper** [comment]
I agree, it should throw a more meaningful exception. I thought I had all possible open generic scenarios covered, but apparently there is still something missing from the puzzle.  What I don't understand here is what this has to do with filter providers. When you say EF Core, does this mean that this is a .Net Core app?

**Comment by seesharper** [comment]
I am pretty sure this is caused by some incorrect registration. I can easily reproduce a similar scenario so the exception surely needs some TLC :)

**Comment by geirsagberg** [comment]
It wasn't a .NET Core app, just a regular full framework web app using EF Core. What I think happened was this:

- `IncludableQueryable` is registered in the container via assembly scanning as implementation of all its interfaces, including `IEnumerable<TEntity>`
- `LightInject.WebApi` attempts to `GetAllServices<IFilterProvider>()`, which returns an `IEnumerable<IFilterProvider>`
- In `EnsureEmitMethodsForOpenGenericTypesAreCreated`, `GetOpenGenericServiceRegistration()` returns the `IncludableQueryable` as implementation of `IEnumerable<IFilterProvider>, because it matches the signature,` instead of whatever implementation LightInject uses to return multiple `IFilterProvider` service instances as `IEnumerable<IFilterProvider>`.

Not sure if it matters, but we have `EnableVariance = false`.

In any case, I agree the registration was incorrect. Feel free to close this issue :)

**Comment by geirsagberg** [comment]
Actually, I just got the same error again, in a different project. I have created a minimal solution that illustrates the problem:

https://github.com/geirsagberg/LightInject-issue-330

With the partially closed generic changes, assembly scanning seems less robust, as any registered implementation of IEnumerable<> might break `GetAllInstances`. Also, I noticed this method:

        private ServiceRegistration GetOpenGenericServiceRegistration(Type openGenericServiceType, string serviceName)
        {
            var services = GetAvailableServices(openGenericServiceType);
            if (services.Count == 0)
            {
                return null;
            }

            ServiceRegistration openGenericServiceRegistration;
            services.TryGetValue(serviceName, out openGenericServiceRegistration);
            if (openGenericServiceRegistration == null && string.IsNullOrEmpty(serviceName) && services.Count == 1)
            {
                return services.First().Value;
            }

            return openGenericServiceRegistration;
        }

It just grabs the first service, which might be any service which is registered for `IEnumerable<>`.

I guess I could work around the issue by doing something like

`RegisterAssembly(MyAssembly, (serviceType, implementationType) => serviceType != typeof(IEnumerable<>)`

But the issue still remains, `RegisterAssembly` is less robust than before the generic changes.

What are your thoughts on the issue?

**Comment by geirsagberg** [comment]
Alternatively, maybe partially closed generics could be an opt-in feature, specified via `ContainerOptions`? This way it would not break for everyone who won't use it.

**Comment by geirsagberg** [comment]
Here is a minimal test case that breaks:

```csharp
[Fact]
public void Can_GetAllInstances_when_service_with_two_generic_arguments_is_registered_for_IEnumerable()
{
    var container = new ServiceContainer();

    container.Register(typeof(IEnumerable<>), typeof(MyList<,>));

    container.GetAllInstances<IFoo>();
}

public class MyList<T1, T2> : List<T1> {}
```

**Comment by geirsagberg** [comment]
It could be fixed by ignoring all closed generic registrations of type `IEnumerable<>`... I made a PR #332. Not sure if this might have any unintended consequences?

**Comment by seesharper** [comment]
We got to make sure that we fix this in the right place. It might be the AssemblyScanner class that needs to be changed so that it does not register invalid registrations such as the one in your example.

**Comment by geirsagberg** [comment]
The problem is bigger than assembly scanning; any explicit registration of
IEnumerable might break GetAllInstances...

**Comment by seesharper** [comment]
I agree that the problem is not limited to the AssemblyScanner, but it should still be fixed so that we don't register "invalid" open generic types. 

In addition to this the CreateEmitMethodBasedOnClosedGenericServiceRequest method should be more robust when mapping generic arguments and throw a meaningful exception when we encounter "unclosable" generic types. 

We could also check this at registration time to ensure that we don't register invalid mappings between generic types

**Comment by geirsagberg** [comment]
I have updated the PR to throw a more meaningful exception, and ignore generic implementations with too many generic parameters when scanning an assembly. I think this is a better solution than my last fix, and shouldn't have any unforeseen consequences.

You can still explicitly perform invalid registrations, but at least now the error message should give you a hint what's wrong.

**Comment by seesharper** [comment]
Version 4.1.5 has just been published to the official NuGet feed that should solve this issue.
