### ISSUE TITLE
Inject services into DelegatingHandler

### ISSUE THREAD

**Issue by bsoulier** [seesharper/LightInject#335]
Hello there,

I am trying to set services within delegating handlers, how can I achieve this?

```
public class AvailabilityHandler : DelegatingHandler
{
    //TODO: manage service injection 
    public IConfigService ConfigService { private get; set; }

    protected override Task<HttpResponseMessage> SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
    {
        return base.SendAsync(request, cancellationToken);
    }
}
```
Simply defining services does not make them to be injected:

`container.Register<IConfigService, ConfigService>();`

Thanks, Ben

**Comment by seesharper** [comment]
Create a sample repo with what you are trying to do and we will PR into that repo

**Comment by bsoulier** [comment]
Sorry for the inconvenience, I managed to do to using sample provided on the[ LightInject website](http://www.lightinject.net/webapi/) (creating a static reference to the ServiceContainer created in `LightInjectConfig`)
