### ISSUE TITLE
constructor injection & lifetime

### ISSUE THREAD

**Issue by d18zj** [seesharper/LightInject#338]
I have a issue with constructor injection ,last verion and 4.1.5 have the same problem :

```
public interface IRoom
{
	string Name { get; }
	int Size { get; }
}

public class Room : IRoom
{
   
	public Room(string name,int size)
	{
		Name = name;
		Size = size;
	}

	public string Name { get; }

	public int Size { get; }

}
```
test code:
```
var container = CreateContainer();
container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();

//If Register without lifetime, will pass the test
container.Register<string, int, IRoom>((factory, name, size) => new Room(name, size));

Func<IServiceFactory, string, int, IRoom> func = (factory, name, size) =>
{
	return new Room(name, size);
};

container.Register(new ServiceRegistration
{
	ServiceType = typeof(IRoom),
	FactoryExpression = func,
	ServiceName = string.Empty,
	Lifetime = new PerScopeLifetime()//  if lifetime is null, it would pass the test
});

using (var scope = container.BeginScope())
{
	var arr = new object[] { "bedroom", 2 };
	var service = (IRoom)container.GetInstance(typeof(IRoom), arr);

	Assert.Equal(service.Name, "bedroom");
	Assert.Equal(service.Size, 2);
}
```
结果 的堆栈跟踪:	
在 DynamicMethod(Object[] )
   在 LightInject.ServiceContainer.<>c__DisplayClass136_0.<WrapAsFuncDelegate>b__0() 位置 H:\opensource\LightInject\LightInject\src\LightInject\LightInject.cs:行号 3026
   在 LightInject.PerScopeLifetime.CreateScopedInstance(Scope scope, Func`1 createInstance) 位置 H:\opensource\LightInject\LightInject\src\LightInject\LightInject.cs:行号 5874
   在 LightInject.PerScopeLifetime.<>c__DisplayClass1_0.<GetInstance>b__0(Scope s) 位置 H:\opensource\LightInject\LightInject\src\LightInject\LightInject.cs:行号 5859
   在 System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   在 LightInject.PerScopeLifetime.GetInstance(Func`1 createInstance, Scope scope) 位置 H:\opensource\LightInject\LightInject\src\LightInject\LightInject.cs:行号 5859
   在 DynamicMethod(Object[] )
   在 LightInject.ServiceContainer.GetInstance(Type serviceType, Object[] arguments) 位置 H:\opensource\LightInject\LightInject\src\LightInject\LightInject.cs:行号 2739
   在 LightInject.Tests.ConstructorInjectionParamsTest.Register_Params2_Test() 位置 H:\opensource\LightInject\LightInject\src\LightInject.Tests\ConstructorInjectionParamsTest.cs:行号 47
结果 的消息:	System.InvalidCastException : 无法将类型为“LightInject.PerLogicalCallContextScopeManager”的对象强制转换为类型“System.Object[]”。

**Comment by seesharper** [comment]
runtime values should not be dependencies
