### ISSUE TITLE
Making AssemblyLoader available in .NET Core

### ISSUE THREAD

**Issue by comkeendk** [seesharper/LightInject#340]
Any plans on making AssemblyLoader available for projects targeting .NET Core 1.0?
I'm asking because I would like to use the assembly scanning with a search pattern in a project.

As far as I know, the .NET Standard Library (v1.6 at least) should contain all the necessary methods to re-enable the functionality.

**Comment by seesharper** [comment]
LightInject 5.0.2 pushed to NuGet
