### ISSUE TITLE
MVC and Web api at same time

### ISSUE THREAD

**Issue by sandip12081992** [seesharper/LightInject#342]
Can I use LighInject MVC and webapi package at the same time. I'm working on a project which using both MVC and web api.
I'm using Unity IOC but it slow. I want to switch on LightInject. Please provide me a documentation of MVC with web api implementation.
Thanks

**Comment by vegar** [comment]
I'm not sure if I understand the problem, but I can't see that it should be a problem at all.

One small snippet out of our IOC configuration:

```
            _container = new ServiceContainer();
            _container.EnablePerWebRequestScope();
            _container.EnableWebApi(GlobalConfiguration.Configuration);
            _container.EnableMvc();
```
