### ISSUE TITLE
Question: Registering Instance

### ISSUE THREAD

**Issue by Mike-EEE** [seesharper/LightInject#345]
First off, awesome project. :)  Very easy to integrate.  However, I am having a problem with registering instances.  It seems to be going for explicit types and I would like to be more general. So:

```
class Instance : IInterface {}

var container = new ServiceContainer();
var instance = new Instance();
container.RegisterInstance(instance);
var service = container.TryGetInstance<IInterface>(); // null
```

Is there a way to have the container essentially do a `Type.IsAssignableFrom` lookup on the registered instances?

Thanks for any assistance and keep up the great work here. 👍

**Comment by seesharper** [comment]
Thanks for the kind words. Appreciate it. 

Try specifying the interface as the generic argument.

```csharp
var container = new ServiceContainer();
var instance = new Instance();
container.RegisterInstance<IInterface>(instance);
var resolvedInstance = container.TryGetInstance<IInterface>();
Debug.Assert(resolvedInstance != null);
```

**Comment by Mike-EEE** [comment]
And thank YOU for the quick reply. :)

Yes, the above works great.  However in this case I have a list of instances that are already created and assigned in an `object[]` array, so they get registered as `object`.

**Comment by seesharper** [comment]
I see. Let's try this with a extension method.

```csharp
public class MainClass
{
    public static void Main(string[] args)
    {
        object[] instances = new object[] {new Foo(), new Bar()};
        var container = new ServiceContainer();
        foreach (var instance in instances)
        {
            container.RegisterInstanceWithInterfaces(instance);    
        }

        var foo = container.TryGetInstance<IFoo>();
        var bar = container.TryGetInstance<IBar>();
        Debug.Assert(foo != null);
        Debug.Assert(bar != null);
    }      
}

public static class ContainerExtensions
{
    internal static void RegisterInstanceWithInterfaces(this IServiceRegistry registry, object instance)
    {
        var interfaces = instance.GetType().GetInterfaces();
        foreach (var type in interfaces)
        {
            registry.RegisterInstance(type, instance);
        }
    }
}

public interface IFoo { }
public class Foo : IFoo { }
public interface IBar { }
public class Bar : IBar{}
```

**Comment by Mike-EEE** [comment]
ah yes I was thinking of that but I didn't want to pollute the registrations with all the interfaces in case a type has a bunch of them.  I was curious if there was something already made around this and/or if you had a simple convention-based locator.  If not, no worries.  I will use what I have now (did a basic name check).  Thanks again for your assistance!

**Comment by seesharper** [comment]
You could filter this with a simple Func like this 

```csharp
public static class ContainerExtensions
{
    internal static void RegisterInstanceWithInterfaces(this IServiceRegistry registry, object instance, Func<Type, bool> shouldRegister)
    {
        var interfaces = instance.GetType().GetInterfaces();
        foreach (var type in interfaces)
        {
            if (shouldRegister(type))
            {
                registry.RegisterInstance(type, instance);
            }
            
        }
    }
}
```

And you are absolutely right, you should avoid container pollution :)
