### ISSUE TITLE
Question: Constructor Selection

### ISSUE THREAD

**Issue by Mike-EEE** [seesharper/LightInject#346]
Hi again, got another one for you. :) Currently it appears that the selection strategy used for constructors is greedy (e.g. selecting a constructor with 3 parameters rather than 2).  Is it possible to configure so that it selects the constructor with the least amount of parameters?

**Comment by seesharper** [comment]
```csharp
public class CustomConstructorSelector : IConstructorSelector
{
    public ConstructorInfo Execute(Type implementingType)
    {
        var constructors = implementingType.GetConstructors().OrderBy(c => c.GetParameters().Length);
        return constructors.First();
    }
}
```

usage

```csharp
container.ConstructorSelector = new CustomConstructorSelector();
```

**Comment by Mike-EEE** [comment]
Excellent!  Thank you.
