### ISSUE TITLE
Unable to cast object of type 'LightInject.ServiceContainer' to type 'System.Object[]'.

### ISSUE THREAD

**Issue by Mike-EEE** [seesharper/LightInject#347]
Looks like I've encountered an issue.  Perhaps you might be able to assist in showing me what I am doing wrong.

Given the following:

```
		[Fact]
		public void VerifySimple()
		{
			var container = new ServiceContainer();
			container.Register<DependencyOne>();
			container.Register<IDependencyOne, DependencyOne>();
			container.Register<IDependencyOne, ISimple>((provider, arg3) => new Simple(arg3));

			var one = container.GetInstance<IDependencyOne>();
			var two = container.GetInstance<ISimple>(); // throws
			
		}

		public interface IDependencyOne {}

		class DependencyOne : IDependencyOne {}

		public interface ISimple {}

		class Simple : ISimple
		{
			readonly IDependencyOne _dependency;

			public Simple(IDependencyOne dependency)
			{
				_dependency = dependency;
			}
		}
```

I am experiencing a throw at the line demarked by `// throws`.  Here is the exception details:

```
System.InvalidCastException occurred
  HResult=-2147467262
  Message=Unable to cast object of type 'LightInject.ServiceContainer' to type 'System.Object[]'.
  Source=LightInject
  StackTrace:
       at DynamicMethod(Object[] )
  InnerException: 
```

Is there a registration/configuration I am overlooking, perhaps?

**Comment by Mike-EEE** [comment]
Durp.  It appears that this is for factories, that's why.

So, `GetInstance<Func<IDependencyOne, ISimple>>()` works.  Looks like I got my wires crossed with Decorator.  Or just crossed in general. :)

**Comment by Mike-EEE** [comment]
FWIW, `RegisterConstructorDependency` was the magic I was looking for.  Gotta say I am very impressed with this library.  `Decorate` is especially sublime.  There's been very little friction and for the most part everything has behaved as expected. Very nice work here. 👍

**Comment by seesharper** [comment]
Thanks a lot for those kind words 👍
