### ISSUE TITLE
Support for registering multiple factories of the same type.

### ISSUE THREAD

**Issue by trbenning** [seesharper/LightInject#353]
I'm not sure if this is a bug, or just not supported, but I'm having trouble registering multiple named factories for the same interface. Here is my code:

    void Main()
    {
        var container = new ServiceContainer();
        container.Register<int, IMyInterface>((factory, value) => new MyClass1(value), "MyClass1");
        container.Register<int, IMyInterface>((factory, value) => new MyClass2(value), "MyClass2");
        var instances = container.GetAllInstances<Func<int, IMyInterface>>();
        Console.WriteLine($"Found {instances.Count()} instances.");
    }
    
    interface IMyInterface
    {
        int MyInt { get; }
    }
    
    class MyClass1 : IMyInterface
    {
        public int MyInt { get; }
        public MyClass1(int myInt)
        {
            MyInt = myInt;
        }
    }
    
    class MyClass2 : IMyInterface
    {
        public int MyInt { get; }
        public MyClass2(int myInt)
        {
            MyInt = myInt;
        }
    }

Is this supported?

**Comment by seesharper** [comment]
Try this instead. 

```csharp
   class Program
    {
        static void Main()
        {
            var container = new ServiceContainer();
            container.Register<Func<int, IMyInterface>>(factory => (i => new MyClass1(i)), "MyClass1");
            container.Register<Func<int, IMyInterface>>(factory => (i => new MyClass2(i)), "MyClass2");
            var factories = container.GetAllInstances<Func<int, IMyInterface>>();
            var instances = factories.Select(f => f(42));
            

            Console.WriteLine($"Found {instances.Count()} instances.");
            Console.ReadKey();
        }

        interface IMyInterface
        {
            int MyInt { get; }
        }

        class MyClass1 : IMyInterface
        {
            public int MyInt { get; }
            public MyClass1(int myInt)
            {
                MyInt = myInt;
            }
        }

        class MyClass2 : IMyInterface
        {
            public int MyInt { get; }
            public MyClass2(int myInt)
            {
                MyInt = myInt;
            }
        }
    }
´``
