### ISSUE TITLE
First autofactory sample is not working

### ISSUE THREAD

**Issue by UmairB** [seesharper/LightInject#356]
class Program
    {
        static void Main(string[] args)
        {
            using (var container = new ServiceContainer())
            {
                container.Register<IFoo, Foo>();
                container.RegisterAutoFactory<IFooFactory>();

                var factory = container.GetInstance<IFooFactory>();
                var foo = factory.GetFoo();
            }
        }
    }

    public interface IFoo { }

    public class Foo : IFoo { }

    public interface IFooFactory
    {
        IFoo GetFoo();
    }

Is throwing an exception "unable to resolve type" when trying to resolve `IFooFactory`. Tried on .net core 1.1 and .net46. LightInject.AutoFactory v2.0.0.

**Comment by seesharper** [comment]
think you forgot this line 
```
container.EnableAutoFactories();
```

so it should be 

```
class Program
{
    static void Main(string[] args)
    {
        using (var container = new ServiceContainer())
        {
            container.Register<IFoo, Foo>();
            container.EnableAutoFactories();
            container.RegisterAutoFactory<IFooFactory>();

            var factory = container.GetInstance<IFooFactory>();
            var foo = factory.GetFoo();
        }
    }
}

public interface IFoo { }

public class Foo : IFoo { }

public interface IFooFactory
{
    IFoo GetFoo();
}
```

**Comment by UmairB** [comment]
Ah! Might want to update http://www.lightinject.net/autofactory/ to show this :)
