### ISSUE TITLE
ICompositionRoot only works in .net framework, not .net core

### ISSUE THREAD

**Issue by philippe-lavoie** [seesharper/LightInject#358]
My library is a .net standard 1.6 library and it looks like that it works when used from a .net 4.7 framework code, but not a .net core 1.1 one. Anything else I need to get 

`container.RegisterAssembly("Framework.*.dll");`

to properly call the compose method below ?

`[assembly: CompositionRootType(typeof(Framework.Rabbit.DependencyRegistry))]

namespace Framework.Rabbit
{
    
    public class DependencyRegistry : ICompositionRoot
    {
        public void Compose(IServiceRegistry serviceRegistry)
        {
            serviceRegistry.Register<IMessaging, CoreMessaging>();
            serviceRegistry.Register<IMessageBroker, CoreMessageBroker>();
        }
    }
}`

**Comment by seesharper** [comment]
I'm gonna need a full repro to investigate. Create a repo here on GitHub that I can PR into

**Comment by philippe-lavoie** [comment]
Not sure why, but if I replace your Register implementation with

`
            var dllFiles = Directory.GetFiles(AppContext.BaseDirectory, "Framework.*.dll");
            foreach(var dllFile in dllFiles)
            {
                var info = new FileInfo(dllFile);
                var name = info.Name.Substring(0, info.Name.Length - info.Extension.Length);
                var assembly = Assembly.Load(new AssemblyName(name));
                container.RegisterAssembly(assembly);
            }
`

Then it works, not sure why the use of AppContext.BasePath makes a big difference, but now it works, so I'm a happy coder.

My code structure if you still want to reproduce is the interface are defined in current assembly as .net standard 1.6 and the implementation is in another DLL. The register links the interface from the first assembly with the concrete implementations in itself.

**Comment by philippe-lavoie** [comment]
Maybe I shouldn't close this yet ?
