### ISSUE TITLE
Open generics prioritized over closed generics

### ISSUE THREAD

**Issue by vegar** [seesharper/LightInject#359]
**.Net Framework 4.6**
**LightInject 5.0.3**

Take a look at the following console application:

```
    interface IMyInterface<T>  { ...   }
    class MyGenericImplementation<T> : IMyInterface<T>{ ... }
    class MyImplementation: IMyInterface<string> { ...   }

    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.RegisterAssembly(Assembly.GetExecutingAssembly(), (serviceType, implementationType) => serviceType.IsSubclassOfRawGeneric(typeof(IMyInterface<>)));

            var services = container.AvailableServices.Select(s => $"{s.ServiceType} - {s.ImplementingType}");
            Console.WriteLine(string.Join("\n\r", services));

            var strImp = container.GetInstance<IMyInterface<string>>();
            Console.WriteLine($"GetInstance<IMyInterface<string>>: {strImp.GetType().Name}");

            Console.ReadKey();
        }
    }
```
The output of this application is as follow:

> ConsoleApplication3.IMyInterface'1[T] - ConsoleApplication3.MyGenericImplementation'1[T]
> ConsoleApplication3.IMyInterface'1[System.String] - ConsoleApplication3.MyImplementation
> GetInstance<IMyInterface< string >>: MyGenericImplementation'1

I would expect `GetInstance<IMyInterface<string>>()` to be resolve to the 'most type-specific' service, which is `MyImplementation`.

In fact - if I take out the `RegisterAssembly`, and register the types manually, things change:

```
    interface IMyInterface<T>  { ...   }
    class MyGenericImplementation<T> : IMyInterface<T>{ ... }
    class MyImplementation: IMyInterface<string> { ...   }

    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.Register<IMyInterface<string>, MyImplementation>();
            container.Register(typeof(IMyInterface<>), typeof(MyGenericImplementation<>));

            var services = container.AvailableServices.Select(s => $"{s.ServiceType} - {s.ImplementingType}");
            Console.WriteLine(string.Join("\n\r", services));

            var strImp = container.GetInstance<IMyInterface<string>>();
            Console.WriteLine($"GetInstance<IMyInterface<string>>: {strImp.GetType().Name}");

            Console.ReadKey();
        }
    }
```
Now the output of the application is

> ConsoleApplication3.IMyInterface'1[T] - ConsoleApplication3.MyGenericImplementation'1[T]
> ConsoleApplication3.IMyInterface'1[System.String] - ConsoleApplication3.MyImplementation
> GetInstance<IMyInterface< string >>: MyImplementation

When enumerating `AvailableServices`, I'm not able to see any difference between the services registered through `RegisterAssembly` vs `Register`, yet there has to be some difference in the internals.

When stepping through the source, I see that for the explicit `Register`-version, `GetRegisteredEmitMethod` uses an emitter returned from `registrations.TryGetValue( )`, while in the `RegisterAssembly`-version, it uses an emitter returned from `CreateEmitMethodBasedOnClosedGenericServiceRequest`. I have no idea how this stuff works, though, so I cannot tell the difference ;-)

Full source for example available here: https://gist.github.com/vegar/b42f347907d326fbae83f6bf55156282

**Comment by seesharper** [comment]
Ah, man those generics again :) Looking into it right now. Thanks a lot for really good repro 👍

**Comment by seesharper** [comment]
Confirmed to be a bug and is related to named services. When you are doing manual registration there is no service name When scanning assemblies, the service name is set to the name of the implementing type. 
When you ask for the default service (service without a name), LightInject will resolve a named service as the default service if there is only one named service registered for a given service types. 

The following code will also reproduce the bug 
```
container.Register(typeof(IMyInterface<>), typeof(MyGenericImplementation<>), "MyGenericImplementation");
container.Register<IMyInterface<string>, MyImplementation>("MyImplementation");
```
