### ISSUE TITLE
Open generics constructor parameters

### ISSUE THREAD

**Issue by pavlalexandr** [seesharper/LightInject#362]
Hello,
Is it possible to register open generic services which have parameters in constructor? Can't find the way to do this

**Comment by seesharper** [comment]
Open generic services can have dependencies just like any other service. It is just not possible to provide a factory delegate for it since the actual type is not known until the service is resolved. 

```
    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.Register<Bar>();
            container.Register(typeof(Foo<>));

            var foo = container.GetInstance<Foo<string>>();
        }
    }


    public class Foo<T>
    {
        public Foo(Bar bar)
        {
            
        }
    }

    public class Bar
    {

    }
```
