### ISSUE TITLE
Way to disable property injection?

### ISSUE THREAD

**Issue by kondotak** [seesharper/LightInject#370]
I recently realized that lightInject is doing property injection by default.  I didn't realize it was on by default when writing code and had a very difficult to track bug where there was unintended object instantiation (sql connections).  Is there a way to disable property injection across the entire container?

**Comment by seesharper** [comment]
https://github.com/seesharper/LightInject/blob/master/src/LightInject/LightInject.cs#L1829

**Comment by kondotak** [comment]
Thanks!  I found the containerOptions, but I was using 4.x... looks like I
just needed to get latest.  Thanks again!
