### ISSUE TITLE
Clone method

### ISSUE THREAD

**Issue by reinaldoarrosi** [seesharper/LightInject#372]
Issue #251 added a clone method to the container, but this method was removed in commit 7e54376a7f4c2ed8798124585d6600011a76e4c1 without explanation of why it was being removed.

Can we bring back this method? It's useful in multi-tenant scenarios where all tenants share a common set of services but also need some specific, per-tenant, registrations.

**Comment by yodasad** [comment]
+1

**Comment by seesharper** [comment]
LightInject 5.1.0 will reintroduce this method 👍
