### ISSUE TITLE
Cannot register two different types with same name when assembly scanning with predicate

### ISSUE THREAD

**Issue by geirsagberg** [seesharper/LightInject#373]
I am using LightInject to register mapping profiles for AutoMapper. I have code like the following

```csharp
public class Foo {
  ...
  public class MappingProfile : Profile {
    ...
  }
}

public class Bar {
  ...
  public class MappingProfile : Profile {
     ...
  }
}

public class TestBase {
  public TestBase() {
    var container = new ServiceContainer();
    container.RegisterAssembly(typeof(Foo).Assembly, (serviceType, _) => serviceType == typeof(Profile));
    var profiles = container.GetAllInstances<Profile>();
  }
}
```

When I run the code and examine `profiles`, only `Foo.MappingProfile` is present.

If I rename `Bar.MappingProfile` to `BarMappingProfile`, both services are present.

**Comment by seesharper** [comment]
This is probably because the implementing type name is used as the service name. We should probably use the full name here.

**Comment by geirsagberg** [comment]
Made a PR with test: https://github.com/seesharper/LightInject/pull/374
