### ISSUE TITLE
LightInject and .NET CORE 2 throw an exception in AddMVC call

### ISSUE THREAD

**Issue by hdesouky** [seesharper/LightInject#378]
Hello All,

I tried to work with LightInject using .NET CORE 2.0 MVC website

The call to AddMvc in the Configure method fails with circular dependency.

Downgrading to CORE 1.1 everything worked as expected 

I am using LigthInject 5.0.3 and LightInject.Microsoft.DepndencyInjection 2.0.2

**Comment by seesharper** [comment]
Try bumping your dependencies to LightInject 5.1.0 AND LightInject.Microsoft.DependencyInjection to 2.0.3.
In addition you need to disable propertyinjection (ContainerOptions).

PS: The docs are being updated to target .Net Core 2.0

**Comment by hdesouky** [comment]
I already tried the latest version, but didn't disable the propertyinjection.

I will give it a try

**Comment by seesharper** [comment]
Did disabling property injection work out for you?

**Comment by maximrub** [comment]
Had the same problem in .NET core 2 webApi.
disabling property injection did the trick
ServiceContainer container =
                new ServiceContainer(new ContainerOptions() { EnablePropertyInjection = false });

**Comment by seesharper** [comment]
https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/issues/16

**Comment by hdesouky** [comment]
Interesting it is worked when disabling property injections
However i have large codebase i am migrating from EntLib Unity DI where injection is done to properties through the [Dependency] attribute

Any other workaround to make it work with .NET core 2?

**Comment by seesharper** [comment]
The reason that we disable property injection is mainly because the default container is ASP.NET does not support it and it is very likely to introduce unwanted side effects like we just saw with the recursive graph detected when property injection was enabled. 

It is however, possible to implement a custom IPropertyDependencySelector that lets you decide what properties should be injected. 
```
  /// <summary>
    /// Represents a class that is responsible for selecting the property dependencies for a given <see cref="Type"/>.
    /// </summary>
    public interface IPropertyDependencySelector
    {
        /// <summary>
        /// Selects the property dependencies for the given <paramref name="type"/>.
        /// </summary>
        /// <param name="type">The <see cref="Type"/> for which to select the property dependencies.</param>
        /// <returns>A list of <see cref="PropertyDependency"/> instances that represents the property
        /// dependencies for the given <paramref name="type"/>.</returns>
        IEnumerable<PropertyDependency> Execute(Type type);
    }
```
You can use this to check for the Dependency attribute

**Comment by hdesouky** [comment]
Could you please provide an example for the implementation of IPropertyDependencySelector?

**Comment by seesharper** [comment]
Take a look here 
https://github.com/seesharper/LightInject.Annotation/blob/master/src/LightInject.Annotation/LightInject.Annotation.cs

You should be able to customize this to your needs

**Comment by hdesouky** [comment]
Everything sorted out, i implemented my own property selector and everything is OK now :)

**Comment by seesharper** [comment]
Good stuff 👍
