### ISSUE TITLE
LogFactory not called

### ISSUE THREAD

**Issue by hdesouky** [seesharper/LightInject#379]
I configured the container to log using my logfactory through the container options, however the code is never called.

Below is my configuration:
            var containerOptions = new ContainerOptions();
            containerOptions.LogFactory = (type) => logEntry =>
            {
                Console.WriteLine(logEntry.Message);
                System.Diagnostics.Debug.WriteLine(logEntry.Message);
                System.Diagnostics.Trace.WriteLine(logEntry.Message);
            };

            var container = new ServiceContainer(containerOptions);

Any thoughts?

**Comment by seesharper** [comment]
We don't do very much logging from within LightInject. We warn about services being registered after the first GetInstance, but that is pretty much it.

**Comment by hdesouky** [comment]
i see
I +1 if the library can log when a new service registered, instance resolution fails, etc.

**Comment by seesharper** [comment]
You can at any time get to all registrations through the AvailableServices property.

If resolution fails, an exception will be thrown
