### ISSUE TITLE
PerWebRequestScopeManagerProvider Problem

### ISSUE THREAD

**Issue by t11omas** [seesharper/LightInject#383]
Hi,

At this point I am just asking a question rather than raise an issue as I don't know if this is by design.

When using PerWebRequestScopeManagerProvider in my MVC app and then taking advantage of await/async and  the executing is passed to another thread then I get the following exception:

Object is null exception:
   at LightInject.Web.PerWebRequestScopeManager.GetOrAddScope() in C:\projects\lightinject-web\build\tmp\Net46\Binary\LightInject.Web\LightInject.Web.cs:line 148
   at LightInject.Web.PerWebRequestScopeManager.get_CurrentScope() in C:\projects\lightinject-web\build\tmp\Net46\Binary\LightInject.Web\LightInject.Web.cs:line 129
   at DynamicMethod(Object[] )
   at LightInject.ServiceContainer.GetInstance(Type serviceType) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:line 2720
   at LightInject.ServiceFactoryExtensions.GetInstance[TService](IServiceFactory factory) in C:\projects\lightinject\build\tmp\Net46\Binary\LightInject\LightInject.cs:line 1074
   at LightInjectIssue.Controllers.HomeController.<>c.<SomeIoBoundWork>b__3_0() in C:\Users\thomaande\Source\Repos\LightInjectIssue\LightInjectIssue\Controllers\HomeController.cs:line 41
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

This is because The scope is stored in the HttpContext.Items which is threadstatic.

Any thoughts/suggestions on this?

Cheers,
Thomas

**Comment by seesharper** [comment]
Hi Thomas. If you create a simple repro and push it up to github, I will help you out 👍

**Comment by t11omas** [comment]
[LightInjectIssue.zip](https://github.com/seesharper/LightInject/files/1308239/LightInjectIssue.zip)

I have attached a simple example.  Its just a box standard MVC template, but a couple of lines of code to show the problem.

I appreciate your help

**Comment by seesharper** [comment]
I think that Task.Run is what causes this to fail. 
https://stackoverflow.com/questions/13748267/using-httpcontext-in-async-task

Try modifying the method to use ` Task.Delay` . That will also cause the resolving to be executed on another thread. The difference is that if "flows" the logical thread context that HttpContext.Current depends on. You should avoid Task.Run on the server since that schedules the task on the thread pool and threads are a very limited resource on a server. 

```
        public async Task SomeIoBoundWork()
        {
            Debug.WriteLine($"Thread before resolving {Thread.CurrentThread.ManagedThreadId}");
            await Task.Delay(100);
            Debug.WriteLine($"Thread during resolving {Thread.CurrentThread.ManagedThreadId}");            
            var resolvedClass = MvcApplication.Container.GetInstance<ClassPerScope>();                
        }
```

**Comment by t11omas** [comment]
Hi,

Thanks for your reply, Task.Run isn't used on my code, it was merely use in this example to force the execution on another thread.

I updated the example as you suggested and that works as long as the calling controller has ConfigureAwait(true) as soon as I use ConfigureAwait(false) it throws the same exception.  I would prefer not to have the overhead of marshalling between threads

`
        public async Task<ActionResult> Index()
        {
            await SomeIoBoundWork().ConfigureAwait(false);
            await SomeIoBoundWork().ConfigureAwait(false);
            await SomeIoBoundWork().ConfigureAwait(false);

            return View();
        }`

Any thoughts?

**Comment by seesharper** [comment]
I see that HttpContext.Current is null so next is to figure out why :)

**Comment by seesharper** [comment]
https://stackoverflow.com/questions/31389119/httpcontext-current-is-null-after-task-run

**Comment by seesharper** [comment]
Let's try using the PerLogicalThreadScopeManager

``` 
   public class MvcApplication : System.Web.HttpApplication
    {
        public static ServiceContainer Container;

        protected void Application_BeginRequest()
        {
            Container.BeginScope();
        }

        protected void Application_EndReguest()
        {
            Container.ScopeManagerProvider.GetScopeManager(Container).CurrentScope.Dispose();
        }

        protected void Application_Start()
        {
            Container = new ServiceContainer();
            Container.RegisterControllers();
            Container.Register<ClassPerScope>(new PerScopeLifetime());

            Container.EnableMvc();
            Container.ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider();
            AreaRegistration.RegisterAllAreas();
            FilterConfig.RegisterGlobalFilters(GlobalFilters.Filters);
            RouteConfig.RegisterRoutes(RouteTable.Routes);
            BundleConfig.RegisterBundles(BundleTable.Bundles);
        }
    }

    public class ClassPerScope
    {
        
    }
``` 

On a side note, if this a green field project, I would strongly recommend using AspNetCore instead where dependency injection is a first class citizen 👍 You can still target net461.

**Comment by t11omas** [comment]
Hi,

Thank you for your reply.  That worked for me.  I know my colleague also found this useful.  
 
Cheers,
Thomas

**Comment by seesharper** [comment]
Nice 👍
