### ISSUE TITLE
A question about disposing of IDisposable objects

### ISSUE THREAD

**Issue by yodasad** [seesharper/LightInject#384]
Assume we have the following 
````csharp
public class Foo : IDisposable
{
    private Bar bar;
    public Foo(Bar bar)
    {
        this.bar = bar;
    }

    public void Dispose()
    {
         this.bar.Dispose();
    }
}

public class Bar: IDisposable
{
    public void Dispose()
    {
    }
}

var container = new ServiceContainer();
container.Register<Bar>(new PerScopeLifetime());
container.Register<Foo>(new PerScopeLifetime());
using(container.BeginScope())
{
    container.TryGetInstance(typeof(Foo));
}
````
Is it right that the Bar instance will be disposed only once (when Foo is disposed) and it will not be disposed when the current scope is disposed?

**Comment by seesharper** [comment]
Bar will be disposed by the container when the scope ends. Simple rule applies here. If you create it, you destroy it. In this case, the container created both instances and the container destroys (disposes) them.

**Comment by seesharper** [comment]
And you don't need to manually dispose `bar`

**Comment by yodasad** [comment]
Thank you!

**Comment by seesharper** [comment]
No problem 👍
