### ISSUE TITLE
asp.net core 2.0 app: System.InvalidOperationException: Unable to resolve type: System.Boolean 

### ISSUE THREAD

**Issue by jesuslpm** [seesharper/LightInject#385]
Steps to reproduce:

- Create an empty asp.net core 2.0 app in Visual Studio 2017
- Install LightInject.Microsoft.DependencyInjection NuGet package
- Change ConfigureService method on Startup.cs:

```
public IServiceProvider ConfigureServices(IServiceCollection services)
{
    var containerOptions = new ContainerOptions { EnablePropertyInjection = false };
    var container = new ServiceContainer(containerOptions);
    services.AddMvc();
    return container.CreateServiceProvider(services);
}
```

- Press F5 to start debuging. You get System.AggregatedException on Program.BuildWebHost. The inner exception is the following:

> **System.InvalidOperationException**: Unable to resolve type: System.Boolean, service name: 
>    at LightInject.ServiceContainer.CreateDelegate(Type serviceType, String serviceName, Boolean throwError)
>    at LightInject.ServiceContainer.CreateDefaultDelegate(Type serviceType, Boolean throwError)
>    at LightInject.ServiceContainer.GetInstance(Type serviceType, Object[] arguments)
>    at LightInject.ServiceFactoryExtensions.GetInstance[T1,T2,TService](IServiceFactory factory, T1 arg1, T2 arg2)
>    at Microsoft.Extensions.Logging.Debug.DebugLogger.IsEnabled(LogLevel logLevel)
>    at Microsoft.Extensions.Logging.Debug.DebugLogger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
>    at Microsoft.Extensions.Logging.Logger.Log[TState](LogLevel logLevel, EventId eventId, TState state, Exception exception, Func`3 formatter)
>

**Comment by seesharper** [comment]
Try bumping to the LightInject 5.1.0

**Comment by jesuslpm** [comment]
Thanks! It works!
