### ISSUE TITLE
HttpContext.current is null when creating scope in LightInject.web

### ISSUE THREAD

**Issue by karunagoyal** [seesharper/LightInject#388]
Hi,
First of all thank you so much for valuable lib. I recently moved to LightInject and running into the issue while creating scope from test project. I am writing integration test as suggested on this post:

https://blogs.msdn.microsoft.com/youssefm/2013/01/28/writing-tests-for-an-asp-net-web-api-service/

I am able to register the all the services without any issue however when the call goes to GetScopeManager() method in light inject, there is no httpcontext. Though I have valid httprequestmessage which I am passing from my test.

Can you suggest how can I begin the scope manually or resolve the issue?

THanks.

**Comment by karunagoyal** [comment]
has anybody faced this issue?

**Comment by seesharper** [comment]
Could it be related to #386 ?

**Comment by karunagoyal** [comment]
Thanks for response. It works perfectly fine when making api call from browser using swagger. I am using webapi2. 
The issue happens from integration tests. I am following the link as I mentioned in my previous post
https://blogs.msdn.microsoft.com/youssefm/2013/01/28/writing-tests-for-an-asp-net-web-api-service/

for end to end testing(usinf in memory http server). Thats where it tries to look for scopemanager in httpcontext.current which is null.
I am not sure of the solution.
Thanks

**Comment by karunagoyal** [comment]
This is the issue I mentioned

**Comment by seesharper** [comment]
I am going to need a small repro of this. Create a the simplest example you can that put it up on GitHub. We will the PR a solution to you

**Comment by karunagoyal** [comment]
Sure. Let me get it to you by eod
