### ISSUE TITLE
RegisterAssembly with search pattern no more available?

### ISSUE THREAD

**Issue by leorjbrz** [seesharper/LightInject#389]
I updated the version from 5.0.3 to 5.1.0 and is not possible to scan assembly files based on a search pattern, like the doc:

`container.RegisterAssembly("SomeAssemblyName*.dll");`

I used to register the assemblies using my pattern "Company.*.dll", and got an error after updating the package.
No overload accepting only a string as a parameter?

Thanks!

**Comment by seesharper** [comment]
What kind of app is it. Target framework?
