### ISSUE TITLE
LightINject.source latest code not compiling

### ISSUE THREAD

**Issue by karunagoyal** [seesharper/LightInject#390]
I took the latest source code of light inject  and it is not compiling. Intilially it says CreateDynamicMethod is not defined. Once I declare the symbols in project properties, it gives lot of build errors about duplicate methods and classes.

**Comment by seesharper** [comment]
What kind of application is this? Is it a .Net Core app?

**Comment by kgoyal1** [comment]
It is web api2.

**Comment by seesharper** [comment]
So it is a full framework app? Net461?

**Comment by kgoyal1** [comment]
It is targeting .net framework 4.5.2

**Comment by seesharper** [comment]
Okay, did you pull in LightInject.Source through NuGet or did you just copy LightInject.cs from GitGub?

**Comment by kgoyal1** [comment]
I tried both and getting same error.

**Comment by seesharper** [comment]
Two ways to solve this
Either you can put `#define NET452` at the first line in `LightInject.cs` or you can define a compiler directive like this

![image](https://user-images.githubusercontent.com/1034073/32018745-1e45e12e-b9cb-11e7-805c-aaac401ee2d9.png)

**Comment by kgoyal1** [comment]
It works. Thanks much.

**Comment by seesharper** [comment]
No problem :)

**Comment by kgoyal1** [comment]
I am facing another issue when running in memory integration test

**Comment by seesharper** [comment]
#388 ?

**Comment by kgoyal1** [comment]
Issue # 388
Yes

**Comment by seesharper** [comment]
We take from there

**Comment by kgoyal1** [comment]
Sounds good.
