### ISSUE TITLE
Lightinject.mocking not compiling after taking latest of light inject source code

### ISSUE THREAD

**Issue by karunagoyal** [seesharper/LightInject#394]
I updated lightinject source code to latest version. I took the code base for lightinject.mocking as well. After that it is not compiling. Errors are as below:
1.ServiceContainer' does not contain a definition for 'Invalidate' and no extension method 'Invalidate' accepting a first argument of type 'ServiceContainer' could be found
2.ServiceRegistration' does not contain a definition for 'IsReadOnly' and no extension method 'IsReadOnly' accepting a first argument of type 'ServiceRegistration' could be found
3.Cannot implicitly convert type 'System.Linq.Expressions.Expression<System.Func<EPPS.LightInject.IServiceFactory, TService>>' to 'System.Delegate'	EPPS.LightInject

**Comment by karunagoyal** [comment]
Hi @seesharper 
Did you get a chance to look into it?
Thanks
Karuna

**Comment by seesharper** [comment]
Hi and sorry for the late reply. 
`LightInject.Mocking`has been deprecated a long time ago.

You are not going to need it. LightInject supports overwriting existing services as long as it is done before the first service request.

**Comment by karunagoyal** [comment]
Thanks @seesharper
