### ISSUE TITLE
serviceContainer.Clone() not working 

### ISSUE THREAD

**Issue by raizam** [seesharper/LightInject#396]
I'm using the Clone method, expecting a duplicate of the container state, but this is not working at all.

```csharp
using ConsoleApp1.LightInject;
using System;

namespace ConsoleApp1
{
    class Program
    {
        public class Class1
        {

        }

        public class Class2
        {

        }

        public class Class3
        {

        }

        public static void Main()
        {
            ServiceContainer container = new ServiceContainer();
            container.Register<Class1>();
            container.Register<Class2>();
            container.GetInstance<Class1>();

            container = container.Clone();
            container.Register<Class3>();

            container.GetInstance<Class2>(); //Error1
            container.GetInstance<Class3>();  //Error2

            Console.ReadKey();
        }
    }
}

```

Error 1 : NullReferenceException on AssemblyScanner https://github.com/seesharper/LightInject/blob/c05cae17a952a7c0d479a0520b7cbf494183f536/src/LightInject/LightInject.cs#L3157 

Error 2 : NullReferenceException on methodSkeletonfactory https://github.com/seesharper/LightInject/blob/c05cae17a952a7c0d479a0520b7cbf494183f536/src/LightInject/LightInject.cs#L3119

**Comment by denispakizh** [comment]
same issue. Clone method is not functional
