### ISSUE TITLE
Access information about resolved service dependencies

### ISSUE THREAD

**Issue by ilyazolotarov** [seesharper/LightInject#397]
Hi Bernhard.

Imagine a scenario:
We have `public interface ICacheable {
   void Refresh();
   int RefreshOrder {get;}
}` and `internal interface IGlobalCache {
   void AddCacheable(ICachable item);
   void RefreshAll();
}` as part of framework infrastructure. Implementation of IGlobalCache keep WeakReference on all ICacheable services passed to `IGlobalCache.AddCacheable` which is invoked during object post-processing, somethig like this `IServiceRegistry.Initialize(r => typeof(ICacheable).IsAssignableFrom(r.ServiceType), (f, obj) => f.GetInstance<IGlobalCache>().AddCacheable((ICacheable)obj))`.
The problem is about `ICacheable.RefreshOrder`. IGlobalCache relies on this property to determine in which order invoke `ICacheable.Refresh` method during RefreshAll execution in case ICacheable instance depends on other ICacheable services. So customer of ICacheable interface should provide RefreshOrder value (for instance `RefreshOrder => Math.Max(cachableDependency1.RefreshOrder, cachableDependency2.RefreshOrder) + 1`. I know, a more transparent contract is possible:
`public interface ICacheable {
   void Refresh();
   IReadonlyCollection<ICacheable> Dependencies {get;}
}`. But the problem remains that customer should know which dependencies of his ICacheable implementation also implements ICacheable. Which may not always be the case. For instance there may exist some abstract dependency which doesn't expose ICacheable  interface directly, but concrete injected implementation does. So the idea is grab somehow concrete  injected dependencies and build dependency graph to resolve correct refresh order. I think about overriding ConstructorDependencySelector/PropertyDependencySelector and make some dependency analysis in place. But again, we still doesn't know concrete type of dependency resolved in runtime. Is there any possibility to intercept somehow service instantiation in container and access the information about service dependencies. Could this be a kind of feature? Not that I ask you to implement it, rather I wonder if  I can create pull request in future. Of course if it is at least possible or does not contradict with **Light** part of your library name. Or maybe you have any suggestions how to resolve this problem nicely?

**Comment by seesharper** [comment]
Would love to help you out. 
Here's what I'm thinking. Create a small repro of this in the form of a console app that contains a minimal example of what you are trying to do. Put it up on Github and we can take it from there. Sounds okay?

**Comment by ilyazolotarov** [comment]
Thank you for your prompt response.
https://github.com/ilyazolotarov/lightinject_example
