### ISSUE TITLE
Recommended way of implementing Custom lifetime using TTL logic?

### ISSUE THREAD

**Issue by MedAnd** [seesharper/LightInject#401]
Is there a recommended way of implementing Custom lifetime using TTL logic? 

For example I would like an object to be created as PerContainerLifetime, the same instance shared among threads, but when the instance's Time To Live (TTL) expires, it's removed and another instance is created, registered and returned to new callers instead... similar to how .Net Core IMemoryCache works?

**Comment by VictorTomaili** [comment]
http://www.lightinject.net/#custom-lifetime

You already can create your own lifetime

**Comment by MedAnd** [comment]
Prior to posting I checked the docs... what I was hoping for was best practice for creating a thread safe but shareable lifetime (with TTL feature)... will close though as more of a question...
