### ISSUE TITLE
Question: RegisterConstructorDependency for Generics?

### ISSUE THREAD

**Issue by Mike-EEE** [seesharper/LightInject#408]
First off, we launched v2 of [ExtendedXmlSerializer](https://extendedxmlserializer.github.io/) late last year and LightInject has been really great with it. 😄 

We are working towards v2.5 and one of the goals is to provide better serialization around generics.  One of our registrations makes a call to `RegisterConstructorDependency` for a registration.  However, now we are in generics land and the type isn't readily available.  Registrations in this case have been working well with `Register` but in this case there doesn't seem to be one for `RegisterConstructorDependency`... any suggestions on how to make this work?  Thank you for any assistance you can lend!

**Comment by seesharper** [comment]
Could you come up the simplest possible example of what you are trying to do and we'll take it from there ? 😄

**Comment by Mike-EEE** [comment]
Haha alright I will try my best to keep this simple.  Generics are hardly that as you know. 😉 

Currently we have a registration as such:

```
parameter.RegisterConstructorDependency<IContents>((provider, info) => provider.Get<DeferredContents>())
```

But now we are creating a generic type of contents `IContents<T>`, but we cannot use `RegisterConstructorDependency` above as we do not know what `T` will be at compile time, so:

```
parameter.RegisterConstructorDependency<IContents<>>((provider, info) => provider.Get<DeferredContents<>>())
```

results in compiler exceptions...

**Comment by seesharper** [comment]
Are you sure that you need to use `RegisterConstructorDependency` here. That is mostly useful when you need access to the type for which the dependency is injected. An example would be injecting `ILog` where you need an `ILog` instance that is tied to the type is is being injected into.

**Comment by Mike-EEE** [comment]
Oh... well in this case it's to protect against dependency recursion that we're experiencing.  I suppose I could think about this another way now that we're revisiting it. 👼

**Comment by seesharper** [comment]
If you need to defer the service resolution, you could also inject a `Lazy<T>` or a `Func<T>` 👍

**Comment by seesharper** [comment]
I see. We can use the decorator pattern to solve this. 

```
using LightInject;

var container = new ServiceContainer();
container.Register(typeof(IBar<>), typeof(Bar<>));
container.Register<IFoo,Foo>();
container.Decorate(typeof(IBar<>), typeof(DeferredBarDecorator<>));
var foo = container.GetInstance<IFoo>();


public interface IBar<T>
{
    void DoStuff();
}

public class Bar<T> : IBar<T>
{
    public void DoStuff()
    {
        Console.WriteLine("Hello from bar");
    }
}

public class DeferredBarDecorator<T> : IBar<T>
{
    private readonly Lazy<IBar<T>> _lazyBar;

    public DeferredBarDecorator(Lazy<IBar<T>> lazyBar)
    {
        this._lazyBar = lazyBar;
    }

    public void DoStuff()
    {
        _lazyBar.Value.DoStuff();
    }
}

public interface IFoo
{

}

public class Foo : IFoo
{
    public Foo(IBar<string> bar)
    {
        bar.DoStuff();
    }
}

```

**Comment by Mike-EEE** [comment]
Ah of course... the problem is that the root registration has a dependency that circles back around to interface that is being registered.

So, I think the course of action here is to be more explicit in our dependencies.  In this case, our `RuntimeSerializer` [here](https://github.com/wojtpl2/ExtendedXmlSerializer/blob/master/src/ExtendedXmlSerializer/ContentModel/RuntimeSerializer.cs#L39), rather than referencing `IContents`, reference `DeferredContents` instead.

I think I have a better grasp of this problem now.  Thanks for being so responsive and engaging!
