### ISSUE TITLE
Register Singleton lifetime

### ISSUE THREAD

**Issue by lutaiphong** [seesharper/LightInject#415]
Sorry for this stupid question. How can I register a singleton lifetime object?

**Comment by seesharper** [comment]
No such thing as a stupid question 😺 

```
container.Register<YourClass>(new PerContainerLifetime());
```

alternatively if you already have an instance of an object 

```
var instance = new YourClass();
container.RegisterInstance(instance);
```

**Comment by lutaiphong** [comment]
Thank you so much! 👍
