### ISSUE TITLE
Struggling with strange recursive dependency 

### ISSUE THREAD

**Issue by adyshimony** [seesharper/LightInject#430]
Hi, I am changing our app to use lighInject indstead of autofac. I an struggling for 2 days with this error. Its happening so far only for a specific view model.

From some reason, it trows an error for BleDevice model.

``Recursive dependency detected: ServiceType:System.Collections.Generic.IEnumerable`1[PetActivityMobile.Core.Models.Device.BleDevice], ServiceName:]
``

When calling :

```
var viewModel = _container.GetInstance(viewModelType);
```

I am getting the error. Can't figure out why, its a very simple model.

```
namespace PetActivityMobile.Core.Models.Device
{

    public class BleDevice
    {
        public string MacAddress { get; set; }
        public string Name { get; set; }
        public bool IsConnected { get; set; }
        public bool IsAssigned { get; set; }
        public string DisplayTitle { get; set; }
        public int Index { get; set; }
        public string IndexTitle { get; set; }
    }
}

```

The view model is holding a list of this model. Nothing is injected in the constructor.
Remove this list from the viewmodel, and the error is gone. 

I am registering viewmodels this way:

`_container.RegisterAssembly(assembly, (serviceType, implementingType) => serviceType.Namespace.Contains("ViewModel"));`

If I can't solve it, I will have to find another IOC..
Any idea?

Thanks,

Ady.

**Comment by adyshimony** [comment]
Ok even more strange:

```
        private List<string> _deviceList; - working!
        private IList<string> _deviceList; - not working
        private ObservableCollection<string> _deviceList; - not working
```

Why Lightinject is not working with some of the lists?

**Comment by adyshimony** [comment]
Turn off property inject solved it

var container = new ServiceContainer(new ContainerOptions { EnablePropertyInjection = false });

**Comment by seesharper** [comment]
Does this also solve #431 ?

**Comment by adyshimony** [comment]
Its not injecting it anymore so I don't need it, but if you try to compile ObsarvableCollection<T> of any T, its not working.

**Comment by seesharper** [comment]
Could you come up with a complete set of steps to reproduce this error?

This is what I've got 

```
var container = new ServiceContainer();
container.Register<ObservableCollection<string>>();
container.Compile<ObservableCollection<string>>();
```

Works fine on my machine 😄

**Comment by adyshimony** [comment]
Yep,  I didn't register it :)
I thought assembly scan enough?

Closing.
Thanks!
