### ISSUE TITLE
Challenge (Help wanted) Possible memory problem

### ISSUE THREAD

**Issue by seesharper** [seesharper/LightInject#434]
Just recently we updated the `LightInject.Microsoft.DependencyInjection` package to confirm with the latest version of `Microsoft.Extensions.DependencyInjection.Abstractions`. What we discovered pretty much by accident was that the memory consumption went through the roof when used in a ASP.NET Core web application. 

What we have found so far is that it is probably related to how we resolve `IEnumerable<T>`. In the old version of `LightInject.Microsoft.DependencyInjection` we used to create an explicit registration of `IEnumerable<T>` where we in the new version just offload this to LightInject itself. The latter causing the app to consume a lot of memory. 

We have created a test web app to demonstrate this behavior and a toggle to switch between the old and the new way of handling `IEnumerable<T>` 

https://github.com/seesharper/TestWebApp/blob/5c7ee7c3308eeaa3d1a5fb96a77bc6e0c3b6a859/TestWebApp/Startup.cs#L40

Using the memory diagnostics in VS 2017 (15.8 preview 5) we can see that something is wrong. 

With `useExplicitEnumerable = false`

![image](https://user-images.githubusercontent.com/1034073/44083561-9ac4e310-9fb4-11e8-8dec-b9ca4f51c638.png)

With `useExplicitEnumerable = true`
![image](https://user-images.githubusercontent.com/1034073/44083644-e30362f0-9fb4-11e8-8bbf-42d6cf88bcec.png)

So far we have not been able to reproduce anything like this apart from what we are seeing in the test web application.  As mentioned it seems related to `IEnumerable<T>`, but that is all we know for now. 

Any suggestions/input on this problem would highly appreciated.

**Comment by leandro86** [comment]
Hi @seesharper!

I've looked at the issue, and, as you said, it's related to emitting the same code multiple times. I managed to reduce the memory usage, but I'm not very sure if a missed something: I still need to perform a few tests.

Here's a screenshot with "useExplicitEnumerable = false":

![imagen](https://user-images.githubusercontent.com/1261279/44314022-7dea1380-a3e9-11e8-9b8a-08cb7177ad70.png)

I only added a dictionary to check if the GetInstanceDelegate exists before we create it. You can take a look at the code here: https://github.com/leandro86/TestWebApp/commit/c6d57f44ed9310ddd09f8c197956c6732272adf2

**Comment by seesharper** [comment]
@leandro86 This actually looks very promising. I was overcomplicating this and your simple solution seems to be more than enough, at least for now 👍  I just ran the test suite for LightInject with this change and all tests passed. 😎

**Comment by seesharper** [comment]
No need. It's already there 😄 
https://github.com/seesharper/LightInject/pull/436

**Comment by seesharper** [comment]
Fixed by #436
