### ISSUE TITLE
How to provide one of several constructor dependencies from a factory method?

### ISSUE THREAD

**Issue by vegar** [seesharper/LightInject#435]
I'm sitting with service fabric, and are wondering how to apply dependency injection in a good way...

The reliable services has a `CreateServiceInstanceListeners`-method that you override to provide the different listeners for the service. You would typically do this by creating an instance of `ServiceInstanceListener`. This class takes a factory function as it's first parameter:

    public ServiceInstanceListener(Func<StatelessServiceContext, ICommunicationListener> createCommunicationListener, string name = "");

So this factory function should create an instance of your listener.

My listener has a constructor with multiple dependencies. One of them is the `StatelessServiceContext`-instance provided in the factory function. 

Is there a way of resolving a service where one of the dependencies is provided?

e.g.  `container.GetInstance<MyServiceListener>(context)`

so that the container will use the provided services for any matching constructor parameter and resolve the rest from the container?

**Comment by seesharper** [comment]
The general advice here is not to mix runtime data with services. In fact, this is probably one of the features I regret ever adding to LightInject. We are actually considering marking these register methods obsolete and remove them in the next major release. Instead of injecting runtime data, it is better to let this data flow through the methods exposed by the service.

In your case it would probably be better to inject some kind of `IContextAccessor` that provides the context.

This topic is very well covered in this article by @dotnetjunkie

https://www.cuttingedge.it/blogs/steven/pivot/entry.php?id=99

**Comment by vegar** [comment]
I've skimmed through the blog post, but have to look into it more detailed at a later point (better time, larger screen..)

That said, I think I get the principles that he is pointing at, but I'm not sure they apply in this case. 
In his example of a  `MoveCustomerCommand` and it's `CustomerId` it's quite clear that the customerId is something that should be provided at runtime as an input to the `Execute` method. No doubt about that. 

In my case, though, I'll argue that the `context`-parameter that I want to inject later is not part of my application logic in any way. It's not something that I can provide at runtime anywhere. 

What I have, is the following API:  

`ServiceFabric.RegisterService(string Name, Func<Context, StatelessService>serviceFactory)`.  

And the `StatelessService`-constructor 

`StatelessService(StatelessServiceContext serviceContext)`

Now I have two options:

1. Create my stateless service manually without any dependency injection / management at all
2. Let the ioc container resolve the stateless server for me and that way also manage the dependencies that it might need. That is not possible, though, without having some way of telling the ioc container : `pls resolve a MyStatelessService for me, and all other dependencies that it might have. And when it asks for a context, use this context that I've been given`.

I *could*  create a `IContextAccessor` as you suggest, but then I would need to be able to setup that accessor in some way at the point where service fabric choose to call the fabric method. Like a singleton where I can set the context, just so that it can be fetched again right after. 

```
container.Register<MyStatelessService>();
container.RegisterInstance<IContextAccessor>(new ContextAccessor());

ServiceFabric.RegisterService("MyStatelessService", context => {
    container.GetInstance<IContextAccessor>().SetContext(context);
    return container.GetInstance<MyStatelessService>();
});
```

Or something similar. 
I'm pretty sure this isn't much nicer than what I would have if I was able have something like `container.GetInstance<MyStatelessService>(context)`. 

But of cause, if Lightinject doesn't support what I want, and it is possible to make it work in another way, the working way will always be better than the impossible way...

**Comment by seesharper** [comment]
Could the following be an acceptable approach?

https://blog.abatishchev.ru/2018/06/02/service-fabric-and-dependency-injection-part-1-stateful-service/

**Comment by seesharper** [comment]
@vegar Did you manage to get this working?

**Comment by vegar** [comment]
I haven’t had the time. Just close the case, though. I’ve received good input :-)


________________________________
Fra: Bernhard Richter <notifications@github.com>
Sendt: fredag, september 14, 2018 8:16 pm
Til: seesharper/LightInject
Kopi: Vegar Vikan; Mention
Emne: Re: [seesharper/LightInject] How to provide one of several constructor dependencies from a factory method? (#435)


@vegar<https://github.com/vegar> Did you manage to get this working?
