### ISSUE TITLE
After add fluentvalidation lightinject stops registering some types, for example BinderParameter

### ISSUE THREAD

**Issue by Merdok94** [seesharper/LightInject#445]
public IServiceProvider ConfigureServices(IServiceCollection services)
        {
            services.AddMvcCore().AddVersionedApiExplorer(o => o.GroupNameFormat = "'v'VVV");
            services.AddCors();
            services.AddMvc(options =>
            {
                options.Filters.Add(new ValidateModelAttribute());
            })
                .AddControllersAsServices()
                .AddJsonOptions(options =>
                {
                    options.SerializerSettings.Converters.Add(new StringEnumConverter());
                });
            //doesn't work after this
            services.AddMvc().AddFluentValidation(configuration =>
            {
                configuration.RegisterValidatorsFromAssemblyContaining<Startup>();
            });

            var container = new ServiceContainer(new ContainerOptions
            {
                EnablePropertyInjection = false
            })
            {
                ScopeManagerProvider = new PerLogicalCallContextScopeManagerProvider()
            };
            return container.CreateServiceProvider(services); ;

**Comment by seesharper** [comment]
Try adding this to your container options. 

```
DefaultServiceSelector = serviceNames => serviceNames.SingleOrDefault(string.IsNullOrWhiteSpace) ?? serviceNames.Last();
```

Alternatively use https://github.com/seesharper/LightInject.Microsoft.AspNetCore.Hosting that does this for you

**Comment by Merdok94** [comment]
Thank you so much. It works!

**Comment by seesharper** [comment]
Great 👍
