### ISSUE TITLE
Remove dependency on System.ValueTuple NuGet package when targeting .Net 4.7

### ISSUE THREAD

**Issue by vlardn** [seesharper/LightInject#447]
After switching project from .NET 4.6.1 to .NET 4.7.2 the following errors appear:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS8356	Predefined type 'System.ValueTuple`2' is declared in multiple referenced assemblies: 'System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51' and 'mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' ...
```
The possible reason is that System.ValueTuple is incompatible with .Net Framework 4.7 (because it's already built in to 4.7).

**Comment by seesharper** [comment]
Somehow I knew that dependency was trouble. I’m going to remove it completely 👍

**Comment by vlardn** [comment]
Actually there is a workarounds for now: use a .NET 4.7 build of System.ValueTuple that seems just contains references to value tuple types from mscorlib. There are 2 ways how to do it:

1) . Change to "net47" in HintPath like this: 
```
<Reference Include="System.ValueTuple, Version=4.0.3.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51, processorArchitecture=MSIL">
<HintPath>..\packages\System.ValueTuple.4.5.0\lib\net47\System.ValueTuple.dll</HintPath>
</Reference>
```
2) Or use "Update-Package -Reinstall" to update all such packages. I think this is preferable method after switching to another .NET framework version but it usually produces much more changes.

**Comment by thuannguy** [comment]
@vlardn  thank you :D Update-Package -Reinstall basically saved me a day of work 👍

**Comment by yodasad** [comment]
> I’m going to remove it completely 👍
Anyway that's the best solution, there is no need in the library "System.ValueTuple" at all if one is targeting .NET47 or higher.

**Comment by andrzejmartyna2** [comment]
The last version I'm able to use is 5.1.8.
The version 5.1.9 introduced dependency to ValueType and I no longer can use it.
Could you reopen the issue and remove the dependency?

**Comment by seesharper** [comment]
Fixed by #532

**Comment by seesharper** [comment]
@andrzejmartyna2 Version 6.3.4 has removed this dependency 👍

**Comment by andrzejmartyna2** [comment]
I'm really appreciate it! Thanks!!
