### ISSUE TITLE
Support for PackageReference in LightInject.Source

### ISSUE THREAD

**Issue by alanisaac** [seesharper/LightInject#457]
I tried searching for this issue and didn't find it, but let me know if I'm making a duplicate here!

As of version 5.2.0, the way the LightInject.Source NuGet package is set up doesn't support adding the cs file if your project is using [PackageReference-style](https://docs.microsoft.com/en-us/nuget/consume-packages/package-references-in-project-files) NuGet references as opposed to [packages.config](https://docs.microsoft.com/en-us/nuget/reference/packages-config).  This applies to .NET Core and Standard projects by default, as well as .NET Framework projects that were created or [migrated over](https://docs.microsoft.com/en-us/nuget/reference/migrate-packages-config-to-package-reference) to use the PackageReference format.  To reproduce the issue:

- Create a blank .NET Standard project
- Add LightInject.Source as a dependency
- Observe that there is no cs file that gets added

This is because the .cs.pp file gets included in the [content tag of the nuspec](https://github.com/seesharper/LightInject/blob/cd5c1d87a7a760312e867a33f40a3cb2cd20ec6b/build/LightInject.Source.nuspec#L21) as opposed to using the [contentFiles feature](https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html).  Content files are a newer way of including dependencies in NuGet packages.

Unfortunately, switching entirely to content files means there **won't be support for packages.config**.  .NET Framework projects can and are encouraged to migrate to use package reference and the SDK project style, so hopefully it will become less of a support issue moving forward.  But other libraries in similar situations have made the leap: 

- [LibLog](https://github.com/damianh/LibLog) is an example of a library that offers a source code / content-based package.  Their nuspec now [targets contentFiles](https://github.com/damianh/LibLog/blob/c21fbcda9638188f922d2b42e56635cd54a2d0d6/src/LibLog/LibLog.nuspec#L30) as the way to deliver .cs.pp files.
- [LiteGuard](https://github.com/adamralph/liteguard) offers a source package as well.  They also [use contentFiles](https://github.com/adamralph/liteguard/blob/5a69fcc833b5d1e648cc083c99d8b7d120abfbfa/src/LiteGuard/LiteGuard.Source.nuspec#L21) to deliver .cs.pp files.

I'd love to be able to use this in my .NET Standard projects!

**Comment by seesharper** [comment]
Yeah, I have been looking for a solution for this using the new csproj file format. I'll look into it

**Comment by seesharper** [comment]
@alanisaac I see that LiteGuard uses both the `files` tag and the `contentFiles` tags. Meaning it will work for both SDK style  project files and legacy style project files?

**Comment by alanisaac** [comment]
I think the `files` tag is used to pull in files from outside the package directory.  Notice that in the LiteGuard example the targets are `target="contentFiles/..."`, which means they are added to the `contentFiles` directory.

Take a look at [NuGet ContentFiles Demystified](https://blog.nuget.org/20160126/nuget-contentFiles-demystified.html), it's a pretty good guide to what the different tags do.  In the first example, there's no `files` tag, but in the second example, there is, and it explains how the files are copied.

**Comment by seesharper** [comment]
@alanisaac I guess it is not possible to support both then?

**Comment by seesharper** [comment]
@alanisaac Fixed in 5.4.0
