### ISSUE TITLE
ASPNET errors with Entity Framework

### ISSUE THREAD

**Issue by bsoulier** [seesharper/LightInject#458]
I have been using LightInject for a while, but on some part of our project we are getting weird errors.

We are using a service that wraps access to a multi-tenant db system.
We have a pretty request intensive dashboard that sometimes crash on having multiple runs of the sames API methods.

Errors are:
There is already an open DataReader associated with this Command which must be closed first.
The connection was not closed. The connection's current state is open.
The connection was not closed. The connection's current state is connecting.

This points to injecting service already being used on other calls.

I am using the default setup indicated on LightInject website (using OWIN):

```
var config = new HttpConfiguration();
var container = new ServiceContainer();
container.Register<IXXXRepository, XXXRepository>();
...
container.RegisterApiControllers();
container.EnableWebApi(config);
```

I am not using the EnablePerWebRequestScope as it is relying on HttpContext.Current,  and I am not using System.Web anywhere in my app.

Is there a way to properly make this work with Owin and scope it to each web request?

**Comment by seesharper** [comment]
So this is not hosted in IIS?

**Comment by bsoulier** [comment]
It is hosted in IIS, sorry for the missing info.

Is there a way to hook up to the We API HTTP pipeline to ensure that a given service is only retrieved in that case?

Thanks, Ben

**Comment by seesharper** [comment]
Can you take a look at this and see if that can help?
https://github.com/seesharper/LightInject/issues/339

**Comment by bsoulier** [comment]
This actually was an error from my side, everything is working fine.
Woot to this awesome LIB!
