### ISSUE TITLE
Ask about how to use it in large projects

### ISSUE THREAD

**Issue by kaki104** [seesharper/LightInject#459]
Version Information
5.1.0
Platform
Windows, WPF, .Net Framework 4.6.1
An example that shows the issue.
We are using LightInject in a large project developed with WPF. There are over 70 class library projects. However, if you register all the dlls that you use after the application starts, the memory usage will increase dramatically. If I try to create a memory snapshot in VisalStudio 2017, an error occurs. Is this the right thing to use?

**Comment by rubenwe** [comment]
> However, if you register all the dlls that you use after the application starts ...

Do you register all public types in those Assemblies or only certain types?

> ... the memory usage will increase dramatically.

How dramatic is dramatic? How big are the assemblies you are loading?

**Comment by seesharper** [comment]
The recommended approach is to implement `ICompositionRoot` and use that to register services. It is much better to be explicit rather than filling up he container with services that don't belong there. The reason you're seing such a increase in memory usage when scanning is that all 70 assemblies gets loaded into the AppDomain at startup.

**Comment by kaki104** [comment]
@rubenwe @seesharper 
I just confirmed and it was late. Sorry.

1. All public types are registered

2. After registering the type, the memory of 98.7MB is increased.
197.6MB - 98.9MB = 98.7 MB

3. I saw a document on how to use ICompositionRoot. By the way, I do not know how to actually apply it. Where is the implemented example?

**Comment by jordansjones** [comment]
@kaki104 I can provide a simple example here.

This is an example of a composition root from one project
```csharp
public sealed class CoreIocModule : ICompositionRoot
{
        public void Compose(IServiceRegistry serviceRegistry)
        {
            serviceRegistry.Register<IEnvironment, EnvironmentWrapper>(new PerContainerLifetime());
        }
}
```

And another composition root from another project
```csharp
public sealed class DataIocModule : ICompositionRoot
{

    public void Compose(IServiceRegistry serviceRegistry)
    {
        serviceRegistry.Register<IDataStore, DataStore>(new PerContainerLifetime());
    }

}
```

And how to use them:
```csharp
var serviceContainer = new ServiceContainer();
serviceContainer.RegisterFrom<CoreIocModule>();
serviceContainer.RegisterFrom<DataIocModule>();

var dataStoreInstance = serviceContainer.GetInstance<IDataStore>();
```

**Comment by seesharper** [comment]
@jordansjones That is definitely the way to go. It is much better to have multiple composition roots that explicitly registers the services. Otherwise (all public types), it is very easy to end up with a lot of services in the container that is really not needed.
