### ISSUE TITLE
Scoped registrations

### ISSUE THREAD

**Issue by furier** [seesharper/LightInject#479]
Hi

I am building a multi tenant asp net core application, where I have a hangfire instance running for each tenant. 

Each tenant have their own database, and the jobs executed on hangfire needs to resolve tenant specific dependencies like their corresponding ef core context.

So what I would like to do is give each hangfire instance their own lightinject scope but make some scope specific registrations, so that when the dependency injection resolves the ef core context it constructs it with the correct connection string.

Is it possible to have scope specific registrations, or do I need to use a different IoC container with child container feature?

**Comment by chrismcv** [comment]
@furier  - just wondering if you ever came up with a solution to this? Am in a simliar boat, and looking for guidance!

**Comment by furier** [comment]
I am not using LightInject but I guess you could just new up multiple containers and add registrations to them individually, which should work the same. At least that's what I ended up doing with aspnet core's built in DI container.
