### ISSUE TITLE
Conditional constructor parameter injection

### ISSUE THREAD

**Issue by bounav** [seesharper/LightInject#484]
Hello,

I'd like to be able to register callback that lets me do some checks on the type being resolved before resolving a constructor dependency.

Something very similar to [property injection on existing instance](http://www.lightinject.net/#property-injection-on-existing-instances).

As well as having the factory available in the registration's lambda callback, it would be super useful to __know the type__ of the class of which the constructor is being resolved.

```c-sharp
public class HelloWorld
{
    public HelloWord(IFoo foo)
    {
        ...
    }
}

registry.Register<IFoo>((factory, serviceType) =>
     {
          return serviceType.Namespace.Contains("Blahblah") 
              ? factory.GetInstance<Foo>()
              : factory.GetInstance<Bar>();
     }
```

At the moment it seems the only way to achieve this is using an [initializer](http://www.lightinject.net/#initializers)?

PS: Did I mention I'd like to do all this with property injection disabled?

**Comment by seesharper** [comment]
You can check out the `RegisterConstructorDependency` method . It passes the parameter for which the dependency is being injected.

**Comment by bounav** [comment]
Thanks! I can't believe I missed [in the documentation](http://www.lightinject.net/#constructor-injection).

It sounds like `RegisterConstructordependency` is just what I'm looking for.

I'll close this issue now. Thanks again for pointing me in the right direction one more time ;)
