### ISSUE TITLE
AspNetCore 2.2 AspNetCoreHostingModel InProcess not working

### ISSUE THREAD

**Issue by valeriob** [seesharper/LightInject#488]
Hi,
if you create a new AspNetCore 2.2 project and add LightInject.Microsoft.DependencyInjection package, configure the container in ConfigureServices

`var container = new ServiceContainer();
return container.CreateServiceProvider(services);`

when you run it blows with :
 
System.InvalidOperationException: 'No service for type 'Microsoft.AspNetCore.Hosting.Server.IServer' has been registered.'

**Comment by seesharper** [comment]
Could you create a simple repro of this and push it up on Github?

**Comment by valeriob** [comment]
Suere,
there you go. https://github.com/onitgroup/LightInject_AspNetCore2_2InProcess
(Run it With IIS Express)

**Comment by seesharper** [comment]
Take at look at this PR

https://github.com/onitgroup/LightInject_AspNetCore2_2InProcess/pull/1

**Comment by valeriob** [comment]
Thanks, i was using it wrong :D

**Comment by valeriob** [comment]
I would like to understand better, i'm looking at the code in 
https://github.com/seesharper/LightInject.Microsoft.AspNetCore.Hosting/blob/88fc26fddcb42f2bde50ef3fc59be2c21191b279/src/LightInject.Microsoft.AspNetCore.Hosting/LightInjectWebHostBuilderExtensions.cs
i do not see anthing related to the issue, what's the difference in using this package instead of the approach i used ?

**Comment by seesharper** [comment]
It sets a couple of options that makes LightInject 100% compliant with the default container in Microsoft.Extensions.DependencyInjection. 

https://github.com/seesharper/LightInject.Microsoft.DependencyInjection/blob/0b57968e2328f62bc262da9ce75d431954c82cfc/src/LightInject.Microsoft.DependencyInjection/LightInject.Microsoft.DependencyInjection.cs#L207

**Comment by valeriob** [comment]
There you go: 
options.DefaultServiceSelector = serviceNames => serviceNames.SingleOrDefault(string.IsNullOrWhiteSpace) ?? serviceNames.Last();

Thanks
