### ISSUE TITLE
Problem with "Attempt to create a disposable instance without a current scope"

### ISSUE THREAD

**Issue by shinjiDev** [seesharper/LightInject#49]
Hi
I'm using the get method of JQuery to return a json to fill a combobox, and also to receive an html and  fill it in a div.
The problem is that It works in the first requests, but after that it throws an exception:
"Attempt to create a disposable instance without a current scope"
It looks related to lightinject.

How did it happen to me?And also, how can i fix it?
Thanks for your time

**Comment by ZOXEXIVO** [comment]
Issue not solved!
