### ISSUE TITLE
Question: Fallback for Registered Services

### ISSUE THREAD

**Issue by Mike-EEE** [seesharper/LightInject#518]
I have registered a fallback delegate via the `IServiceContainer.RegisterFallback` and all works well when the type is not registered.

However, I am finding that this delegate is not used for registered services and an exception occurs during resolving them.

What I would like to do is use this `RegisterFallback` delegate when an exception occurs during resolution of a service.  

To be more specific, I would like to have the service container attempt to resolve a service as normal, and if it runs into an exception, call the fallback delegate which will look for a singleton on the class instead.  If the class does not have a singleton, then throw the exception instead.

Is this possible to do with all of the magic components found in LightInject? :)

**Comment by seesharper** [comment]
Could you create a small repro, console app or something I can run to see what you are trying to do?

**Comment by Mike-EEE** [comment]
Doh!  Should have done that to start. :)

OK... [This test](https://github.com/Mike-EEE/LightInject-Fallback/blob/master/LightInject-Fallback/LightInject-Fallback/UnitTest1.cs#L12-L28) passes while [this one doesn't](https://github.com/Mike-EEE/LightInject-Fallback/blob/master/LightInject-Fallback/LightInject-Fallback/UnitTest1.cs#L30-L42).  I basically want `IFrom` to resolve to the registered `Singleton` but doing so by using the `RegisterFallback` delegate when it hits the exception.

Please let me know if you have any further questions around this. 👍

**Comment by seesharper** [comment]
I understand part of the problem here. 

`container.Register(typeof(IFrom), typeof(Singleton));`

The `Singleton` class does not have a public constructor so that is what's failing 

You could this instead.

`container.RegisterInstance<IFrom>(Singleton.Default);`

At least that would make the test pass 😀

I have not looked in detail at your code, but in general we can state the following.

* Don't use exceptions to flow program logic. Exception handling in .Net is dead slow so you want to avoid throwing/catching exceptions unless there really is an "exception".

* LightInject will use the last registered service if there are multiple registrations of the same interface. 

```
container.Register<IFoo,Foo>();
container.Register<IFoo,AnotherFoo>();
var instance = container.GetInstance<IFoo>();
// Instance is now AnotherFoo since that was the last registration.
```

Maybe we don't need `RegisterFallback` at all?

If you want to register a default service, you can do that as early as possible before other services are registered. 

Did I completely miss the point here? 😀

**Comment by Mike-EEE** [comment]
> Did I completely miss the point here? 😀

Kinda. 😁

I appreciate the time looked into this.  

To sum up: LightInject can locate `Singleton` just fine via the registered fallback delegate.

So far so good.

Now we move to a mapped registration (from `IFrom` to `Singleton`), which does not use the fallback and fails with an exception.  Or rather, there appears to be no way of rerouting the exception so that it uses the fallback as a, well, fallback. :)

I could indeed use `container.RegisterInstance<IFrom>(Singleton.Default);`.  However, I am wanting to find a generalized strategy that basically says "if you cannot instantiate an object for whatever reason, use this (fallback) delegate instead to locate the instance."

Well actually, this _does_ work exactly as expected with direct location.  It's the mapped registrations where we are running into the issue here.

What I was looking for was an obvious way to re-route/extend/override the location mechanism to somehow capture the exception state and re-route to another provided implementation/delegate of some sort. Since this does not appear to be apparent, I will dig further into some creative thinking to see if I can get what I am looking to accomplish.

Thanks again for your valuable time @seesharper and for your efforts with this project.  I am a big fan. 👍

**Comment by Mike-EEE** [comment]
OK @seesharper FWIW I figured it out.

The trick is not to use mapping registrations, but the factory method registrations as such:

```
var container = new ServiceContainer();
container.Register<IFrom>(x => x.GetInstance<Singleton>());
```

That resolves the singleton from the fallback as expected.  Passing test can be [found here](https://github.com/Mike-EEE/LightInject-Fallback/blob/master/LightInject-Fallback/LightInject-Fallback/UnitTest1.cs#L30-L42).
