### ISSUE TITLE
Encountering IAsyncDisposable Error

### ISSUE THREAD

**Issue by Mike-E-angelo** [seesharper/LightInject#577]
Thank you again for adding IAsyncDisposable support.  However, I am now getting a weird exception on disposing of Blazor controls:

```
System.InvalidOperationException: The type DragonSpark.Presentation.Environment.Browser.Document.FocusedElement only implements `IAsyncDisposable` and can only be disposed in an asynchronous scope started with `BeginScopeAsync()`
   at void LightInject.Scope.Dispose()
   at void LightInject.Microsoft.DependencyInjection.LightInjectServiceScope.Dispose()
   at ValueTask Microsoft.Extensions.DependencyInjection.AsyncServiceScope.DisposeAsync()
   at ValueTask DragonSpark.Composition.Construction.ServiceScopeFactory+Scope.DisposeAsync() in D:/a/1/s/Framework/DragonSpark.Composition/Construction/ServiceScopeFactory.cs:line 35
```

Note that the above code can be found here:
https://github.com/DragonSpark/Framework/blob/master/DragonSpark.Composition/Construction/ServiceScopeFactory.cs

The first thing that catches my eye is a reference to `BeginScopeAsync` which I do not see anywhere.

The other issue is that while `LightInject.Scope` is now IAsyncDisposable it appears that `LightInject.Microsoft.DependencyInjection.LightInjectServiceScope` is not and still only implements `IDisposable` only.

Anyways, I may be confused here but wanted to start the confirmation and see if there is something I am overlooking/misunderstanding.  Thank you for any assistance/consideration.

**Comment by Mike-E-angelo** [comment]
Excellent, thank you @seesharper it is appreciated.  Any chance you can update `LightInject.Microsoft.Hosting` to point to this new version?  [It is what I am using to pull in all your magic](https://github.com/DragonSpark/Framework/blob/master/DragonSpark.Composition/DragonSpark.Composition.csproj#L10) :D

**Comment by seesharper** [comment]
@Mike-E-angelo  LightInject.Microsoft.Hosting 1.5.0 should pull in everything you need 👍😃

**Comment by Mike-E-angelo** [comment]
Confirmed @seesharper!  Thank you very much 🙏
