### ISSUE TITLE
Register Multiple Instances Without Needing A New Service Name

### ISSUE THREAD

**Issue by dbuksbaum** [seesharper/LightInject#68]
I often need to register multiple instances of the same base interface, for example an IPlugIn.

In code, I want to do this:
serviceRegistry.RegisterInstance<IPlugIn>(mySuperPlugIn);
serviceRegistry.RegisterInstance<IPlugIn>(myOtherSuperPlugIn);

but now, I have to provide a service name. some code:
serviceRegistry.RegisterInstance<IPlugIn>(mySuperPlugIn, "Plug In One");
serviceRegistry.RegisterInstance<IPlugIn>(myOtherSuperPlugIn, "Plug In Two");

Its a minor thing, but sometimes the IDs for these instances are not string based so I have to convert to strings just to satisfy this need. In a few cases I just do a Guid.NewGuid(). I retrieve these items by IEnumerable<> or IList<>, so the service name is not used.

**Comment by Shazwazza** [comment]
I also have this situation however I am using the container to build each instance in the collection. From what I can tell, there's really no way to do this without naming each item with LightInject, can you confirm this? Just seems like unless you keep the name of the item very small this will take up more memory than might be needed if the collections have quite a few items. I realize that in the underlying code it is using a ConcurrentDictionary where the name of the service is the key but maybe it would be possible to have a different type of registration that just uses the implementing type as the key?

**Comment by seesharper** [comment]
Actually, starting from LightInject 3.0.2.2 you can do this.


    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.Register<SomePlugin>();
            container.Register<AnotherPlugin>();

            var plugins = container.GetAllInstances<IPlugin>();

            Debug.Assert(plugins.Count() == 2);
        }
    }

    public interface IPlugin { }

    public class SomePlugin : IPlugin { }

    public class AnotherPlugin : IPlugin { }


Does that get you out of the woods? :)

Best regards 
Bernhard Richter

**Comment by Shazwazza** [comment]
Actually, yes it does for what I'm using this for right now! :) Didn't realize a new version was released today just after I started tinkering with this library. Nice!
