### ISSUE TITLE
PCL version of LightInject?

### ISSUE THREAD

**Issue by prasannavl** [seesharper/LightInject#69]
Currently, it ships as separate compilations for different platforms. 

I see a lot of use of ILGenerator in code. Can a PCL version be expected, or is that not a part of what you have planned?

**Comment by anisimovyuriy** [comment]
Looking forward for LightInject.PCL nuget as well :). 
Great job Bernard!
Thanks.

**Comment by omares** [comment]
Any news on this?

**Comment by seesharper** [comment]
LightInject 4.0 supports PCL profile 111

**Comment by jzeferino** [comment]
@seesharper there is any place where i can see what are the PCL profiles that LightInject supports?

**Comment by seesharper** [comment]
Profile111

**Comment by jzeferino** [comment]
Yes @seesharper , i read that above. But i'm curious if it supports other profiles.

**Comment by seesharper** [comment]
Nope, profile 111 is the only profile supported by LightInject. Unless you need support for .Net 4.0, which is NOT supported by Microsoft anymore or the old windows phone (silverlight), you should be able to use profile 111. This also confirms to the Net Platform Standard 1.1 which will be the "lowest" platform standard supported by LightInject once it has been updated to the latest RC2 bits (CoreCLR).
https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md

**Comment by jzeferino** [comment]
I was using lightInject with Xamarin. Profile 111 worked. Thanks for the clear answer.

**Comment by seesharper** [comment]
No problem :)
