### ISSUE TITLE
Access type of class declaring dependency in factories

### ISSUE THREAD

**Issue by MikeHanson** [seesharper/LightInject#91]
We have a specific scenario, but I think it suggests a general feature requirement.

In the application we are building we want LightInject to inject a type specific logger when it is declared as a dependency.  In order to do this either the type or name of the class declaring the dependency must be passed to the constructor of the logger implementation.

We tried achieving this via a factory but neither of the objects passed to the factory delegate give us access to the declaring type i.e. the type into which the instance being created is to be injected

**Comment by seesharper** [comment]
After thinking about this for a while I have found a solution that seem to work as expected.

    class Program
    {
        static void Main(string[] args)
        {
            var container = new ServiceContainer();
            container.ConstructorDependencySelector = new CustomConstructorDependencySelector();
            container.Register<IFoo, Foo>();
            container.GetInstance<IFoo>();
        }

        public class CustomConstructorDependencySelector : ConstructorDependencySelector
        {
            public override IEnumerable<ConstructorDependency> Execute(ConstructorInfo constructor)
            {
                ConstructorDependency[] dependencies = base.Execute(constructor).ToArray();

                ConstructorDependency logDependency = dependencies.FirstOrDefault(d => d.ServiceType == typeof(ILog));
                if (logDependency != null)
                {
                    Expression<Func<ILog>> factoryExpression = () => LogManager.GetLogger(constructor.DeclaringType);
                    logDependency.FactoryExpression = factoryExpression.Body;
                }

                return dependencies;
            }
        }

        public interface IFoo { }

        public class Foo : IFoo
        {
            public Foo(ILog log)
            {
                Debug.Assert(log.Logger.Name == typeof(Foo).FullName);
            }
        }
    }
