### ISSUE TITLE
Issues implementing a ILifetime for Session (SessionLifetime)

### ISSUE THREAD

**Issue by zhech2** [seesharper/LightInject#95]
I am writing an application built on Asp.net MVC and have the need to store some of my objects in Session.  I would like the objects to be registered with the LightInject ServiceContainer and be stored in Session based on a custom Session Lifetime.  

I can see several ways that this could be implemented.  
1. The Scope class tracks IDisposable instances.  If this object could be customized. I could cast to a derived type and track the session objects using a SessionLifetime from the Custom Scope. 
2. Provide another argument for ILifetime.GetInstance that takes the ServiceRegistration which would allow for unique identification of the object.
3. Provide another interface for Lifetime that takes the ServiceRegistration.  IRegistrationLifetime or something similar that could be used instead of ILifetime.

Is one of my suggestions a possibility?  Is there another way that this functionality could be implemented?  I would be willing to implement one of these if there is a way you would prefer (with 100% test coverage).

Thank you,
Justin

**Comment by arrcher** [comment]
Is it right that PerSessionLifetime is still not supported out of the box?

Thank you,
Alexei
